### ISSUE TITLE
Spark Immunity List

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#104]
I would like to have an area where you can make a list of people who will never be charged sparks on your channel.

**Comment by Firebottle** [comment]
Worked on this a bit. The exempt list is currently in the moderation area. The actually settings are saved to settings.json since it is not an interactive group.

To Do:
Figure out a way to get the cached userlist from groupsService.js over to control-router.js so we don't need to hit the harddrive to see if someone is exempt every time we press a button.

**Comment by ebiggz** [comment]
I've added a cached list to the main process. The cache is updated whenever the user edits the list via an event sent from the render process to the main.

**Comment by Firebottle** [comment]
Released 4.1.0
