### ISSUE TITLE
Connect / Disconnect Sound

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#105]
Add in the option to play a sound when Firebot connects and disconnects. That way it's easier to tell when the buttons are active without needing to visit the channel.

**Comment by Saiasanc** [comment]
I second this idea and would even encourage you to make a high(ish) priority. I have been seeing a LOT of issues with streamers interactive controls go down. And they don't even notice until someone in chat notifies them. Some kind of sound to notify you it disconnected would be awesome. Maybe even allow the ability to choose which sound to play from the settings screen.

**Comment by Firebottle** [comment]
This is in the newest beta. Customization of sounds will come later on.
