### ISSUE TITLE
Windows Defender and AVG stopping Firebot from being opened. 

### ISSUE THREAD

**Issue by EvilKupo** [Firebottle/Firebot#106]
I just downloaded the Beta 1 and my computer locked it down quick. AVG says it contains a "unique file" that "may contain something bad" for my computer and Windows (windows 10) says something similar. 

Even running with admin and/or compatibility it still says I don't have the permissions.

Tried to download and run again with the same results.

**Comment by Firebottle** [comment]
Hmm... Havent heard of that yet. Windows should ask if you want to allow Firebot to use the network though. It needs permissions to connect the app to the overlay file.

**Comment by Firebottle** [comment]
Were you able to get this fixed?

**Comment by Firebottle** [comment]
It's been a week with no response. Closing this one.
