### ISSUE TITLE
Firebot 3.0 Beta 1 and 2 Do Not Show on Mixer Channel

### ISSUE THREAD

**Issue by KirscheBuster** [Firebottle/Firebot#109]
Here is a screen capture of my setup showing that Firebot is working locally without issue. When I connect the bot to Mixer it does not display on stream. Any ideas as to what to check? Firewall and antivirus are disabled.

https://www.screencast.com/t/lI4Dmd0EPkb3

**System:**
OS Name	Microsoft Windows 10 Pro
System Model	Inspiron 15 7000 Gaming
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM)	16.0 GB

**Browsers:**
Chrome 58.0.3029.110 (64-bit)
Microsoft Edge 38.14393.1066.0

**Comment by Firebottle** [comment]
I see you have controls in the tablet view. Do you have them on desktop and mobile as well?

**Comment by KirscheBuster** [comment]
I don't. I will test shortly and let you know.

**Comment by KirscheBuster** [comment]
@Firebottle embarrassed. That was the issue :) Love the new interface. Thank you for all of your work on this.
