### ISSUE TITLE
Assigning multiple game keys to a button does not press them all at once.

### ISSUE THREAD

**Issue by EarWaxCandy** [Firebottle/Firebot#110]
The multi-key buttons don't seem to exist any more. i tried adding multiple game control effects, however i'm guessing they are pressed in sequence rather than at the same time.

**Comment by Firebottle** [comment]
The are pressed in sequence, but it should be under a millisecond apart and it should register as multiple keys being pressed. I'll research.

**Comment by EarWaxCandy** [comment]
just tested shift and a letter in notepad... didn't capitalize :(

**Comment by Firebottle** [comment]
okay, I'll work on it

**Comment by Kylix-Tyfurious** [comment]
Same here @Firebottle 

I setup a control + f1 combo and it didn't trigger anything to happen in OBS, though the chat text came through to Mixer and it showed that I pressed the button in the log.

**Comment by Firebottle** [comment]
Yep! I'll get it all fixed up like it was before. Until then you can change hotkeys to a single button press somewhere.

**Comment by awrebels** [comment]
Is there a single button that works as an OBS hotkey when focus is not on the program? The multikey seemed to work but i've tried the function keys to no avail. Thoughts?

**Comment by Firebottle** [comment]
If the newest full release is stable and I don't get any bug reports, game controls will be my next focus. I'll be adding back the same multi key functionality that was there before. But as of right now I don't think there is a key that will trigger OBS.

**Comment by Firebottle** [comment]
Please try the new release which re-introduces multi key presses and makes some tweaks to try to fix OBS and other apps not registering key presses.

https://github.com/Firebottle/Firebot/releases/tag/v3.1.1

If you run into any problems please open a new issue.

@EarWaxCandy @awrebels @Kylix-Tyfurious
