### ISSUE TITLE
Overlay: Button Press Info

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#111]
I'd like to give people the option to display the names of people pressing buttons in the overlay. It would just be a running feed similar to chat or event logs, except it'd show who is pressing what.

**Comment by Firebottle** [comment]
It'll be easy to output button press info to the overlay. But it also needs to be customizable. Should have options for font, color, position, etc...

**Comment by Firebottle** [comment]
Dev is completed on the override effect for this one. The global settings for it are going to be a bit different and I think @ebiggz is working on that.

Note:
This currently shows one press at a time in the overlay. The info will animate in, and either stay for X duration, or it will immediately animate out to show another press. Due to the time it takes to animate this won't show every single button press if there is spam. It's mainly meant for "regular use".

With that said, we could swap to a running list style if we want to keep up with spam. Similar to how a chat window works. If we want to do that we could build a toggle into the effect to switch between the two.

**Comment by ebiggz** [comment]
Released in v4.6
