### ISSUE TITLE
Buttons do nothing

### ISSUE THREAD

**Issue by traincrafter** [Firebottle/Firebot#114]
I downloaded the Bot same as the developer do in the video tutorial and started it in the same way but nothing happens when I click on the Login Button (wheather on Brodcaster or Bot). Also nothing happens when I click on the buttons on the top.

**Comment by Firebottle** [comment]
Have you tried downloading the zip again and unzipping the folder somewhere? If so, give me some info about your machine. This app only works on windows 64bit right now.

**Comment by traincrafter** [comment]
I downloaded it 3 times and unziped it in the same way you did in the video,
My machine running on Windows 10 Anniversary Update 64bit. I have a Intel i7 950 Quadcore prozessor, 16 GB of ram, and the program was running on a SSD.

**Comment by Firebottle** [comment]
Try running the app as administrator.

Having the login button simply not do anything means that the javascript isn't working for whatever reason. I haven't had any other reports of this yet and I'm not entirely sure how I can go about reproducing it considering I'm on the same OS. 

But I'll look into it.

**Comment by Firebottle** [comment]
@traincrafter try downloading the newest release.. I made a few changes that might help.

https://github.com/Firebottle/Firebot/releases/tag/v3.0.0

**Comment by traincrafter** [comment]
now it works thank you :D
