### ISSUE TITLE
Emoji in button ID field causes failed connection with no warning.

### ISSUE THREAD

**Issue by Iampanzer** [Firebottle/Firebot#115]
I upgraded from beta 1 to beta 2 and now i cant connect when ever i click to connect . Even if i press ctrl+alt f12. I have no idea why :(

**Comment by Firebottle** [comment]
I'm looking into it. I got three other people reporting the same thing at the exact same time. I have a feeling it might not be related to the bot itself. I'm testing on my end to see if I can try make it happen as well, but so far it seems to be connecting fine.

**Comment by Iampanzer** [comment]
It was working fine yesterday then.. nope, just wouldnt connect

**Comment by Firebottle** [comment]
Any success today?

**Comment by ThePerry-2015** [comment]
Mine works just fine, I got some errors a couple of times where it connected, but disconnected again after 1-3 seconds. Started the app via command line so I could see what it put in the console, and it showed me that it failed authenticating the streamer account, so I just re-authenticated and it worked just fine afterwards.

**Comment by Iampanzer** [comment]
Hey guys, mine doesnt do anything, when i click the connect button nothing, ive tried many times logged in and out of both stream account and bot. Sux man i just finished my board when it stopped working yesterday lol Ctrl + Alt + F12 wont connect either kind of feels like my button is broken, like it doesnt change color when trying to connect or anything 
![firebot_wontconnect](https://cloud.githubusercontent.com/assets/28286188/26530001/fabb2f42-440f-11e7-8a4f-ad036e044e36.jpg)

**Comment by ThePerry-2015** [comment]
Have you tried running it from the command line to see if it outputs anything to the terminal when you try clicking on the button?

**Comment by Firebottle** [comment]
@Iampanzer I understand. I'm not able to make the problem happen on my end, but I'm going to release an update in a bit that might help.

It'll add in a few more error messages and it'll load all JS locally instead of going to a CDN.

**Comment by Firebottle** [comment]
@Iampanzer can you try downloading v3 and giving it a go? It has some changes and error handling that might help out.

https://github.com/Firebottle/Firebot/releases/tag/v3.0.0

**Comment by Iampanzer** [comment]
ty ill try anything, @ThePerry-2015 sorry i dont know how to do that. but @Firebottle the new app came up with 

Error
Authentication failed.

**Comment by Iampanzer** [comment]
Ok so i reauthed both streamer and bot now i just get 
Error
Close

**Comment by pnkllr** [comment]
Same issue as @Iampanzer im afraid

**Comment by pnkllr** [comment]
Just tried logging into another account and it worked fine. So there is someone on my mixer account that isn't allowing it to connect.

**Comment by pnkllr** [comment]
Ok so.. i had to delete my current board from studio and make a new one, it then allowed me to connect it.

**Comment by ThePerry-2015** [comment]
@Iampanzer If you open the folder where you unpacked Firebot, hold Shift while right clicking on an empty space below the files, you should get an option to "Open PowerShell window here" or "Open Command Line here". Then write .\Firebot.exe in the window that opens and push enter. This will launch Firebot and you will be able to see some output in the window where you started firebot from. This might reveal some more information about which account that failed the authentication and/or more depending on what causes the error.

**Comment by pnkllr** [comment]
My issue i found out when I did more testing was using certain text in the name of the button (not the text) for example i had some Emojis as the name which caused mine to throw the error.

**Comment by Iampanzer** [comment]
Ba boom Pnkllr has found the issue! <3

**Comment by Firebottle** [comment]
Thanks so much guys! @pnkllr @Iampanzer the button name can't contain emoji, however the button text can. Viewers never see the button name, that's entirely for your reference.

I'll look into a way of warning users when they try to do this, so marking this as a bug..

**Comment by Iampanzer** [comment]
No thank you @Firebottle youre doing awesome work <3

**Comment by Firebottle** [comment]
This emoji check will be in the next release. It will pop up a warning that asks the user to remove emoji from the button name field. It also lets the user know that the button name field is different from the button text field.

**Comment by Firebottle** [comment]
released as part of v3.3.0
