### ISSUE TITLE
Cooldown Groups - Edit causes duplicate to be made instead of updating existing group

### ISSUE THREAD

**Issue by Saiasanc** [Firebottle/Firebot#117]
When you click the edit icon for a cooldown group and make changes to the group name, instead of updating that group it creates a new group with all the same settings under the different name.  Maybe this was intended to make similar groups easier to make? I don't know. But to me it is a bug.

Here is a GIF I made demonstrating the issue(?):
https://i.gyazo.com/1b23c9252b15bbaefeff3963d5113419.gif

Edit should only make changes to the existing group. If you want to duplicate an existing group, maybe add a button called "Duplicate" or "Copy" or something that opens the window with all the same settings and THEN makes a new group when you click Save Changes.

**Comment by Firebottle** [comment]
Hello! Yep, editing the name of a group will create a new group and leave the other one in place. It's actually done on purpose for copying groups when needed. So I'll put this down as a feature request.

**Comment by Saiasanc** [comment]
Thanks, @Firebottle! You rock, Sir! Keep up the good work!

**Comment by ebiggz** [comment]
This no longer happens in v4.0. Editing the name only changes the name, it does not duplicate.

**Comment by Firebottle** [comment]
Release 4.0.0-beta.1
