### ISSUE TITLE
Change Group effect does not work.

### ISSUE THREAD

**Issue by DakotaBlake** [Firebottle/Firebot#118]
After adding a Custom Group, then assigning a button to change to this group, it does not work.

**Comment by Firebottle** [comment]
The change group button will only change the group of the person who clicked it. Is that what you tested?

**Comment by DakotaBlake** [comment]
Yes, that is what I tested. I can put myself (or my bot account for testing) into that group manually via the interface, but using a Change Group effect on a button does not do this; the log shows the button was pressed, but it does not actually do anything.

**Comment by Firebottle** [comment]
Okay, I'll look into it!

**Comment by Saiasanc** [comment]
Not sure if it helps or not. But if you click the button for changing groups in the Firebot GUI (not on stream page), the following error(?) message pops up:
https://i.gyazo.com/dc81030e754fec2af02b0b56a94e61d8.png

**Comment by Firebottle** [comment]
Yep, helps a ton. That means it's most likely a simple typo that should be easy to fix.

**Comment by Firebottle** [comment]
Tested changing groups today and it seems to work for me. The issue @Saiasanc reports will only happen when manually triggering the button (because group changes dont work with manually triggering).

@DakotaBlake make sure you're trying to change people to a group that exists already and has a default scene set. Otherwise it will fail to move people because the group doesnt exist.

Will be adding some more error handling to report back on cases like that.

**Comment by DakotaBlake** [comment]
The group already exists and has a default scene set. This is what I tried first, as it was the default instructions. It does not work. At all.

**Comment by Firebottle** [comment]
@DakotaBlake Try the newest upload that is in place now. It tries to address problems with changing groups and it might fix it.

**Comment by Firebottle** [comment]
@DakotaBlake please let me know if you're having issues with the new beta 2.

**Comment by DakotaBlake** [comment]
It works great now, but with more than more than 2 scenes, the bot does not connect at all.

**Comment by Firebottle** [comment]
@DakotaBlake if you download the newest version and still have that problem can you open a new issue for me? I'm connecting with two scenes right now on the newest version.
