### ISSUE TITLE
Firebot 3.0.0 Supporter - BUg Notice

### ISSUE THREAD

**Issue by TigerPerfect** [Firebottle/Firebot#119]
Do you think you could get the fix done for the issue/bug "no buttons showing up" when create a new scene/group in the build mode - It's kind of the most important feature riding on all your setup here. As of right now 3.0.0 says offers groups and so much more although at is point we can only make one.

**Comment by TigerPerfect** [comment]
Also could you please re add the former feature of "Text Button Type" or are you planning to?

**Comment by Firebottle** [comment]
Please dont open a new issue for something that already exists. Text button type is the same as chat.
