### ISSUE TITLE
Chat effect - Firebot 3.0.0

### ISSUE THREAD

**Issue by TigerPerfect** [Firebottle/Firebot#120]
So I'm guessing this is the new replacement "text type button" if not please correct me. 
I so the chat effect also does not work. Thank you @Firebottle

**Comment by Firebottle** [comment]
Yes, it does. I use it every stream. Make sure you're logged in as the person you're trying to send chat as.

**Comment by TigerPerfect** [comment]
Well excuse me for asking a question as new user out of all the guides and one video you never mentioned that about the text being chat now, just was little confusing from using 2.3 first. Thanks again

**Comment by Firebottle** [comment]
No problem. For future reference, there is a wiki button at the top of this page that'll help answer some questions. Here is a link for the different effect types and what they do.

https://github.com/Firebottle/Firebot/wiki/Effect-Types
