### ISSUE TITLE
Feature Request: Dynamic Global Cooldown

### ISSUE THREAD

**Issue by Kylix-Tyfurious** [Firebottle/Firebot#122]
For example, I have 4 'major' interactions and 8 'minor' interactions.

The minor interactions are very quick, but the major interactions are long. 

When someone triggers a major interaction, I would like the entire board to cool down for maybe 2 minutes, but when someone triggers a minor interaction, the board should only need to cool down for maybe 15-20 seconds.

In my case, I need the entire board to go on cool down because if someone were to also trigger a minor interaction during a major, it would stop the major interaction and ruin it. This is why I can't use cool down groups because then other buttons would still be available to press.

Soundwave Interactive Soundboard has this feature and it's great if you just want to use audio, but I have scene switching interactions in OBS that Firebot helps with. A Dynamic Global Cooldown feature would really benefit me and probably many others.

**Comment by Firebottle** [comment]
Any button can cool down any other button for however long. Check out the "cooldown" effect type. It'll do what you need.
