### ISSUE TITLE
I cant get Interactive 2.0 Scenes to swop for different users

### ISSUE THREAD

**Issue by Iampanzer** [Firebottle/Firebot#123]
So mixer has fixed it so you can add different scenes on the sound boards with buttons. I did this and then filled them in on the bot.  When my mods or my other group  join chat they only see the first default scene. Not sure if im doing something wrong or there is something on the bot/mixer side stopping it from knowing when to swop scenes for which users

**Comment by Firebottle** [comment]
In the board settings you can set which groups will see which scenes as their default. So, if you want moderators to see a "moderator" scene, make sure to set the right settings. Firebot will then automatically group your moderators and show the correct scene.

**Comment by Iampanzer** [comment]
I have done this and it still only shows the first defult scene to everyone? I have a Moderator board, and i even tried to make a group mods and add mods manually.. still cant get it to work? anyone else having this trouble?
