### ISSUE TITLE
Firebot only controls my focused window for game controls

### ISSUE THREAD

**Issue by Thanory** [Firebottle/Firebot#124]
I had setup 2.0 to clip a 20sec on one button and to play that back with other. At that time I was using the OBS hotkeys ctrl+Num0 and ctrl+Num1. 

I know you are working on multi key input. but that may not be my issue directly. 

I setup 3.0. It will type my single hotkeys in notepad just fine. I have even tested function keys outside of game and those work. So I started trying different single keys for OBS. and they all work while OBS is focus. But if I jump to any other window or while in game the hotkeys no longer work for OBS. Tried most function keys, insert, delete, and most spec characters. All the same. 

Anyway, this probably resolves when multi-key function is returned. :)

**Comment by Firebottle** [comment]
We'll see! I'm using the exact same emulator for this as I did in version 2. So, technically it should pick up the keys just like it did before unless something has changed within OBS.

Keep an eye on the multikey thread for more news on that.
