### ISSUE TITLE
Can't connect after deleting scenes or controls from the interactive studio.

### ISSUE THREAD

**Issue by DakotaBlake** [Firebottle/Firebot#125]
The newest version of Firebot (3.1.0-beta) does not connect to the board properly, with Mixer just saying "Waiting for game to be ready". The button does not change to green either. When pressing the "Disconnected" button, the bot turns black with a flickering message "Unhandled error: please check your board settings".

**Comment by Firebottle** [comment]
Try downloading Firebot again and overwriting everything again. If it still does it let me know. The first upload had some issues and I had to pull it.

**Comment by DakotaBlake** [comment]
Now it doesn't connect. The glitch is fixed, but the connect button does nothing.

**Comment by Firebottle** [comment]
No errors? Try making a new board with a single button and try connecting. Have you deleted any scenes from the studio fro the board you're using?

**Comment by DakotaBlake** [comment]
I have not deleted anything.

**Comment by DakotaBlake** [comment]
It is indeed due to "deleted"/leftover controls in the JSON file. Very annoying.

**Comment by Firebottle** [comment]
Okay, I figured. I just finished up beta 3 which will clean up the deleted controls.
