### ISSUE TITLE
chat error as bot

### ISSUE THREAD

**Issue by dicksonia** [Firebottle/Firebot#127]
hi there . i ahve just updated to the new 3.1.0 beta 1  i had no issues last update but this one, when i click connect it connects for 3 sec i can see the board on mixer then and Error shows up saying " There was an error with bot chat or it was disconnected. "  can u plz help . thanks

**Comment by Firebottle** [comment]
Try re-logging into the bot with both streamer and bot accounts. Let me know if there are issues after.

**Comment by Firebottle** [comment]
Also new version released. Give that a download.

**Comment by Firebottle** [comment]
Hello, there have been several updates since v3.1.0 beta 1 some of which try to address connection issues. Please try downloading the latest version and give it a try. If you still run into problems please open a new issue for me.
