### ISSUE TITLE
Login Flow

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#13]
Right now both the streamer and bot login works by grabbing oauth info for whoever is logged in on Beam at the time. This means the login flow is somewhat confusing.

Current:
Login to beam as streamer -> login to app as streamer -> go to beam and log out -> log into beam as bot -> log in to app as bot

Can we fix this by opening the auth window in the app as "incognito" and force a sign in for both?

**Comment by brumoen** [comment]
I think I might have a solution that seems to work for this.
At line 24 in login.js

`partition: 'persist:'+date`
instead of just
`partition: date`
Then I can log out and I have to use my credentials as soon as I click on login again, both for streamer and bot.
