### ISSUE TITLE
Cant get bot to connect

### ISSUE THREAD

**Issue by Iampanzer** [Firebottle/Firebot#134]
![cant log bot in](https://cloud.githubusercontent.com/assets/28286188/26708898/00e49518-4792-11e7-940a-ce6738a4da78.jpg)
Just dl the new version to see if i could connect and i still cant. Any ideas?

**Comment by Iampanzer** [comment]
wait wrong pic
![cant log bot in2](https://cloud.githubusercontent.com/assets/28286188/26708922/47eefc78-4792-11e7-8a79-1a80b9a3addd.jpg)

**Comment by Firebottle** [comment]
Can you give these steps a shot? 
https://github.com/Firebottle/Firebot/wiki/Troubleshooting

**Comment by Iampanzer** [comment]
Thanks man still cant connect for some reason , still says waiting for game to connect . Sorry i dunno wtf ive done

**Comment by Firebottle** [comment]
Go through every scene and button and hit save. Then try again.

**Comment by Firebottle** [comment]
Any luck?

**Comment by Iampanzer** [comment]
Sorry ive been ill with migraines,  I did all you said and then got rid of everything and started again. Some where i could connect. Unsure what it was but i tried all you said and it didnt work. Sorry i couldnt be more help
