### ISSUE TITLE
Dynamic button cooldowns

### ISSUE THREAD

**Issue by JimmyMac3** [Firebottle/Firebot#137]
Here is what I'm trying to do - 

ALL BUTTONS Group (add all 25 button to this group) - Once someone presses any button on the board I don't want anyone to be able to press any other button on the board until that button is finished playing.

Problem with that - Some buttons play a longer sound/animation than others - So the button cooldown may need to be 15 seconds for 1 button and 30 seconds for the next. The only way currently to have all the buttons cool down the same amount as the button that is pressed is to NOT use Cooldown groups and instead add the Cooldown ACTION to each and every button and add all the other buttons. Very Tedious and time consuming.

I think it would be more useful if it worked like this - I create a group named ALLButtons15 and another group named ALLButtons30 both groups have all buttons in it (DUH) and the duration is different for each group (DUH again). Then in the button interface I can attach a group to the button to match the duration of that button. This way the current function of Cooldown Groups would still work too.

**Comment by Firebottle** [comment]
Changed the title. Cooldown groups are working, but you're asking for a new feature which would dynamically change the cooldown amount based on button click.
