### ISSUE TITLE
Dice

### ISSUE THREAD

**Issue by RicardoArturo** [Firebottle/Firebot#139]
Hello! 
I do not speak English. But I hope you understand what I am writing to you.
I would like to know if they can do that in Mixer, users can throw dice.

To be clearer, simulate that one or more dice are thrown.

It is so that the users can play a role-play in mixer.

**Comment by Firebottle** [comment]
Yes! We could definitely add something like this... very good idea.

**Comment by RicardoArturo** [comment]
I'm glad to hear that.
I just knew that Mixer could be programmed.
If you can do it, I can use Mixer for my role-playing :)
There are many people who would like this.

**Comment by RicardoArturo** [comment]
When you finish, will you let me know?

**Comment by Firebottle** [comment]
Sure thing. I usually comment on the thread here with a link to the release once it is added.

**Comment by RicardoArturo** [comment]
By the way, do you know the role-playing?
Those who are on the table

Because there are data of many faces, there are of 4, up to 100 faces, so in the code you must put the option to choose the type of dice, and if you can not then search for something solusion, perhaps putting a button for each die .

I would like that to be sent the result in the chat and not in the screen if possible.


So that the record stays there.

How difficult it is to have to use a translator, not all sentences correctly translate. XD

**Comment by Firebottle** [comment]
I understand! I played role-playing games for many years. I'll set it up so you can combine any combination of dice. :)

**Comment by kateract** [comment]
I had a dice expression parser somewhere around here, I'll see if I can dig it up...

**Comment by kateract** [comment]
Actually there's a package for it: https://www.npmjs.com/package/roll

**Comment by Firebottle** [comment]
@kateract do you want to implement this or should I run with it? Don't want to step on your toes.

**Comment by kateract** [comment]
You can run with it, I just thought I'd help with some resources.  I probably won't be able to look at it for real until after E3 though.

**Comment by GamertagIsAnt** [comment]
Yay I'm glad to See this post exist :) This was a recommendation in the comments of one of my videos so I sent them here, I'm glad to see the community coming together to Achieve new Features for the bot :)

Firebottle Your Awesome TY for your wonderful creation & thank you too Kateract for being an awesome Contributor :)

**Comment by Firebottle** [comment]
Finished development on this and it will be in the next release.

**Comment by RicardoArturo** [comment]
Great!
Thank you very much!!

**Comment by Firebottle** [comment]
Released: https://github.com/Firebottle/Firebot/releases/tag/v3.2.0

If you run into any problems please open a new issue. :)

**Comment by RicardoArturo** [comment]
Help!
Will not let me log in to Fire Bot.exe
I have a Microsoft account associated with Mixxer
Butnot login

**Comment by Firebottle** [comment]
Hello @RicardoArturo go to your account settings on Mixer and set a Mixer password in there. Until we can fix #155 that Mixer login should work.

**Comment by RicardoArturo** [comment]
Password change failed. Try again later.
I get this problem.
I'll try tomorrow.

**Comment by RicardoArturo** [comment]
There is a problem with the code

I want to show the result of each die.

Not the sum of all

Example:
Roll says: lightning_Yata rolled 1,3,9,8,9,2 = 32 in 6d10.

It's the only problem.

Everything else is perfect. :)

**Comment by Firebottle** [comment]
The package we used for this can do that. This will be a feature request to add a toggle that changes the output from sum to individual.

For Devs:
The toggle will change from roll.result to roll.rolled

**Comment by RicardoArturo** [comment]
???
I'm not a programmer.
It cost me a lot to make them appear on my channel

Can you explain it more clearly?

**Comment by Firebottle** [comment]
Sure. It means it is possible to do what you want and we'll get it into the app soon.

**Comment by RicardoArturo** [comment]
When do you update the new dice function?

**Comment by Firebottle** [comment]
It might be a bit. Right now we're focusing on a different part. We will comment here when progress is made.

**Comment by RicardoArturo** [comment]
ok Thank you

I thought you were away for a while.

Why the update stayed in 3.4.0

**Comment by RicardoArturo** [comment]
Sorry for insisting.
But I need that function of Dice
Only show the result of each die separately and then the sum.

My users have waited a lot
And many have left my page, because I have failed to fulfill what I said.
:(

I hope you can change that soon

**Comment by eaaliprantis** [comment]
To be honest,

I wouldn't really promise my viewers anything unless I know that what you are requesting is done. I apologize for the viewers to leave. But you also did lie to them.....

**Comment by Firebottle** [comment]
Are you trying to say that we lied to your viewers because we haven't updated the bot with the features you want? I've never spoken to your viewers, and quite frankly this is the best way to never get what you want.

**Comment by Firebottle** [comment]
We will update the bot with this feature when we have time to do so. Never promise your viewers something in which you have no control over. This

**Comment by RicardoArturo** [comment]
I did not want to make you angry, but it's difficult to use a translator and I'm just looking for words that translate them well.

I can not express myself as I should.

I did not want to make you angry, but it's difficult to use a translator and I'm just looking for words that translate them well.

I can not express myself as I should.

Only in a direct and general way, just imagine that I try to explain my situation so that you understand and so you could decide if you helped me a little.

Take 40 minutes to translate this, looking for the fraces that say what I mean.

**Comment by ebiggz** [comment]
Hey Ricardo,

I know there is a language barrier and that it makes communication hard.
I actually think it was what eaaliprantis said that was mainly upsetting, not what you said.
Regardless, I think what eaaliprantis said may have been misunderstood by us because it was difficult to tell if he's talking to you or us. So lets just put that all aside.

The reason it is taking us longer to get this update out is because we are redoing most of Firebot to make make it look better, run faster, and be easier for us to make improvements like the one you want. While I can't tell you when the big update might be done, I can tell you we are getting really close. I will also make sure that the dice change is also in that big update. 

Thank you for being patient with us. I will make sure to update this thread as soon I know when that update will be coming out.

**Comment by eaaliprantis** [comment]
I was initially talking to Ricardo.  I apologize if I came off badly or
offensively.

**Comment by Firebottle** [comment]
@eaaliprantis you're fine! I just misunderstood and assumed the worst. My apologies.

**Comment by RicardoArturo** [comment]
Thanks for understand

I'll wait what I have to wait for.

I know they do a good job and I appreciate it.

**Comment by ebiggz** [comment]
Hey Ricardo,

I just wanted to let you know that we are getting close to releasing a beta version of the big Firebot update. This update contains the Dice features you wanted. If all goes well, this beta version will be available in the next few days.

**Comment by RicardoArturo** [comment]
thank you very much!!
This funsion will be very used
Because I am the creator of a role forum
Where people create and search games using Mixer

But for this everyone will use this dice function.

:)

Just to make sure everything is okay.

What I want is to show the result of each die thrown.
Example:
2,1,2,4,7,4,10 = 27

At the end the total sum is shown.

I understand they left that to you?

**Comment by ebiggz** [comment]
Yes, I have made sure the new feature will function similar to how you described.

In chat, it will look something like this:
"ebiggz rolled a 7 (4, 3) on 2d6."

**Comment by Firebottle** [comment]
Release 4.0.0-beta.1
