### ISSUE TITLE
Randomization

### ISSUE THREAD

**Issue by Emiiiii** [Firebottle/Firebot#140]
Like the title says, I would be nice if we could have many different images or sounds assigned to a button, and they act like a playlist that firebot can just get one image and one sound and play them randomly.

That would be cool and it would make firebot buttons more dynamic since the experience will be random, and having a button playing different things on every push, would surely make people want to keep pushing buttons if they know it will not play the same content over and over again. 

I can think, it could also work for other buttons like input keys, since it would let us have a button people can push and have fun with since it is unknown what it is going to do.

**Comment by Firebottle** [comment]
Sure, we could implement an effect that does something like this one. Marking it as a feature request.

**Comment by Firebottle** [comment]
I'll be doing some work on this one next. 

Effects that could benefit:
- Sounds
- Images
- Videos

**Comment by ebiggz** [comment]
@Firebottle  I was thinking about tackling this after I got "drag to reorder" effects finished so I have thought about possible implementations of this. Passing along the thoughts I had my in my head in case it sparks ideas: 

I was thinking the easiest and most versatile implementation would be to create a new "Random Effect" effect, and inside of it, it would literally just have a nested "effect list" view where you could add/remove any effect you wanted. 

This would make it so not only any effect could be randomized, but also you could mix effects to be randomized. I could think of viable use cases for pretty much any effect to be randomized. 

A sister feature to this that I thought of while thinking about this, was an "effect group" effect. Basically would work the same way as the randomization effect in that it would just be an effect that you define  a list of effects inside of it. But this one wouldn't randomize anything, instead it would just always play all the effects in the group. The use case would be to use this within the randomization effect. IE if someone wanted random images with paired sound effects, they could create a "random effect" with several "group" effects inside of it, each group effect containing a "show image" and "play sound" pair. Then the random effect would pick one groups and show the image and play the sound.

I am not sure how the ui for the random effect (or group effects effect) would look like. It may look bad having another effect list nested inside itself so perhaps if we went this route and the nesting does look bad, there could just be an "edit effects" button inside those effects that open their own seperate modal where you can better focus on their effects.

**Comment by ebiggz** [comment]
95% of the work for this has been completed. Should be release in v4.6

**Comment by ebiggz** [comment]
Released in v4.6
