### ISSUE TITLE
Request Delay "effect" added to workflow

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#141]
With the new design of 3.0.x is it possible to add a delay option as an effect? I'm using firebot to trigger (show) elements and scenes in obs with a hotkey and was hoping I could program it to wait X seconds and then press the hide element/scene. In my mind the layout would be "game control" then "delay" then "game control". Thoughts?

**Comment by Firebottle** [comment]
It'll require rewriting how the effects are handled right now, but it's not out of the question.

**Comment by awrebels** [comment]
Figured it might be a cool addition. Do the effects process sequentially or immediately? Trying to think of a temporary hack. if I added a sound effect of silence for X seconds would that delay the next effect. I'm assuming not and that they all just happen at once.

**Comment by Firebottle** [comment]
Well, it processes them sequentially but it does it so fast it might as well be at the same time. It also doesn't wait for one to complete before starting the next one, so the sound idea wouldn't work.

Right now with the way it is written I can't think of a way to delay some of the effects.

**Comment by ebiggz** [comment]
I think this is a cool idea. Going to tackle it next.

**Comment by Firebottle** [comment]
https://github.com/Firebottle/Firebot/releases/tag/v3.4.0
