### ISSUE TITLE
Image Sizing

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#143]
Add an extra field to the Image effect to allow people to designate a size. This would then just scale the image up or down with CSS in the overlay.

**Comment by Firebottle** [comment]
@ThePerry-2015 finished this one up. Basically each image has a container that is full screen now. Then I applied the positioning and sizes to the image itself. So multiple images will technically be multiple overlapping full screen divs.

**Comment by ThePerry-2015** [comment]
Nice, I didn't even think about doing it that way.. 👍

**Comment by Firebottle** [comment]
Released: https://github.com/Firebottle/Firebot/releases/tag/v3.2.0
