### ISSUE TITLE
In app Update?

### ISSUE THREAD

**Issue by TokenParents** [Firebottle/Firebot#145]
Is there an easier way to update than to delete and reinstall the app? I hit download and it just reloads the info page. 

Thanks
_Token

**Comment by Firebottle** [comment]
You don't have to delete the app. Just replace the files in the Firebot folder with the ones in the zip you download.

**Comment by TokenParents** [comment]
Awesome! Thanks Firebottle. The app is great, thank you for everything you do for the community.

_Token

**Comment by Firebottle** [comment]
No problem! :) Let me know if you run into any issues at all.
