### ISSUE TITLE
Unable to Remove Users From Custom Group After 1st Page

### ISSUE THREAD

**Issue by mrpaden** [Firebottle/Firebot#148]
I accidentally added someone to my "Channel Regulars" group that I did not want on here. I went to delete them from the list, however after I clicked the X nothing happened. I noticed it did this for all the names around it. I went back to the first page and noticed they were still able to be deleted. 

Odd thing is that if I delete ones from the first page, the ones that fall back to the first page from the second are still unable to be deleted until I save and close out of the window, and then reopen it.

Searching for the name to make it the only result does not allow it to be deleted either.

Seems the only way to delete was to completely delete the database until I had gotten the name to the first page.

I am using 3.1.1 beta. Not sure if this is exclusive to that. Just started using the bot yesterday.

**Comment by Firebottle** [comment]
I think I know why this is happening. I'll look into it and get a fix out.
