### ISSUE TITLE
Cooldown Action Not Visibly Cooling Down Other Buttons and Crashing Board

### ISSUE THREAD

**Issue by Kylix-Tyfurious** [Firebottle/Firebot#150]
@Firebottle 

To keep it simple, I have [button 01] set to cool down for 2 minutes and an action added that makes all other buttons cool down for 30s.

When I hit [button 01] none of the other buttons on the board visibly cool down, but when I click them, nothing happens and then the board suddenly turns off on Mixer. I then have to Disconnect Firebot and Launch it again for the board to come back.

Any idea why these things are happening?

I'm using the latest version of Chrome on Windows 10 in case that info is relevant. And I'm on Firebot release 3.1.1

**Comment by Firebottle** [comment]
Not sure, but I'll look into it and get a fix out.

**Comment by Firebottle** [comment]
Got a fix together for this issue and it will go out in the next release. When I was adjusting cooldown groups I didn't go back and adjust the cooldown effect as well.

**Comment by Kylix-Tyfurious** [comment]
You're amazing @Firebottle! Can't wait for the new release! 😄 Thanks for rolling out these fixes so quickly!

**Comment by Firebottle** [comment]
Released: https://github.com/Firebottle/Firebot/releases/tag/v3.2.0

If you run into any problems please open a new issue. :)
