### ISSUE TITLE
Contributor Section

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#151]
I'd like to add an additional section to the info page to list out contributors with links to their channels or websites. I want Firebot to be a community project which allows all developers to learn interactive 2 and help contribute and I want to make sure everyone gets credit.

Right now contributors are listed on the wiki.

**Comment by ThePerry-2015** [comment]
Something like this? @Firebottle ![2017-06-04_18-43-29](https://cloud.githubusercontent.com/assets/25306770/26763604/be4409e4-4955-11e7-8718-c0f19111f236.png)

**Comment by Firebottle** [comment]
That looks good to me!

**Comment by Firebottle** [comment]
Released https://github.com/Firebottle/Firebot/releases/tag/v3.2.0
