### ISSUE TITLE
3.1.1 Logging in with MS Account - Blank Screen

### ISSUE THREAD

**Issue by wcphart** [Firebottle/Firebot#155]
When logging in with a MS account during setup after upgrading to 3.1.1, when you click on the blue bar "Login with your Microsoft Account" the popup that is opened is a blank white page.

How do I log back in now that I have updated to 3.1.1?

**Comment by Firebottle** [comment]
For now I'd recommend downgrading until we can take a look at the bug.

**Comment by wcphart** [comment]
@Firebottle I was able to log in without the MS account. Apparently you can set a password in Mixers account area, and login with that password OR use MS login. So for now, I can login but would prefer to use MS login eventually.

**Comment by Firebottle** [comment]
Ah okay! I'm sure that eventually the mixer login will go away completely and will 100% use the microsoft login.

**Comment by kateract** [comment]
I have a question in to the electron-oauth2 guy about this.  The windows display properly if I turn on sandboxing, but the window itself doesn't close and return the tokens.  So, most likely a security issue of some sort with Chromium.

**Comment by Firebottle** [comment]
I know I had this working in the interactive v1 branch for old Firebot. Deeky helped fix the issue. It wasn't using oauth2 but it worked the exact same way.

**Comment by Firebottle** [comment]
Release 4.0.0-beta.1
