### ISSUE TITLE
Login button issues

### ISSUE THREAD

**Issue by UnknownTBeast** [Firebottle/Firebot#156]
If you click the connect/disconnect repeatedly really quick, after a few seconds a pop up is shown, but since I was clicking so fast it disappeared and I was left with a gray screen.

**Comment by Firebottle** [comment]
Probably just need to take a pass at the login button in general. I've noticed instances where it won't flip over to the opposite status, or where it'll seem as if it doesn't do anything if your connection is slower. 

Will take a look and try to improve it over all.

**Comment by Firebottle** [comment]
Release 4.0.0-beta.1
