### ISSUE TITLE
Whispering to the bot 

### ISSUE THREAD

**Issue by GamertagIsAnt** [Firebottle/Firebot#158]
Need whispering to the bot account like the 2.2.3 version to clear up some of the spam in chat for like Counters n such or invisible commands you don't want shown publicly :) doing "/whisper @"Botname" !cmd" just generates a solid text line

**Comment by ThePerry-2015** [comment]
This is already in Firebot 3.2.0.

Chose Chat as the button action -> Chose who that should say/whisper the command -> Write the message: "!cmd something" -> Write the name the command should be whispered to in the field below "Who should I whisper this to? Leave blank to broadcast to everyone." and click save changes.

**Comment by GamertagIsAnt** [comment]
Ah I was just having a Personal bug then or something xD Thank you for letting me know its still there Perryman, your awesome!
