### ISSUE TITLE
Cooldown Groups

### ISSUE THREAD

**Issue by GamertagIsAnt** [Firebottle/Firebot#159]
They are not currently working, Not only do they overwrite the space where your cooldown is originally set for individuals back to a blank slate but they are not triggering, The same goes for adding another button to the cooldown function within what the button does

**Comment by ThePerry-2015** [comment]
Cooldown groups do work, but at the moment it seems that you might have to restart Firebot after you have created/edited the cooldown group. Not sure why this is happening. The same goes for editing cooldowns on the buttons individually. As for editing the cooldowns I can't say that I see that the get blanked out, but doing changes to the cooldowns after you have initiated Interactive mode and connected the app you have to restart the app to get it to refresh the cooldown settings both for individual cooldowns and cooldown groups. We might have to take a look at this to figure out why this is happening.

**Comment by Firebottle** [comment]
I'll take a look at this as well. To help speed stuff up when Firebot initially connects to interactive it attaches whatever the current settings are to each button. That way it doesn't have to make a bunch of calls to the json DB to pull in info each time anything is clicked. It seems to help with things like auto clickers on a zero cooldown button.

It could be that after the first connection it's not passing the new settings on to the buttons.

**Comment by Firebottle** [comment]
Found bug where the cooldown group settings were being removed from the button when saving individual button settings. This would be the cause, working on a fix.

**Comment by Firebottle** [comment]
@GamertagIsAnt Can you try out the newest update and see if it helps? You'll need to go into each cooldown group and hit the save button.

https://github.com/Firebottle/Firebot/releases/tag/v3.2.1

**Comment by GamertagIsAnt** [comment]
Yes I can, Just got Up & will download the update :)

**Comment by GamertagIsAnt** [comment]
Fixed, Thank you so much for your hard work guys! :) 👍

**Comment by GamertagIsAnt** [comment]
All it took was a resave in the Cooldown settings/options

**Comment by Firebottle** [comment]
Awesome! Glad that got it fixed.
