### ISSUE TITLE
v3.2.0 Settings not saving to buttons consistently

### ISSUE THREAD

**Issue by Kylix-Tyfurious** [Firebottle/Firebot#161]
I've attached an image for reference, but sometimes when I tell Firebot I want it to press [control] and [F1] then hit save, I'll try it on the Mixer board and nothing will happen. I'll go back to the button settings and see that the [control] modifier is no longer checked. Not sure what's causing this issue, but it's happening across multiple button settings.

![control issue](https://cloud.githubusercontent.com/assets/29049332/26829509/e7d1305e-4a93-11e7-8145-7a75fc2f323f.PNG)

**Comment by ThePerry-2015** [comment]
Is this edited while the board is active or in-between connections? I've experienced that some changes requires me to restart the whole app before the changes are effective through button pushes and some just requires me to disconnect and reconnect it.

**Comment by Kylix-Tyfurious** [comment]
I always make sure I am not connected while editing, but I haven't tried restarting the app with each change.

**Comment by Firebottle** [comment]
Off the top of my head I have no idea why this would happen. As soon as you hit the save button it writes the settings to the controls file. So it sounds like somewhere in the process of connecting to interactive that controls file is getting reverted.

Will look into it.

**Comment by Firebottle** [comment]
Here is what I tested so far. All of these successfully changed and kept the settings. Still looking.

- Edit changes and hit save. 
- Connect, then edit changes and hit save.
- Connect, edit changes and hit save. Disconnect, and then check settings.
- Change settings, switch to different scene, switch back and check settings.
- Change scenes, edit a different button, switch back and check settings.
- Connect, auto click the button on mixer site for a minute, check settings.
- Make changes, restart app, check settings.
- Add button to cooldown group and check settings.
- Remove button from cooldown group and check setting.
- Reselect board to refresh buttons and check settings.

**Comment by ThePerry-2015** [comment]
Same here @Firebottle, the only thing I've encountered so far is that the changes I do isn't always reflecting to the buttons on the site. If I change a cooldown length or a cooldown group the changes doesn't always trigger via the buttons on my stream page until I restart the app. It's almost like it needs a reinitiation of the interface to see the newly saved settings before it mirrors over to the interactive board on the stream page. Kind of messy explanation, but hopefully you are able to decipher it..

**Comment by Firebottle** [comment]
@Kylix-Tyfurious can you attach the controls file for the board you're having issues on? Maybe it's something specific there.

**Comment by Kylix-Tyfurious** [comment]
Certainly @Firebottle where do I find that file and I'll add it. Also, I should note that this issue can be duplicated using a step I left out. At least it was happening to me multiple times.

This is what I was doing exactly for each button:
1. Add effect > Game Control
2. Check control box modifier & set button (F1) 
3. Add effect > Cooldown
4. Add all buttons & set their cooldown time
5. Click save
6. Click connect and press button on Mixer > Nothing happens in OBS
7. Go back to settings and see that control modifier is now unchecked

**Comment by ThePerry-2015** [comment]
Are you testing this on the same computer as you are running the Firebot from?

You can find the control file inside the folder where you have Firebot unpacked:
user-settings\controls\name-of-your-board.json

**Comment by Kylix-Tyfurious** [comment]
Yes @ThePerry-2015 it's all on the same PC for me. 

I uploaded the file for Firebottle on another issue thread, but I'll drop it here again just in case.

https://drive.google.com/open?id=0B8Yo0Os_yTMsSVppX21kM3VpVWs

3.2.2 is retaining the button settings now, it seems, but I can't get the buttons on the site to respond at all for some reason so we're trying to work that out at the moment.

**Comment by Firebottle** [comment]
Kylix mentioned that this is now fixed for him as of the newest release.
