### ISSUE TITLE
Auto group not working?

### ISSUE THREAD

**Issue by ReAnimateHer** [Firebottle/Firebot#163]
I am new to firebot, so I may be missing something. But my issues it this I set up several scenes on 1 board but I can only get the default board to show when I connect the board to my stream. No matter what I do only the default scene shows up. Is there something I am missing? Should I delete it all and start a new? Thank you for your help.

**Comment by Firebottle** [comment]
If you haven't already I recommend watching the getting started video tutorial. https://github.com/Firebottle/Firebot/wiki/Getting-Started

Without changing any settings everyone is going to see the default board. Look at the settings tab of your current board to see where you pick which groups see which boards by default.

**Comment by ReAnimateHer** [comment]
Hi I did that already hence why I am here asking the question. I also had other people who use Firebot try to help while on stream showing them exactly what I needed.

**Comment by ReAnimateHer** [comment]
Thanks I will see what else I can use since I can not get this to work.

**Comment by Firebottle** [comment]
Thanks for the additional information. Please take a screenshot of your board settings page and attach it here so we can see what you're seeing.

**Comment by Firebottle** [comment]
Going to go ahead and close this as I havent heard anything in two days. If you run into any problems just open another issue.
