### ISSUE TITLE
HTML Output and Dice Effect don't work on manual activation in UI

### ISSUE THREAD

**Issue by TheClassicalGod** [Firebottle/Firebot#164]
I was super happy to see the HTML Output added as a button effect. Opens up doors to more elaborate things to display.  I immediately slapped together a quick html video player to see if I could use MP4 files rather than GIFs since they would look smoother and have audio along with them. I tested the output in Chrome and Edge to make sure it worked before I took things any farther and all seems fine there, so I threw it into Firebot on a button and nothing seems to display at all. Not visually or audibly.

I thought maybe the browser plugin in OBS didn't support HTML5 video players, but I ran my own HTML file through the plugin and everything worked as intended. I also ran the firebot overlay HTML file direct from a browser and does not seem to work there either, but using other output types do work.

Not sure if I jumped the gun trying to use it before I was supposed to and this was supposed to be a future function or maybe i'm doing something wrong? I know it's a new feature and it may not even be intended for what I was trying to do.

Just to give an idea of what I was doing, I pasted code below.

```
<!DOCTYPE html>
<html>
<style>
	.player {
		position:absolute;
		bottom:0;
		right:0;
		margin: 50px;
	}
</style>
<body>
	<video class="player" width="400" autoplay>
		<source src="E:\Videos\FirebotClips\Not.Physically.Possible.mp4" type="video/mp4">
	</video>
</body> 
</html>
```

**Comment by Firebottle** [comment]
Try the code below instead. Then you'll want to tell Firebot to remove "custom-video-wrap" after X amount of time.

```
<div class="custom-video-wrap">
        <video class="player" width="400" autoplay>
		<source src="E:\Videos\FirebotClips\Not.Physically.Possible.mp4" type="video/mp4">
	</video>
<style>
	.player {
		position:absolute;
		bottom:0;
		right:0;
		margin: 50px;
	}
</style>
</div>
```

**Comment by Firebottle** [comment]
Basically all it's doing is taking a single div with whatever is inside of there and outputting it to an HTML page. So if you include doctype and such again it will probably mess up the overlay.

**Comment by ThePerry-2015** [comment]
You might want to use the HTML way of including the movie as well:
file:///E:/Videos/FirebotClips/Not.Physically.Possible.mp4

And easy way to do this is to open the given file/video in Chrome by dragging the file over to Chrome and then copy the URL from Chrome into the <source>-tag.
Using direct "Windows" filepaths is a BAD practice in HTML.

**Comment by Firebottle** [comment]
@ThePerry-2015 ah good point. Corrected the code snippet to include that.

**Comment by TheClassicalGod** [comment]
I was actually thinking it would need the extra div tag and drop the others since it was likely already declared in the main page, but I didn't dive into how it was implemented, so I figured better to try anyway. With the exception of adding the new div class, I tried every full and partial way of coding it out I could think of.

I knew using direct windows paths was bad practice, but I figured since it was local and I had no intention of porting it to anything else, it would be fine. Either way, I changed it for the sake of being as proper as possible in hopes my own error was the issue. lol

Unfortunately still nothing displaying after adding the new div tag and using the file path. I dropped the CSS to see if that was causing issue. Still nothing. I even just tried to swap to displaying an image instead of a video just to see what would happen. Absolutely nothing. =\ Maybe I need to scrap my install directory and start Firebot fresh. Not sure what I could have messed up along the way, but maybe I did.

**Comment by Firebottle** [comment]
It sounds like the websocket connection to the overlay is being blocked, but you said you tried out all of the other effects and "show image" works the same way as the HTML button. So if that's showing the HTML one should technically work. You also mentioned it works fine in chrome.

I'll have to download OBS and test it out. Not sure what would cause only that one effect not to work.

**Comment by ThePerry-2015** [comment]
I tested this with the exact code I wrote in my above response with the latest OBS FTL of March and it worked just fine. I even managed to scared myself since I forgot I had my speakers turned on.. xD

**Comment by TheClassicalGod** [comment]
@ThePerry-2015 It shows Image Outputs in Chrome, Edge, and Firefox, but the HTML Output doesn't seem to work there either. Maybe I need to throw it through Handbrake and covert it to MP4 with different codecs.. Not sure, but I definitely tried an image and even just text and nothing displays with that HTML output for me. =\

**Comment by ThePerry-2015** [comment]
Do you mind adding your controls file to this thread so we can take a peek at it?

**Comment by TheClassicalGod** [comment]
It wouldn't let me attach the json directly, so I had to zip it. Ignore some of the, uh... questionable buttons. lol I run an odd stream with even odder(if that's possible) audience.. lol Clearly, I also need to clean up my folder structure. Been just slapping things in random folders since I was on Twitch forever ago. lol

[SFX.zip](https://github.com/Firebottle/Firebot/files/1055921/SFX.zip)

**Comment by ThePerry-2015** [comment]
That file works just fine at my end. Now I don't have you board so I can't test everything in the file, I just used the video part and swapped it out with my own local video file to see and it worked just fine. I also swapped the video with an online test mp4 just to test as well and it worked just fine.

```
<div class="custom-player-wrap">
<video class="player" width="400" autoplay>
		<source src="http://techslides.com/demos/sample-videos/small.mp4" type="video/mp4">
	</video>
<style>
	  .player {
		  position:absolute;
		  bottom:0;
		  right:0;
		  margin: 50px;
	  }
</style>
</div>
```

**Comment by ThePerry-2015** [comment]
Oh, Do you use the buttons on your stream page or the assigned interactive button inside Firebot itself?
I just tried triggering the overlay with the assigned button within Firebot and that failed.. When I use it via my stream page, which I've done the whole time, until I took a shortcut, it works flawless.

**Comment by TheClassicalGod** [comment]
I was trying it from firebot itself. I'll try from the stream page and see if that makes a difference.

**Comment by ThePerry-2015** [comment]
Well I believe it should work from the Interactive App it self as well as all other buttons does, but there might be some bells and whistles missing as it's a brand new function.. ;) Glad I accidentally took a shortcut there then..

**Comment by Firebottle** [comment]
Ahhhhh that makes sense.

So, in the controls router file there are actually two different routers depending on if it's a live button press or a manual activation. I had to do this because some things shouldn't trigger during manual activation like button presses.

I completely forgot to add the new HTML and Dice button to the manual activation list. I'll get those in there and it'll be included in the next release.

**Comment by ThePerry-2015** [comment]
Might want to add Change Scenes to that list as well. ;) It seems that those buttons doesn't trigger via the interface either.

**Comment by TheClassicalGod** [comment]
At least something came out of this. lol

**Comment by Firebottle** [comment]
@TheClassicalGod thanks so much for helping us narrow it down. :)

@ThePerry-2015 yeah change scene and change group dont work with manual presses right now. Not sure how to handle those since they need the participant object that comes through when a live button is pressed.

**Comment by Firebottle** [comment]
Should be in release https://github.com/Firebottle/Firebot/releases/tag/v3.2.3
