### ISSUE TITLE
Running FireBot for first time - log-in

### ISSUE THREAD

**Issue by MrCrankyCanuck** [Firebottle/Firebot#165]
Decided to give FireBot a try and I am not able to even log in for the first time with either the Streamer or Bot account
![firebot-error](https://user-images.githubusercontent.com/22506307/26843200-69760cfa-4abd-11e7-8296-26323ced2c99.png)

not sure what I am doing wrong here :)

**Comment by MrCrankyCanuck** [comment]
oh and this is with the newest FireBot dist

**Comment by ThePerry-2015** [comment]
Are you using Microsoft login by a change? If so this is related to #155 .

**Comment by MrCrankyCanuck** [comment]
no I am using my Mixer login info

**Comment by Firebottle** [comment]
@MrCrankyCanuck That was my fault. A bad build was uploaded. Please redownload the newest version again and you should be good.

**Comment by ThePerry-2015** [comment]
That's what happens when I check new updates the lazy way.. xD I just copied the update over my previously authorized bot and it worked just fine.

**Comment by Firebottle** [comment]
(That's what I did also)

**Comment by MrCrankyCanuck** [comment]
thank you .. that did the trick
