### ISSUE TITLE
Long Button IDs cause UI Issues

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#166]
When a user has a really long button ID name the board UI goes all crazy.

![image](https://user-images.githubusercontent.com/17416635/26847717-a7e02b78-4ac3-11e7-9bd7-1661ec24067d.png)

**Comment by Kylix-Tyfurious** [comment]
I'm using Zalgo text for the '2 Spooky' button by the way, so that one is suppose to look weird, but the others like 'Raise Your Dongers' aren't... (That's just a placeholder name for that button by the way, lol!)



2͖̺̤̭̔̓ͣ͊̅ͥ̽ ̛̥͎͋ͣͭ͒ͩͬ͒S̮͖̻̒̐ͅP̻̀̐̔͆ͦ͘Ȯ͔̹̳̭̪̞͔ͣ̐O̺̫̫͂̕K̘̯͕̰͎ͫ͆̂ͅY͋ͦ͛̚

**Comment by Firebottle** [comment]
Released 3.3.0
