### ISSUE TITLE
Missing image sizes seems to "blow them up" a bit.

### ISSUE THREAD

**Issue by ThePerry-2015** [Firebottle/Firebot#168]
It seems that untouched size settings after the image size settings was added into Firebot causes images to be enormous in the overlay. Might have to add some checks there to be sure they don't exceed 100% unless that's intentionally added by the user.

**Comment by Firebottle** [comment]
Thanks for working on this @ThePerry-2015 I made just a few small tweaks to try to fix having to do the math to scale thing proportionally. Will get it into the next build.

**Comment by FluffyMatt** [comment]
Could use `naturalWidth` and `naturalHeight` if no `Height` or `Width` is specified?

This will give you the base `Height` and `Width` of the image that you could use instead.
