### ISSUE TITLE
Button Menu Field Validation

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#17]
The validation for the button menu fires at a weird time after saving. It fires after the fields clear, but before the menu closes. This causes the user to see a flash of red on everything for a second.

**Comment by brumoen** [comment]
Another thing on this note is that if you go in to edit an already assigned button it won't load the keys already bound to that button, all other settings are read, but not the keybinding itself.

**Comment by Firebottle** [comment]
Yeah, right now it does not grab button specific info, only the general info at the top. I'll have to add in the ability for the button specific stuff to load.

**Comment by Firebottle** [comment]
Fixed the main issue here by fading the menu out while clearing the fields. Looks okay, but there are better ways to do it. For now it will work.
