### ISSUE TITLE
Alt button becoming unchecked

### ISSUE THREAD

**Issue by TokenParents** [Firebottle/Firebot#172]
after running game controls for a bit some scenes uncheck the alt button in game controls. 

_token

**Comment by Firebottle** [comment]
How long does it take for this to happen? Are you able to force it to happen somehow?

**Comment by TokenParents** [comment]
Seems like maybe after 5-10 game commands using Alt as a modifier. Should I list the game controls I use? 

_token

**Comment by ebiggz** [comment]
Yeah, that would be great. Any info is super helpful when trying to reproduce issues.

**Comment by TokenParents** [comment]
Alt + J
Alt + N
Alt + O
Alt + '
Alt +[
Alt +]
Alt +numpad_6
Alt +numpad_5
Alt + F10
Alt +

**Comment by Firebottle** [comment]
Does the alt modifier get turned off for all of these buttons or is it just a few of them you see the issue on?

**Comment by TokenParents** [comment]
Seems like just a few of them but seems like just the ones that get pressed the most

**Comment by SpontaneousJ** [comment]
I have seen the same for the Ctrl modifier.  Seems the game control is hit/miss every time I test.  One time it will run the three different game controls then the next time only two, then only 1, then all, then none.  Seems to be random.

**Comment by awrebels** [comment]
I've ran into this issue as well albeit slightly modified. As an example I have a button that executes a game control (ctrl+alt+shift+1) then delays for X seconds then executes game control (ctrl+shift+1) and I notice during save the modifiers will change either to match the last (no alt) or the first (with alt). And this is without hitting the interactive button.  Other buttons which change the number work fine and don't change.

**Comment by Firebottle** [comment]
This should be corrected as part of the 4.0 release.

**Comment by Firebottle** [comment]
Release 4.0.0-beta.1
