### ISSUE TITLE
Video HTML output

### ISSUE THREAD

**Issue by MrCrankyCanuck** [Firebottle/Firebot#174]
Okie dokie :) I have been scratching my head over why this isn't working when I know it should according to the code and local display of the firebot.html but regardless of what I try it will not display in OBS or even live.

The code in the button (HTML selected) is:
```
<div class="good-morning">
<video class="player" width="400" autoplay >
<source  src="file:///D:/Software/Firebot-win32-x64/overlay/morning.mp4" type="video/mp4" >
</video>
<style>
	  .player {
		  position:absolute;
		  bottom:0;
		  right:0;
		  margin: 50px;
	  }
</style>
</div>
```

which is basically an exact copy of a previous post here ( [https://github.com/Firebottle/Firebot/issues/164](url) ) which apparently worked(??)

Any help would be appreciated

Firebot ver: v3.2.3
OBS-FTL: 18.0.1-ftl.0.9.4 - 64bit Windows
Windows 10 (with Creator Update)

**Comment by ThePerry-2015** [comment]
Is that the entire content of the HTML field? If so there is no video there. That's only a style with not contents other than a margin of 50 pixels.

**Comment by MrCrankyCanuck** [comment]
sorry not use to markup .. had to edit a fix :)

**Comment by ThePerry-2015** [comment]
If you have problems putting code in your posts, use ` ``` ` in front and behind.. ;)

**Comment by MrCrankyCanuck** [comment]
yup figured that out - thanks :) .. I might be old and slow but I do catch on lol

**Comment by ThePerry-2015** [comment]
It seems that you are missing a div at the start there, but it should be working without it.
Can you zip your user-settings\controls\board-name.json and attach it to the thread? I just tested with your exact code in my overlay and it worked just fine both in Chrome and OBS FTL, but it never goes away since it's missing the CSS Class setting.

**Comment by MrCrankyCanuck** [comment]
I can do that in a sec .. curiosity got the best of me and had a look at the json (Visual Studio Code IDE) and this is the html line from the button:
`
"html": "<div class=\"good-morning\">\n<video class=\"player\" width=\"400\" autoplay >\n<source  src=\"file:///D:/Software/Firebot-win32-x64/overlay/morning.mp4\" type=\"video/mp4\" >\n</video>\n<style>\n\t  .player {\n\t\t  position:absolute;\n\t\t  bottom:0;\n\t\t  right:0;\n\t\t  margin: 50px;\n\t  }\n</style>\n</div>",
`
somehow that doesn't look quite right??

[Morning V2.zip](https://github.com/Firebottle/Firebot/files/1059291/Morning.V2.zip)

**Comment by Firebottle** [comment]
Just FYI, the html in the JSON will look weird. It has to escape a bunch of characters and such to get it into the JSON. That is why there are slashes and such. When it goes to render it on the front end all of that would be removed.

**Comment by ThePerry-2015** [comment]
The code it self seems to work just fine on my end, I had to swap the video for another, but it plays just fine.
Have you tried opening the video directly in Chrome or any other browser? just drag and drop to see if it's able to play it. Another option is to add a thick red border in the div style so it's visible regardless of the video works or not just to try to see where the issue is.

```
<div class="good-morning">
<video class="player" width="400" autoplay >
<source  src="http://techslides.com/demos/sample-videos/small.mp4" type="video/mp4" >
</video>
<style>
	  .player {
		  position:absolute;
		  bottom:0;
		  right:0;
		  margin: 50px;
		  border: 5px solid red;
	  }
</style>
</div>
```

This block should show you a video with some Lego pieces, some voices plus a 5px border around the video.

**Comment by MrCrankyCanuck** [comment]
alrighty - first no video or audio in OBS but the red border shows .. oh and there is no 'Lego' pieces in that block.
I also loaded up firebot.html in Chrome and it displays just fine with audio so I am not sure what could be wrong as I had this displaying fine when I had it called from my bot (node.js & js)

Screen cap of where the video would be playing in OBS
![firebot-video](https://user-images.githubusercontent.com/22506307/26902149-305d0f9c-4ba6-11e7-8f98-06ee639b7752.png)

**Comment by ThePerry-2015** [comment]
That's really weird. Here is the same on my end showing both OBS and Chrome.
![2017-06-07_23-28-30](https://user-images.githubusercontent.com/25306770/26902419-8c8b70be-4bd9-11e7-9063-afa5be6aab97.png)
I'm really not sure what's causing this, I'm also on Creators update of Windows as well as the latest OBS FTL version. I'm currently on Firebot 3.3.0, but I doubt that's the reason for it not showing in OBS.

Just out of curiosity, OBS setting for the overlay? Local file box checked or not?

**Comment by MrCrankyCanuck** [comment]
Local file Checked
![obs](https://user-images.githubusercontent.com/22506307/26902890-edd7a742-4ba8-11e7-9413-e35a887d6c89.png)

**Comment by ThePerry-2015** [comment]
I just tested with using local file myself and that works just that same as if I'm not using local file.
I'm out of ideas at the moment, but hopefully someone else has a suggestion or can point you in the right direction here as I don't understand why it's not working.

**Comment by MrCrankyCanuck** [comment]
ya I am  at a complete loss here ... it doesn't make any sense

**Comment by ebiggz** [comment]
Hmm. Maybe this was already covered and I am missing it, but in your settings tab for Firebot what do have set for "Overlay Compatibility"?

**Comment by MrCrankyCanuck** [comment]
OBS and I tried both robotjs and KBMRobot

**Comment by MrCrankyCanuck** [comment]
just to update this has been "solved" is was a matter of having OBS Browser source file path be the 'url' rather than the direct desktop path

![obs-path](https://user-images.githubusercontent.com/22506307/26909474-211e61a6-4bcf-11e7-8f42-a2ea2f75a9cd.png)

thanks everyone for the help

**Comment by ebiggz** [comment]
Glad you got it resolved!
