### ISSUE TITLE
Support Chat Command Creation

### ISSUE THREAD

**Issue by ebiggz** [Firebottle/Firebot#177]
I know there are already a lot of solutions out there for creating chat commands with bots, but I don't think it would hurt to add this feature into Firebot as well just to further cement it as an all-in-one streamer tool for Mixer. 

It looks like we already have all the setup required to do this and even have an example "!ping" command in code that doesn't do anything at the moment. So this would be rather quick, easy win and not out of scope.

**Comment by Firebottle** [comment]
Released 4.4.0
