### ISSUE TITLE
Button Selector Dropdown is a pain...

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#179]
Like... it'll actually cause you pain. An example of this type of dropdown is in the "cooldown effect" in which you need to select which buttons need to cool down from a dropdown.

The problem is that if you have a lot of buttons the dropdown will actually be off the page. You'll need to scroll down for each button and click it.

Instead of a dropdown this should be a list you can scroll through and just click a checkmark next to each button.

**Comment by ThePerry-2015** [comment]
Isn't there a way to remove them from the list when they have been added to the cooldown list somehow?

**Comment by ThePerry-2015** [comment]
Nope, forget that, that might mess it up on the next button where you want to add the same buttons.. Forget that, keep on.. :)

**Comment by ebiggz** [comment]
What if you want to add multiple of one type of effect? Like, game control + delay + game control

**Comment by ebiggz** [comment]
We could make a searchable dropdown if we wanted. There’s some pretty customizable jquery plugins that enable that. We would have to switch drop a bootstrap “dropdown” to a select element is all.

**Comment by Firebottle** [comment]
https://github.com/Firebottle/Firebot/pull/181

If you guys want to review. I just changed the button dropdowns to a scrollable list of checkboxes. I checked cooldown groups and buttons with multiple different cooldown effects. Works so far.

We could always improve it by adding search to it later. The functionality for that is already in place on the moderation tab.

**Comment by Firebottle** [comment]
https://github.com/Firebottle/Firebot/releases/tag/v3.4.0
