### ISSUE TITLE
Individual cooldown not working

### ISSUE THREAD

**Issue by DammitRooster** [Firebottle/Firebot#185]
Hey there Firebottle :) So the soundboard was working fine today (6/12) and then out of nowhere viewers started spamming my sounds. For whatever reason the cooldowns I have set just stopped working. I double checked and all the cooldowns I put in place are still there. What do?

**Comment by ThePerry-2015** [comment]
Did you try to restart Firebot or just reconnect it too see if that solved the issue?
Not sure what would break the cooldowns in Firebot unless the Interactive system had some sort of hiccup that made it so that Firebot wasn't able to send the cooldowns over to the interactive board.

**Comment by DammitRooster** [comment]
I’ve restarted many times and the result is the same. Today only a few cooldowns were working. It’s weird. Any and all help would be appreciated. I’ll downgrade for now and see what happens. 

Sent from Mail for Windows 10

**Comment by ThePerry-2015** [comment]
Hmm, that's strange. Have you gone through the buttons and resaved them just to see if that helps?

Can you zip your user-settings\controls\board-name.json and attach it to the thread? As well as add me as an allowed user of the board in Mixer Interactive Studio? That way I can test and see the whole setup in my own channel to see how it behaves.
Mixer name = ThePerry

I won't be able to check it out before in the morning(6ish hours), unless someone else takes a look before I get back online. If not I'll check it out in the morning.

**Comment by DammitRooster** [comment]
I’m not totally clear on how to add you as an allowed user though

Sent from Mail for Windows 10

**Comment by Firebottle** [comment]
Just to check. What version are you on? This was a problem a few versions ago.

**Comment by Firebottle** [comment]
To share your interactive board go to the studio and click the share icon in the to right. Then enter a username.

**Comment by DammitRooster** [comment]
I’m on  v3.4.0

I’ve added ThePerry & Firebottle in the share settings

Thanks for your help 😊

Sent from Mail for Windows 10

**Comment by ThePerry-2015** [comment]
Can you attach the file I asked about last night as well? If not we won't be able to see how you have set up your board in Firebot.. ;) 

Should be a user-settings directory in the directory where you have unpacked Firebot, inside that one again there should be a controls directory in there it should be a file named the same as your board is at Mixer Studio. Zip that json file and attach it to a comment here. :)

**Comment by DammitRooster** [comment]
Here ya go 😊

Sent from Mail for Windows 10

**Comment by ThePerry-2015** [comment]
I'm not sure that sending the files via mail gets it attached to the thread. I can't see any attached files to any of your messages.

**Comment by DammitRooster** [comment]
Hmmm can I DM them to you on Discord ?

-- Rooster

**Comment by ThePerry-2015** [comment]
Sure, I'm on Firebotopolis and the Mixer discord, in the community-developer group. So should be pretty easy to find me. ;)

**Comment by ThePerry-2015** [comment]
So it seems that something have changed somewhere after 3.4.0. The latest Cooldown checker is having problems triggering cooldowns on buttons that has lower cooldowns than the longest one active on the board. So if you trigger a short one, then you can trigger a longer one and so on. But it won't trigger a shorter one than the longest one currently cooling down.
Tagging this as a bug, we have to look into this one to figure out what's causing this.

**Comment by wcphart** [comment]
Came here looking for this. Can confirm I too am having this issue in 3.4.0, of course the darn kids find it immediately and start spamming buttons.

**Comment by wcphart** [comment]
@Firebottle Is there a way to still use the board, until this is out? Like would global CD group avoid it or anything?

**Comment by Firebottle** [comment]
The last version should work. Otherwise wait until a new build later today.

**Comment by wcphart** [comment]
@Firebottle oh!! Don't tease now! Happy Friday maybe!!

**Comment by Firebottle** [comment]
Build is together for this one. Waiting on testers but should hopefully go out tonight.

**Comment by DammitRooster** [comment]
Sweet. I'm off for a few days so I'll check it out when I'm back. Thanks for all your help dude 😎

-- Rooster

**Comment by Firebottle** [comment]
https://github.com/Firebottle/Firebot/releases/tag/v3.4.1

Update released to address the issue. Will close this thread. Just open up another if you continue to have issues when you get back.
