### ISSUE TITLE
Show Images width limitation?

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#186]
Assuming each location is a "cell": Are the show images limited to the max width of each cell you are able to select?  In other words if we have the browser source overlay (OBS) set to fill the full size of the scene and select show image as middle AND set the same pixel width/height of the scene does it only fill the cell or the entire screen?

What I am seeing is if i select middle and make the width/height the same as the scene it still only shows up in the width of 1 of the 9 cells.

**Comment by ThePerry-2015** [comment]
This is how I just tested this(Firebot version 3.4.0) to be able to give you a decent answer.

1. Made sure the firebot overlay cover the entire scene in OBS (1920x1080 setup)
2. Set image to be 1080x1920 in Firebot, as the height and width fields got written "backwards" for some reason. Might blame me for that, most likely added them alphabetically.
3. Assign it to the middle location
4. Trigger button and saw the image cover the entire OBS overlay.

I tried shifting it around on the different locations and it still shows over almost the whole overlay.
The corner locations have a 10px "edge-padding" to make some room between the edge and the div, if you don't want this spacing you can edit the overlay CSS to suit your wishes, just remember to make a copy of the file between updates so you don't loose them when you update Firebot.


This shouldn't make it behave differently, but I'm just putting it in here to have it covered. :)

How have you setup your overlay in OBS? Via "Local File" or using an URL copied from a browser?

I'm using the last one, I open the overlay in Chrome and then copies the URL from there and pastes it into OBS `file:///I:/Firebot%20Development/Firebot%20v3.4.0/overlay/firebot.html
And in Firebot Settings I use "Overlay Compatibility": Other, not OBS.

If you use the "Local File" setting in OBS and browsed for the file you have to use OBS Overlay Compatibility.

**Comment by Firebottle** [comment]
Remember also the image will scale proportionally. If you put in a really talk image it will not continue to stretch wider once it fills the vertical area.

**Comment by ThePerry-2015** [comment]
Closing this as there hasn't been any response in 2 days.
