### ISSUE TITLE
Groups default functionality?

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#187]
I might be misunderstanding the functionality but I my head if I use a group for subscribers and assign buttons to that group, any subscribers would have access to those buttons AND the default buttons, correct? And presumably as the channel owner I would be able to see all the buttons available, correct?

Right now I don't see those extra buttons. Is each group an increased level of access of just completely different buttons? Presumably "Staff" would be channel owner - currently I receive the notice "waiting for game to be ready"

**Comment by ThePerry-2015** [comment]
You as a streamer goes in the Moderator group. Staff = Mixer Staff.
But in the current version of Firebot you can't add access to multiple scenes pr group. The only way to give them access to other scenes you have to give them Switch Scene or Switch Group buttons so they can change the scene they sees or the group they belong to. Hopefully that made some sense. ;)

**Comment by Firebottle** [comment]
Yep we have an article up about scenes and scene changing that might help. 

Each group sees one scene of buttons.

**Comment by Firebottle** [comment]
What you assumed in the second part of the question was correct except channel owners are marked as moderators like Perry said.

Waiting for game to load sounds like a different problem altogether though. That means your interactive isn't connecting correctly.

**Comment by awrebels** [comment]
Interesting. I will play around with it and see if it is an error on my part. Thanks for the explanation
