### ISSUE TITLE
3.4.0 Still having issues with short cooldowns overwriting longer timers

### ISSUE THREAD

**Issue by Kylix-Tyfurious** [Firebottle/Firebot#188]
I just did multiple tests and it now seems to be happening consistently. I have a button on a 3m cooldown, then press a button that would normally cooldown all buttons for 10s and the 3m switched to 10s.

Not sure why it's happening, but I thought I'd bring it up here since this feature is new.

**Comment by Firebottle** [comment]
Can you give more details as to the setup or send over the controls file? I tested this quite a bit and never seemed to get the issue.

**Comment by Kylix-Tyfurious** [comment]
No problem @Firebottle Here's the .json 

https://drive.google.com/file/d/0B8Yo0Os_yTMsNl82U1NWNkZTalE/view?usp=sharing

As for more detail, the best I can provide is that the feature was working for me to begin with, but I made a few changes to one or two buttons and suddenly the smaller cooldowns were overwriting the larger ones again.

**Comment by ThePerry-2015** [comment]
Do you mind adding me to the list of users allowed to use the board? I'd like to see this on my own end while running it with a custom Firebot code-base. Then I can see where and when it overwrites the longer cooldown with the short one so that we can pinpoint the reason.

**Comment by Kylix-Tyfurious** [comment]
Alright @ThePerry-2015 I added you to the board as well!

**Comment by Firebottle** [comment]
I've put together a build for cooldown changes and am waiting on testing. I think this issue is related to #185 .

**Comment by Firebottle** [comment]
https://github.com/Firebottle/Firebot/releases/tag/v3.4.1

@Kylix-Tyfurious can you try  this release and let us know if it fixes the issue for you?

**Comment by Kylix-Tyfurious** [comment]
@Firebottle Tested everything extensively today and had no issues with short cooldowns overwriting longer ones! Tested in 4 different browsers as well. Chrome, Canary, Opera and Edge. Everything looks good for this issue. Thank you for the fix! @ThePerry-2015 You guys are amazing.
