### ISSUE TITLE
StreamJar/Tippee Integration

### ISSUE THREAD

**Issue by Thompson-Kaa** [Firebottle/Firebot#190]
It would be cool and/or sweet if there could be integration with StreamJar or Tippee so that events there(ie. follows, subs, tips, etc.) would cause an event to occur like an interactive button.

**Comment by kateract** [comment]
Follows and Subs would be able to come from the Mixer API, but tips would have to come from the third party API, and I'm not sure we'd want to keep track of more auth tokens. It's worth exploring, but I think we might want to split tips into a separate issue and call this "Sub/Follow Event Integration"

**Comment by wcphart** [comment]
Or for those of us not at partner level yet, triggering off Gamewisp subs?
