### ISSUE TITLE
After i press Ctrl + Alt + F12 to disconnect interactive i cant get it back on 

### ISSUE THREAD

**Issue by mrmoviemaker88** [Firebottle/Firebot#194]
After i press Ctrl + Alt + F12 to disconnect interactive i cant get it back on  again 
i get 
Error
There was an error with bot chat or it was disconnected.

**Comment by ThePerry-2015** [comment]
Which version are you on?
I seem to have issues using the CTRL+ALT+F12 to disconnect, when I do it just reconnects in the same "second".

**Comment by mrmoviemaker88** [comment]
3.0 i Think i look when i am home from work for when i press ctrl+alt+f12 the soundbord start and crash 1 sec after 


Skickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: Perry <notifications@github.com> Datum: 2017-06-16  08:46  (GMT+01:00) Till: Firebottle/Firebot <Firebot@noreply.github.com> Kopia: mrmoviemaker88 <danne07@gmail.com>, Author <author@noreply.github.com> Rubrik: Re: [Firebottle/Firebot] After i press Ctrl + Alt + F12 to disconnect interactive i cant get it back on (#194) 
Which version are you on?

I seem to have issues using the CTRL+ALT+F12 to disconnect, when I do it just reconnects in the same "second".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Firebottle/Firebot","title":"Firebottle/Firebot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Firebottle/Firebot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ThePerry-2015 in #194: Which version are you on?\r\nI seem to have issues using the CTRL+ALT+F12 to disconnect, when I do it just reconnects in the same \"second\"."}],"action":{"name":"View Issue","url":"https://github.com/Firebottle/Firebot/issues/194#issuecomment-308947431"}}}

**Comment by ThePerry-2015** [comment]
If you are using v3.0 it's pretty outdated.
Do you have the same behaviour when you use the connect button at the bottom?

Hopefully there will be a new release of Firebot tonight, or late night for us Scandinavian, when Firebottle is back from Vegas.

**Comment by mrmoviemaker88** [comment]
did get the soundbord to work again i did remove banned users and now it works

**Comment by mrmoviemaker88** [comment]
it did crash again so  i did download  3.4.0 and did add the bord again from mixer and did copy the old Soundbord.json and have try it in 4h now and work fine

**Comment by Firebottle** [comment]
Closing, as it looks like the update to 3.4.0 fixed it for him.
