### ISSUE TITLE
[From E3] Do not disconnect interactive if chat disconnects.

### ISSUE THREAD

**Issue by ProbablePrime** [Firebottle/Firebot#197]
It looks like the connection logic for chat and interactive are too closely coupled so that if one disconnects it will report that the other one has also disconnected to the renderer.

**Comment by Firebottle** [comment]
Uncoupled chat from interactive so they can operate independently. Also made changes to the auto grouper so that it will start and stop as needed since it requires both connections to run.

**Comment by Firebottle** [comment]
Released 4.4.0
