### ISSUE TITLE
[From E3] Sanity check cooldowns to prevent duplicate sounds.

### ISSUE THREAD

**Issue by ProbablePrime** [Firebottle/Firebot#198]
If a button push is recieved by firebot during the time it takes for a cooldown to be triggered on the service it will get through.

Here's a flow:
T0: User A presses interactive button
T1: Firebot receives User A button press event, plays sound
T2: User B presses button
T3: Firebot sends message to set cooldowns
T4: Firebot receives User B button press event, plays sound
T5: Server receives command to disable buttons

We may look at solving this in `interactive-node` but it is reported here.

**Comment by Firebottle** [comment]
Released in the dank update 4.2.0
