### ISSUE TITLE
Feature Request: Video

### ISSUE THREAD

**Issue by mrmoviemaker88** [Firebottle/Firebot#199]
can you add so whe can add in movies to the overlay 
like this one [https://www.youtube.com/watch?v=RzE62hW-w0s](url)

**Comment by Firebottle** [comment]
You can already do this via the HTML button! However, we'll eventually had a video button to make it a bit more straightforward.

**Comment by mrmoviemaker88** [comment]
thanks for answering me so fast need to look on thet :)

**Comment by Firebottle** [comment]
Just adding notes from the stream. We're looking at adding a dropdown so either the file picker or the youtube field is visible in the UI but not both at the same time.

**Comment by Firebottle** [comment]
Release 4.0.0-beta.1
