### ISSUE TITLE
Feature Request: Moderator/Editor Local UI

### ISSUE THREAD

**Issue by Lagby** [Firebottle/Firebot#201]
Here's a tall order and probably not within reason for Firebot.  But I'm going to throw it in there to see maybe at some point you masterminds can think of something along these lines.

I have attempted to use a moderator's board/scene and there was a complaint about seeing it flip/flop when any of the moderators hit it.. etc.. etc..  This has me thinking about how cool it would be if there was a separate panel my moderators or selected individual editors can access... locally(on their comps).. that can trigger overlay elements etc.  In turn Firebot would be working as a server to handle those requests.  

The most basic of push button panels that doesn't interfere with current boards. 🔘 

Keep up the great work!

**Comment by Firebottle** [comment]
Just an update on this one.

We've started work on getting chat commands in place that would allow users to trigger specific things within Firebot through chat. This would most likely bypass spark costs as the button press itself is what triggers that, but it might help with some of what you're looking for. 

I don't know when it will actually be pushed live, but it's in the making.
