### ISSUE TITLE
Unable to Load Board

### ISSUE THREAD

**Issue by mrpaden** [Firebottle/Firebot#202]
I am having trouble getting my board to load. If I try to connect, it tells me I need to load an interactive board. When I try to load my "Firebot" board, I get the error "Unable to load this board. Try restarting the app."

Unfortunately restarting the app does nothing, as does trying it again, restarting the system, uninstalling, reinstalling, downgrading, reupgrading. I continue to get this error. However, it seems to load my other boards with no problems. The only way I seem to be able to access my usual board is to delete the .json file and reimport the code. However, this would require me to reprogram all of my buttons(which I have a lot) and is something I already had to do recently(see previous post by me). Perhaps the .json files are becoming corrupt somehow? Either way this is troubling and I can't be reprogramming the thing every week.

Is there a way to fix this so my old .json will work? Or at the very least, make it so I don't need to do this so often. This worked fine a couple days ago and I hadn't changed anything on the board since besides updating the software.

**Comment by mrpaden** [comment]
![sketch](https://user-images.githubusercontent.com/13129352/27264841-3739614a-5456-11e7-9b1f-5223aac7aa11.png)

**Comment by Firebottle** [comment]
Hello, can you please attached the board.json file that you're having issues with so we can troubleshoot?

**Comment by mrpaden** [comment]
[Firebot.zip](https://github.com/Firebottle/Firebot/files/1086820/Firebot.zip)

**Comment by mrpaden** [comment]
Attached above in a zip. Hope thats okay.

**Comment by ThePerry-2015** [comment]
I just tried loading your board in my Firebot 3.4.1 and it took a little bit longer than with any of the other boards I've loaded up, but it ended loading up just fine. I'm not able to connect using it, but that's because I don't have access to the board in Mixer Interactive Studio. If you could go into the board on Interactive Studio and click the share icon up top on the right side and set it so that everyone with the code can access it or give access to Firebottle, ebiggz, kateract and me(ThePerry) that would be nice. Makes it easier to check for bugs and such as we can use the board on our end as well.

**Comment by mrpaden** [comment]
Well that's just odd and makes me feel dumb :/. I had already reimported another version of the board and rebuilt it. However, I tried loading back the old .json and it does seem to load now. ¯\_(ツ)_/¯  I don't get it. Anyway, I added all of your names to access. Perhaps there's a flag there somewhere.

Am I just going too hard? Like, is there too much and the bots freaking out from time to time?

**Comment by mrpaden** [comment]
Also thanks for your always quick responses. Great support here.

**Comment by ThePerry-2015** [comment]
I just retired to connect with your Firebot board and it works just as it should on my end, not sure if it might be that Firebot gets upset by the amount of buttons and boards, but I've connected and disconnected and restarted Firebot multiple times now and not had one single hiccup. I think we might need some input from @Firebottle here.. :)

**Comment by Firebottle** [comment]
So, anytime you try to load the board in Firebot it will hit the Mixer API and try to grab all of your newest changes for that board. If, for whatever reason, it can't hit the Mixer API it will not load the board right now. That's the only reason I can think of that it didn't load before but does now.

I thought I put an error message in for that though... but yeah, right now loading up a board depends on being able to connect to the mixer api.

**Comment by mrpaden** [comment]
Makes sense. It does seem to work now which is a good sign, so I guess if I encounter this again I'll just be more patient next time(my own thing to work on). I'll follow up again if I encounter the same issue and maybe whats wrong can be more easily found while it's actively having the problem. You guys rock. Thanks.
