### ISSUE TITLE
Bot doesnt send chat

### ISSUE THREAD

**Issue by pnkllr** [Firebottle/Firebot#203]
#### Describe your issue or feature request:
When setting up an effect for the bot to send something to chat. Nothing gets sent (tried reloging bot, same result) 

Sending as streamer works fine

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
3.4.1

- Have you tried the troubleshooting steps located on the wiki?
Yes

- Are you able to reproduce the issue? If so, what steps did you follow?
Create an effect that requires bot to send something to chat.

- Have you gone to /firebot/user-settings/controls and attached the problem controls file to this issue?
Yes

**Comment by ThePerry-2015** [comment]
That's true, Scorpio should do something about that. As it is now it doesn't show anything from the bot account which isn't sent via the Scorpbot user interface. So things like loots messages as well as firebot bot messages are not visible inside Scorpbot.
