### ISSUE TITLE
[Feature Req] Event Log Ignore

### ISSUE THREAD

**Issue by DakotaBlake** [Firebottle/Firebot#205]
I have multiple scenes in my soundboard/GIFboard. I have buttons acting as page indicators. I'd like to disable these buttons. Though it's more a stylistic thing, it would also prevent spamming of the button in the log on Firebot.

**Comment by ThePerry-2015** [comment]
Sorry, not sure why I removed [Feature Req] from the title.. But yeah, tagged it as a feature request.. 👍

**Comment by Firebottle** [comment]
This should be released in the next update.

**Comment by ebiggz** [comment]
Released in 4.2.2.
