### ISSUE TITLE
Problems with cooldowns

### ISSUE THREAD

**Issue by Jeystron** [Firebottle/Firebot#213]
#### Describe your issue or feature request:

So i created my board on firebot, did individual cooldowns and group cooldowns but viewers can still spam the button none stop..

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
Release v3.4.1

- Have you tried the troubleshooting steps located on the wiki?
Yes

- Are you able to reproduce the issue? If so, what steps did you follow?
Everytime i connect the soundboard i tell people to test it out and they are able to spam it since cooldown is not working. 

- Have you gone to /firebot/user-settings/controls and attached the problem controls file to this issue?
I dont' think i have'

- Go to Interactive Studio, edit the board in question, click on the share icon beside the board name up top in the right part of the view. Choose only allow specific .... then type in our names and click add and you should be ok. (Firebottle, ebiggz, kateract and ThePerry)

**Comment by ThePerry-2015** [comment]
> Have you gone to /firebot/user-settings/controls and attached the problem controls file to this issue?
> I dont' think i have'
Can you do that? Inside the folder where you have unpacked Firebot, go into the user-settings folder and see the control folder, open that one, there should be a file named the same as the board you have inside Firebot. Right click this file and make a zip-file, (Send to -> Compressed (Zipped) folder. Then attach this file to this thread either by clicking and dragging it into your browser window, or by clicking on the Selecting them text beneath the text form here when editing your previous post or when answering in a new comment.

**Comment by Firebottle** [comment]
There has been no response in four days on this issue. I'm going to go ahead and close this one. Please open a new issue if you continue to have issues.
