### ISSUE TITLE
Soundboard cooldown problems

### ISSUE THREAD

**Issue by snipe86k** [Firebottle/Firebot#217]
#### Describe your issue or feature request:
I am writing for possible insight on an issue I am having with the soundboard. I have been using soundwave interactive and for some time it has been working well. But the last 6 or 7 streams every button has been overridden with a 1h cooldown instead of a few minutes as I have them set in the software. I have tried to delete the whole editor profile on mixer and redo it. I have also now switched to firebot, and again deleted the profile on mixer starting again fresh and every time I have this 1h preset cooldown thing. with this switch to firebot I have also blocked out and uninstalled soundwave interactive. Please let me know if you guys have any thoughts.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
v3.4.1

- Have you tried the troubleshooting steps located on the wiki?
Yes

- Are you able to reproduce the issue? If so, what steps did you follow?
Yes, simply launching the board. Every button I make has a 1-2h cooldown evn though I only set it for 1-2 seconds or any amount of seconds.

- Have you gone to /firebot/user-settings/controls and attached the problem controls file to this issue?
Yes [Firebot soundboard.zip](https://github.com/Firebottle/Firebot/files/1107191/Firebot.soundboard.zip)

- Go to Interactive Studio, edit the board in question, click on the share icon beside the board name up top in the right part of the view. Choose only allow specific .... then type in our names and click add and you should be ok. (Firebottle, ebiggz, kateract and ThePerry) 

This is also done.

**Comment by Firebottle** [comment]
I looked at your json and the highest cooldown is 600 seconds. So, I connected with your board and tested five buttons. All five of the buttons I tested seem to be cooling down for the appropriate amount of time.

You say this is happening to you with soundwave interactive also?

**Comment by snipe86k** [comment]
It was on soundwave also yes. I moved from soundwave to firebot and it did
the same thing. I'll give it a go and see what happens to be sure it's
still there and update you afterwards.

**Comment by Firebottle** [comment]
Okay, well if you're having the same issue on two different apps you might need to contact mixer support. I did not see anything in your JSON file or while testing that would cause hour long cooldowns from Firebot. So that makes me think it's something beyond our control.

https://mixer.com/contact

**Comment by Firebottle** [comment]
I'm going to go ahead and close this as it's not an issue specific to Firebot. Please contact mixer support and relay the information to them so that they can help out. Make sure to let them know that the issue occurs when using multiple programs.
