### ISSUE TITLE
Auto Updater

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#226]
We were shown a really cool electron package today that might work as an auto updater for us.

https://github.com/juampi92/auto-updater

**Comment by ebiggz** [comment]
I looked into this and found that it likely won’t work.

For one, this specific package simply downloaded a zip of the source code, not the compiled app. 

So instead I tried writing custom logic for firebot that would download the compiled release zip and extract it, but I also ran into many problems with that.

The biggest issue is that you can’t extract a zip of firebot in place while the app is running as firebot.exe is locked. The only way I could think of to workaround that would be to create a second very small updater app that Firebot would open and then firebot would close itself. Then the updater app would extract the zip and reopen Firebot. This approach has problems of its own, and regardless, I think we are getting to the point where it’s just as complicated as implementing a proper electron updater.

**Comment by Firebottle** [comment]
For reference later:

electron-gh-releases is another promising package for doing this when we have time.

**Comment by ebiggz** [comment]
This was accidentally duplicated with #268. We've been tracking progress on that item so I am going to close this one.
