### ISSUE TITLE
White Loading Screen

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#23]
When the app is first starting up the window is white until the app can load the main html file. We need to keep the window hidden until it finishes loading to avoid that white screen and load smoother.

**Comment by ThePerry-2015** [comment]
I think the best way to get around this would be to set a background color of the body as close to the image backgrounds as possible.

**Comment by Firebottle** [comment]
Fixed this by hiding the window via electron options and then showing it after everything has loaded.
