### ISSUE TITLE
Cooldowns Are Not Applying

### ISSUE THREAD

**Issue by Thompson-Kaa** [Firebottle/Firebot#230]
#### Describe your issue or feature request:

MY BOT IS NOT COOLING DOWN FOR SOME USERS AND AS A RESULT I HAVE TO DO LIKE A MILLION PUSHUPS PLEASE SEND HELP OMG

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?

- Have you tried the troubleshooting steps located on the wiki?

- Are you able to reproduce the issue? If so, what steps did you follow?

- Have you gone to /firebot/user-settings/controls and attached the problem controls file to this issue?

- Go to Interactive Studio, edit the board in question, click on the share icon beside the board name up top in the right part of the view. Choose only allow specific .... then type in our names and click add and you should be ok. (Firebottle, ebiggz, kateract and ThePerry)

**Comment by Firebottle** [comment]
HELLO YOU HAVE NOT FILLED OUT ANY OF THE OTHER INFORMATION WE NEED TO HELP YOU. PLEASE FILL OUT THE REMAINING INFORMATION SO THAT WE MAY ASSIST.

**Comment by Thompson-Kaa** [comment]
THAT IS TOTALLY OKAY MY ARMS WERE FALLING OFF WHEN I WROTE THAT I WILL GIVE
YOU MORE DETAIL AS SOON AS POSSIBLE I LOVE YOU

**Comment by Thompson-Kaa** [comment]
I'm still away from my PC but I just remembered that I had recently changed
a bunch of spark values for buttons(from x to zero). Maybe that's a thing?

**Comment by Firebottle** [comment]
Could you give the newest beta a shot and see if that helps? I know we made a few different changes to cooldowns and it might solve the issue.

**Comment by Firebottle** [comment]
@Thompson-Kaa any update?

**Comment by Thompson-Kaa** [comment]
Not yet; was going to test last night but between personal issues and OAuth
problems, I couldn't. I intend on testing with the afflicted users tomorrow.

**Comment by Thompson-Kaa** [comment]
I just tested it live with both group cooldowns and individual cooldowns
set to 30s and the cooldowns are not applying. I'll attach things right
away.

**Comment by Thompson-Kaa** [comment]
Here is my file: https://drive.google.com/open?id=0Bw1PyfFtlzXsZ0duY0l2cTJLNFE

You should still have access to it via Studio but if not just yell at me.

**Comment by Thompson-Kaa** [comment]
Probably Pertinent Information: I could always get the cooldown to work for me, but others had zero cooldowns. You will need two people to test this.

**Comment by Thompson-Kaa** [comment]
I've been doing a bunch of QA on this bug and I am finding some weeiirrdd stuff. I found out that I can make the bug occur if I have Firebot running on my encoding PC and I am accessing Mixer via another PC. If I use Mixer with the same PC that Firebot is running on, I do not see the bug.

Now for the messed up part. I found out that *some* of my buttons have working cooldowns(specifically ShiftUp, ShiftDown, FiveMore, Zero, Average, Random). Every other button does not have a working cooldown. I then tested by increasing the cooldown on a button until it worked(HYPE, increased by increments of 100). Once I found a number that worked, I could make the cooldown work at lower amounts if I changed the cooldown by 10, disconnected, reconnected and retested.

I HAVE NO IDEA WHY AND I AM SCARED PLS HOLD ME

**Comment by Firebottle** [comment]
We believe this is an issue with Mixer and not Firebot. Firebot can't choose which users see the cooldown. It's either a yes or a no. 

So, you'll need to report the issue to mixer.

**Comment by Thompson-Kaa** [comment]
I've messaged Mixer and they came back with this:

Thank you for contacting Mixer. Since you are dealing with a 3rd party bot, we cant say for sure if its the bot or us. We would need Firebottle to show us the data of why this would be a Mixer problem. If you can bring data and errors that happen for you so we can see what the problem is, that would help a great deal.

Is there any data(ie. log info, etc.) that I can send them to help them debug?

**Comment by ThePerry-2015** [comment]
Ok, we are in contact with ProbablePrime about this issue, and will get back to you. We might have to build a special client for you that can gather Interactive data and details so we can send them to him to figure out where the issue is located.

**Comment by Thompson-Kaa** [comment]
Dope. Let me know if there's anything I can do; I will make time to get this problem resolved.

**Comment by Firebottle** [comment]
I'm going to go ahead and set this as a bug for now while we look into it. I'm not entirely sure we can fix it, but we'll run through the cooldown settings to double check everything.

**Comment by Firebottle** [comment]
After troubleshooting we found that this was due to the computer clock running Firebot being out of sync by a minute. This causes it to send over cooldowns that are already expired for computers with synced up clocks.
