### ISSUE TITLE
[4.0] Spruce up styles for remaining rough edges

### ISSUE THREAD

**Issue by ebiggz** [Firebottle/Firebot#231]
Things to improve:
- [x] Checkboxes
- [x] Various panels to match button panels (ie viewer groups, board settings)

**Comment by Firebottle** [comment]
Built functionality into the settings area for a theme switcher (currently setting in a branch). Let me know once you've finished up on this one and I'll reorganize the CSS to easily build out a bunch of themes based on what you do in this one.

**Comment by ebiggz** [comment]
This is all done, sorry about that, meant to push it up last night.
