### ISSUE TITLE
Can't delete member from custom group

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#233]
#### Describe your issue or feature request:
Seems like I can't delete any members from a custom group. Must delete group and re add members. 

As a side note what happens if a member is in multiple custom groups? Do they get no buttons or perhaps an option is to get both; although seems like mixer's interactive studio doesn't allow that. 

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
3.4.1

- Have you tried the troubleshooting steps located on the wiki?
yes

- Are you able to reproduce the issue? If so, what steps did you follow?
yes - open custom group, click red X next to user name, does not delete user. 
-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by Firebottle** [comment]
Hello, this will be fixed in the next release. Thanks for the report!

**Comment by Firebottle** [comment]
Release 4.0.0-beta.1
