### ISSUE TITLE
Images no longer appearing

### ISSUE THREAD

**Issue by JazzyPlaysXbox** [Firebottle/Firebot#236]
#### Describe your issue or feature request:

okay so everything was fine up until 2 days ago, the images no longer appeared when viewers were pressing the interactive buttons on firebot v3.4.1, i have tried removing them and re-adding, also tried re-adding the overlay on obs but no such luck.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?

- Have you tried the troubleshooting steps located on the wiki?

- Are you able to reproduce the issue? If so, what steps did you follow?

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by Firebottle** [comment]
@JazzyPlaysXbox It looks like you missed filling out all of the other information we need. Please fill out the rest of the information so that we can help you.

**Comment by Firebottle** [comment]
Hello, could you try 4.0.0-beta.1 and see if that helps?

**Comment by JazzyPlaysXbox** [comment]
Installing now

**Comment by JazzyPlaysXbox** [comment]
I'm going to try and uninstall the whole thing and reinstall, just doesn't
seem to work

**Comment by Firebottle** [comment]
Okay, the newest version offers some feedback in the overlay if it is unable to connect to Firebot. It will tell you in the top left corner.

There is also an option to change ports for the app. This might also fix the issue, but make sure to read the instructions on the settings page for it.

**Comment by JazzyPlaysXbox** [comment]
Thank you, really appreciate the help
