### ISSUE TITLE
Stats tab

### ISSUE THREAD

**Issue by ebiggz** [Firebottle/Firebot#240]
It would be cool if there was a 'Stats' tab that displayed various stats to do with Firebot. We could use something like [chart.js](http://www.chartjs.org/) to make the data look good. 

Some ideas for stats:
- number of presses per button (per day / all time)
- amount of sparks spent per day / all time
- number of presses per user (per day / all time)

We'd need to be conscious of performance impacts on this one. Not sure if the JsonDb would be good for this. We would be limited in how much we can track if we wanted to stay performant. Using something like SQL would give us more flexibility.

**Comment by ebiggz** [comment]
Just realized this contains the idea from #102 but this expands on that further so I don't think its a full duplicate.

**Comment by Firebottle** [comment]
I went ahead and closed #102 because this is a great idea and would fully cover the other idea.

But yeah, biggest thing is we'd have to keep a close eye on performance. This is a really cool "nice to have" feature if we can get it working with little impact.
