### ISSUE TITLE
[4.0] Sidebar sometimes resizes but it should always be fixed

### ISSUE THREAD

**Issue by ebiggz** [Firebottle/Firebot#241]
The sidebar shouldn't ever resize outside of the button to collapse/open it. 
I noticed the sidebar got all weird when you went to the "Updates" tab after I added the screenshot. The screenshot was super wide and so it forced the tab context to push the sidebar to be a bit smaller (I've since updated the post to use a smaller screenshot, thus hiding this issue for now). 

I already have a fix for this, just wanted a bug to tie the change to.

**Comment by Firebottle** [comment]
released in 4.0.0 beta 2
