### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by ebiggz** [Firebottle/Firebot#243]
Since we have utilized angular services to abstract a lot of our data and logic for stuff, we can now easily bring in that data anywhere and use it in fun ways.

Because of this, I think it would be cool if there was a "Dashboard" page which a user could customize, that would show various widgets containing info for a particular thing. This tab would be designed to be the tab the user would want to have have open the most during a stream.

I am envisioning the tab looking kind of like the Moderation tab, where a widget could look like how the "Event Log" and "Banner Users" sections currently do. Just a card with a header containing a title and maybe some controls, and then an area for content, organized into rows of two. We could even make it so the user can designate a widget to take up a full row.  And they of course should be able to edit the order of the widgets. These widgets could be angular Directives, making it easy for us to plop them down in whatever fashion we wanted.

Ideas for widget types:
* **Event Log widget** - basically how it is now for the mod tab, just a stream of events
* **Button list widget** - a widget that would let the user create a list of button that they perhaps want easy access to manually trigger
* **Stats widget** - if we implement a stats feature ( #240 ), there could be a widget that displays a specific stat
* **Mini widget container widget** - a widget that could perhaps hold three or so "mini widgets"/widgets that are just smaller (Ie, a mini button widget that just shows 1 button, or a stats widget that just shows a single data point of a stat, instead of a graph. The idea being it would allow the user to utilize more space for even more data that they want.
* **Mini-game widget** - if we ever implement minigame stuff, there could be a widget that lets you initiate a game or something.
* **Chat widget** - If we implement chat specific functionality, perhaps there would be something worth putting into a widget for it. Doesn't have to be just another chat feed though.

We could do a lot with this, but ultimately how far we'd go with it would just depend on how much we think people would use it.

**Comment by FluffyMatt** [comment]
This is a great idea. I love the idea of having chat and stats all in 1 window

**Comment by Gopherboy76** [comment]
In-app live chat would be great. Also, as a new start at streaming in Mixer, I'm only getting a few visitors and hour and have sometimes missed their message (usually I have mixer pop-out chat on 2nd screen but gets lost under OBS & other stuff) 
So, a small suggestion of a selectable alert, a small pop-up message like a windows alert or audio signal to notify a new viewer message in chat.

With a previous suggestion of sending audio effects to the overlay, it would allow audible alerts for in-app notification to output through the bots selected Sound Output Device separate to the stream feed.
