### ISSUE TITLE
Chat Messages Not Being Sent

### ISSUE THREAD

**Issue by 5parkyy** [Firebottle/Firebot#245]
#### Describe your issue or feature request:
I created a button to send a chat message. When it is triggered it presents an error "There was an error sending a chat message"

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running? 

4.0.0

- Have you tried the troubleshooting steps located on the wiki? 
Yes. I also tested the same command on previous versions and it works correctly

- Are you able to reproduce the issue? If so, what steps did you follow? 
Create a button with the "chat" effect. Regardless of what text is supposed to be sent, it will error.

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!
[Test - Copy.txt](https://github.com/Firebottle/Firebot/files/1117899/Test.-.Copy.txt)

**Comment by Firebottle** [comment]
Thanks so much for helping test out 4.0. We'll take a look at this and get it patched up.

**Comment by MAPReiff** [comment]
I'd like to also say I'm having the same issue, letting the devs know it is not an isolated issue.

**Comment by ebiggz** [comment]
This has been fixed and should be available in the next beta build. Thanks for the report!

**Comment by Firebottle** [comment]
released in 4.0.0 beta 2
