### ISSUE TITLE
[4.0 Beta 2] Nothing showing on overlay

### ISSUE THREAD

**Issue by DropDeadZed** [Firebottle/Firebot#246]
#### Describe your issue or feature request:
nothing is showing up on new overlay html file. I've  tried all browsers and sources.
-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
4.0.0 beta2

- Have you tried the troubleshooting steps located on the wiki?
I've reinstalled java and tried all browsers

- Are you able to reproduce the issue? If so, what steps did you follow?

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by DropDeadZed** [comment]
I can get the images to show up on older firebot overlays, kinda weird. I would use that as a workaround but you can't configure placement it seems.

**Comment by ebiggz** [comment]
Thanks for the report, DropDead.

I can't reproduce this issue on my current setup. Fireworks, imagines, videos, etc are all show correctly in the overlay. This makes me think that perhaps there's something going on with one of your save files. 

If possible, navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with to this thread (You can just drag the file into the text box).

Also, I want to see if there is any errors in your overlay. If you can, make sure Firebot 4.0 is running, then open up the overlay file in Chrome. Now press **F12* to bring up the developer tools panel and then click on the "Console" tab, if you aren't already on it. Just let me know what you see there, if anything. You can just take a screenshot of it, if you prefer. If the overlay doesn't have any errors, you'll probably just see something like "Connection is opened on port 8080...".

**Comment by DropDeadZed** [comment]
here is the zip
[Zed-FireNEW.zip](https://github.com/Firebottle/Firebot/files/1117996/Zed-FireNEW.zip)

**Comment by DropDeadZed** [comment]
Failed to load resource: net::ERR_FILE_NOT_FOUND
main.js:4 Uncaught ReferenceError: WEBSOCKET_PORT is not defined
    at mixerSocketConnect (main.js:4)
    at main.js:47

**Comment by DropDeadZed** [comment]
firebot.html:18 GET file:///D:/twitch/firebot/Firebot-master/new%20beta/Firebot-win32-x64/user-settings/overlay-settings/port.js net::ERR_FILE_NOT_FOUND

**Comment by DropDeadZed** [comment]
I FIXED it!!! I had to open the ADVANCED tab and edit the connection port, but I did not edit the port I just left the port the same and it seemed to generate the port.js file I was missing.

**Comment by ebiggz** [comment]
I had a feeling it was a port issue. 

Not sure why the port.js file wasn't getting created for you the first time around though. I can't reproduce that problem on my end, it gets created every time. We can at least guard against the symptom of the file not getting created. I have added in some safe guards to hopefully minimize this issue. 

Since you are the only one reporting this problem at the moment, I am going to leave the change at that and see if it crops up again. Thanks for the report!

**Comment by Firebottle** [comment]
Released https://github.com/Firebottle/Firebot/releases/tag/v4.0.0-beta.3
