### ISSUE TITLE
Firebot wont resync board

### ISSUE THREAD

**Issue by DropDeadZed** [Firebottle/Firebot#247]
#### Describe your issue or feature request:

Firebot no longer resyncs my board.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
4.0.0 beta2

- Have you tried the troubleshooting steps located on the wiki?
i've tried loggin in and out of bother the bot and website, re-saving the board multiple times.
The yellow "loading" circle just spins and spins forever.

- Are you able to reproduce the issue? If so, what steps did you follow?
yes, happens every time I try to resync after opening firebot

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by DropDeadZed** [comment]
I did get it to update now and all buttons show up after I re-saved in mixer. Now the buttons do nothing when pressed.

**Comment by Firebottle** [comment]
@DropDeadZed are the settings still on the buttons or were they overwritten?

**Comment by DropDeadZed** [comment]
I had to redo the button actions, no big deal.
