### ISSUE TITLE
[4.0 Beta 2] Renaming a Viewer Group causes a duplication

### ISSUE THREAD

**Issue by ebiggz** [Firebottle/Firebot#249]
If you rename a viewer group and save, it duplicates the previous group instead of just renaming it.

**Comment by DropDeadZed** [comment]
I find also that my custom viewer group is never available to be picked in a button option. If I wanted a mod only button, my MOD group is never available to me for assignment.

**Comment by Firebottle** [comment]
Released https://github.com/Firebottle/Firebot/releases/tag/v4.0.0-beta.3

@DropDeadZed it sounds like that is a different request. If you're still having the issue with the latest built can you open up a different bug for us?
