### ISSUE TITLE
Emote celebration option

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#255]
From warblade:
Ok, well, I'll post here anyways. Would be neat to add a "Celebration" of "Emote-confetti". It could work similar to what KappaGen did for Twitch (https://youtu.be/0cVMAwWLMN0?t=101). Basically, you can select what emotes to use (or select your own files), and then adjust settings and create a trigger.

From Firebottle:
There is an api endpoint to get sub emoticons for a channel. It pulls a spritesheet, but the endpoint has the x/y coordinates of each emote.  https://mixer.com/api/v1/channels/40812/emoticons

**Comment by Firebottle** [comment]
Per ebiggz: http://a-jie.github.io/Proton/#example

could use that to do some extra cool stuff.

**Comment by TweakGames** [comment]
Are you still working on this?  It would be a great feature to have! :D

**Comment by lurk24** [comment]
does this feature do anything other than fireworks? I mean, does it actually show the emotes/skills from mixer's chat? I was sort of expecting it to be more like the kappagen but all im finding is fireworks.

**Comment by Firebottle** [comment]
All it currently does its fireworks. We will be adding more options later.

**Comment by lurk24** [comment]
thanks for confirming
