### ISSUE TITLE
Cooldowns

### ISSUE THREAD

**Issue by BackdraftMixer** [Firebottle/Firebot#263]
#### Describe your issue or feature request:
Setting cooldowns for 30 seconds and 60 seconds and they're appearing as 4 to 8 hours long on stream for viewers.

Feature request: Ease of access on setting global cooldowns on new update

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
3.4.1

- Have you tried the troubleshooting steps located on the wiki?
Yes

- Are you able to reproduce the issue? If so, what steps did you follow?
I just activate the soundboard and the issues stay the same
-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by Firebottle** [comment]
This is an issue on mixers end. Please enter a support request at
mixer.com/contact
