### ISSUE TITLE
Error Logging

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#266]
We need an easy way to log errors to a file along with the currently selected board JSON so that we can easily troubleshoot any errors that pop up.

**Comment by Firebottle** [comment]
Pull request entered for this one. Super simple error logging that fires anytime the error modal is triggered. Saves the error text and the controls json to a file in the /logs folder. This could probably be greatly improved.

**Comment by Firebottle** [comment]
Thinking about this today, I don't know if this is the best way to go about it. I have a feeling people will end up with a ton of log files if it triggers on every error. Maybe we need an extra parameter for the error function that tells it to log or not. That way we can log important things and not other random stuff.

**Comment by Firebottle** [comment]
Reworked it to use the Winston package for error logging. It now will create a single file for that day and then log all errors to that file for the day. Should help a ton, plus Winston has a bunch of other options we can use if we need to later.

**Comment by ebiggz** [comment]
That sounds awesome!
