### ISSUE TITLE
Autoupdating

### ISSUE THREAD

**Issue by ebiggz** [Firebottle/Firebot#268]
It would be great to have an autoupdater like Deek uses.

He uses:
https://github.com/jenslind/electron-gh-releases

We dont need to use a cert.

----------------
Branch: fb-auto-updater

- [x] Get installer working
- [x] Get auto updater working.
- [x] Create shortcuts on install.
- [x] Replace default installing/updating gif with a Firebot related one.
- [x] Replace setup gift icon with a Firebot related one.
- [x]  Check for updates on app launch using version checker.
- [x]  Build window telling the user that an update is downloading.
- [x]  Show that an update has been installed when the app re-launches.
- [x] Move user settings to app data folder so that it can easily be accessed between version.
- [x] Update jsonDB calls to account for the new user-settings app data location.
- [x] Move overlay folder into app data folder after each new version in case it gets updated.
- [x] Add the ability to select the type of updates you'd like to receive.

**Comment by Firebottle** [comment]
- [x] Get installer working
- [x] Get auto updater working.
- [ ]  Build window asking if user would like to update.
- [ ]  Build window telling the user that an update is downloading.
- [ ]  Show that an update has been installed when the app re-launches.

**Comment by ebiggz** [comment]
Modals for downloading update and after an update has been installed have been added to the fb-auto-updater branch.

**Comment by Firebottle** [comment]
Pushed an update that creates desktop shortcuts, and replaces all of the icons with Firebot icons. Only issue is that the shortcut name defaults to "Electron" and apparently the only way to fix that is to:

"You need to hack the electron executable using Resource Hacker, rcedit, or another application to change the ProductName and Icon resources. You'll want to call the above code on both the install and updated Squirrel events."
