### ISSUE TITLE
Able to start a video from a certain point?

### ISSUE THREAD

**Issue by Setarii** [Firebottle/Firebot#276]
#### Describe your issue or feature request:

Feature Request

Just curious if we're able to start a YT video from a certain point in the video or not, or if we're supposed to be able to. I tried setting the time part of it after the YT ID but it didn't work (from the share section on the YT video, i.e. "?t=33s".) Also if I want JUST the sound and not the actual video, I'd figure I'd just make the video 0px tall/wide but that's not working either.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?

4.0.0-beta 5

- Have you tried the troubleshooting steps located on the wiki?

I'll do that right now but not sure if it's a troubleshoot worthy thing.

- Are you able to reproduce the issue? If so, what steps did you follow?

Make a button for YT video, paste in the YT video ID with the time bit at the end of it and watch the button not work. 

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

Github won't let me attach the .json file. Here's the download for it https://file.io/uJuPzd .

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

Done

**Comment by Firebottle** [comment]
It'll be in the full 4.0 release (or perhaps a beta soon)!

**Comment by Setarii** [comment]
Aw yiss

**Comment by Firebottle** [comment]
released
