### ISSUE TITLE
Bot Will Not Connect

### ISSUE THREAD

**Issue by Thompson-Kaa** [Firebottle/Firebot#277]
#### Describe your issue or feature request:

I wish I could give more details, but alas I am limited with this one. I can't seem to connect my bot with my newest board. It connects no problem with other boards I've made(particularly with only one scene). Restarting the app doesn't fix it and I can never get it to connect; it's always in limbo.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
4.0.0-beta5

- Have you tried the troubleshooting steps located on the wiki?
Nope

- Are you able to reproduce the issue? If so, what steps did you follow?

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

https://drive.google.com/file/d/0Bw1PyfFtlzXsRFo1UGF0ZmZhaUU/view?usp=sharing

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by Thompson-Kaa** [comment]
I tested all the things on the wiki and it still does not fully connect. No idea why. Perhaps I still suck.

**Comment by Firebottle** [comment]
Can you uncheck "none" in the help scene and try again?

**Comment by Thompson-Kaa** [comment]
That didn't work. That said, I disabled all Viewer Group Settings and now it can connect.

With that in mind, how will I limit plebs from accessing my Admin section?

**Comment by Thompson-Kaa** [comment]
I think I'm learndings. Duplicate entries in the Viewer Group Settings borks things.

Also, figuring out the control thing too. Yay.
