### ISSUE TITLE
Pulling Button Text into chat.

### ISSUE THREAD

**Issue by EvilKupo** [Firebottle/Firebot#278]
#### Describe your issue or feature request:

I would like to see the ability to pull the Button Text into the chat command.  For example, if I have a button labeled Games I'd like to use something like "$(user) has pressed the $(text) button!" to display "EvilKupo has pressed the Games button" in chat.

This would be useful for button text that is often updated in Mixer Studio.

-----------------------------------------------------------------------

**Comment by Firebottle** [comment]
This will be released in the next update.

Variables are:
User - user who pressed button
Text - Text of the button
Cost - The cost of the button
Cooldown - The cooldown amount for the button

**Comment by ebiggz** [comment]
Released in 4.2.2.
