### ISSUE TITLE
API Effect Improvements

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#279]
- Option to display image related API images in the overlay.
- Add more API sources, such as dad jokes and other silly things.
- Add way to check for 404 images before posting them.

**Comment by Firebottle** [comment]
As part of this, if we can implement a way to detect 404 images before posting to chat that would be awesome.

**Comment by ebiggz** [comment]
@Firebottle Would you call this dev complete? Most of the things have been implemented I'd say.

**Comment by Firebottle** [comment]
Yeah, I'd say dev complete. The biggest thing on my own list was getting the 404s out of the way. That fix is in the beta.

**Comment by ebiggz** [comment]
This has been implemented in
