### ISSUE TITLE
Problem with Button held down feature

### ISSUE THREAD

**Issue by DragonShaft** [Firebottle/Firebot#285]
#### Describe your issue or feature request:

When I configure a button, for example, in overwatch, to be able to fire with the machine gun and it needs to be held down, nothing is happening. 

When I turn down the feature to just be a simple button that you click (without the need to be held down), it's working.

What's weird though is, when I turn on the feature, even if it's not working (the gun doesn't shoot), the input is triggered and registered in Firebot.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
**Release v4.0.0 Beta 5**

- Have you tried the troubleshooting steps located on the wiki?
**Yes and it doesn't work**

- Are you able to reproduce the issue? If so, what steps did you follow?
**Yes I am able to reproduce the issue with Overwatch, for example, and with other games.**

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by Firebottle** [comment]
This will be fixed in the next 4.0 release.

**Comment by DragonShaft** [comment]
Nice! Thank you for the awesome work!

**Comment by Firebottle** [comment]
Released in 4.0.0 main.
