### ISSUE TITLE
Won't load board into firebot/Authentication Failure 

### ISSUE THREAD

**Issue by InstrumentalMixer** [Firebottle/Firebot#286]
#### Describe your issue or feature request:

Attempting to load in my WIP board using interactive 2.0, I copied my code into firebot, nothing will show up now. I had an earlier version working, but stopped being able to access it after a save I made to the board. 

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
v.4.0.0 beta 5

- Have you tried the troubleshooting steps located on the wiki?
Yes

- Are you able to reproduce the issue? If so, what steps did you follow?
Copied board code into firebot-will not load. 

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by Firebottle** [comment]
What save did you make to the board? What did you change that caused it to stop working?

**Comment by Firebottle** [comment]
Going to go ahead and close this one as it's been 4 days without a response. If you're still having issues please go ahead and enter a new ticket for us.
