### ISSUE TITLE
Problem Creating Scenes on Mixer

### ISSUE THREAD

**Issue by TheMadaMaxPayne** [Firebottle/Firebot#288]
#### Describe your issue or feature request: 
     Hi every time I open up Firebot Interactive and click on interactive status to make it Connected it says authentication failed, and then 20 seconds later it says problem creating scenes on mixer.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
  v4.0.0 Beta 5
- Have you tried the troubleshooting steps located on the wiki?
I have tried restarting mixer and saving on every interactive button.

- Are you able to reproduce the issue? If so, what steps did you follow?
I am able to reproduce the issue by simply clicking on Connect Interactive with having my two accounts signed in TheMadMaxPayne as my account and TheMadMaxBot as my Bot. 
-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by TheMadaMaxPayne** [comment]
Sorry forgot the file but what do I happen to do if it is a JSON file?

**Comment by Firebottle** [comment]
change .json to .txt and attach it here.

**Comment by TheMadaMaxPayne** [comment]
Hi I was able to fix it today by signing in and out then re-snyncing board and signing back in.
