### ISSUE TITLE
Updating from 3.4.1 to 4?

### ISSUE THREAD

**Issue by wcphart** [Firebottle/Firebot#289]
Is it ok to update the same way we would for 3.x versions? Just paste over the directory as normal?

**Comment by Kylix-Tyfurious** [comment]
Yes, this is what I did and everything worked normally.

**Comment by Firebottle** [comment]
Yes, just be aware of what a major version change means. You're moving from 3.0 to 4.0 which means there are breaking changes that might cause 4.0 to be incompatible with features of 3.0.

Also be aware that 4.0 is a beta release and not a full release.
