### ISSUE TITLE
Update notifier on beta

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#29]
I'm only updating the json on firebottle.tv for full releases to notify people. However, this means that people using beta versions get an update notification for older versions. For example 1.1.0-beta gets a notification to upgrade to 1.0.0.

**Comment by Firebottle** [comment]
In the settings menu we could have an opt in for beta notifications. Otherwise only show for full releases.

**Comment by ThePerry-2015** [comment]
Can't this easily be resolved by checking for version < jsonVersion instead of version !== jsonVersion ? Until something is written for beta / full release options is in place?

**Comment by Firebottle** [comment]
Maybe! I'll try it. Also, I found this link which pulls in info on the latest release through the github api. This could eliminate the need for a json file at firebottle.tv. 

http://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo

**Comment by Firebottle** [comment]
Just committed a brand new version checker that uses the github api. We no longer need a json file and it automatically pulls the newest release info. There is a new setting on the settings page to opt into beta version notifications as well. 

In addition, there is a new settings page in the left nav. This page lists out info on the latest release along with a link to download it. The update notification directs to this page now.
