### ISSUE TITLE
Game Controls: Unable to press button error.

### ISSUE THREAD

**Issue by Kylix-Tyfurious** [Firebottle/Firebot#290]
#### Describe your issue or feature request:

I added a new button to my board called "Triggered" and checked it to be cooled down by other buttons, but it's not working. Any time you press any other button, Triggered doesn't go on cool down. I've tried restarting the board and resaving all the buttons, but nothing seems to be working. Triggered won't go on cool down from other buttons. Any ideas?

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?

4.0 Beta 5

- Have you tried the troubleshooting steps located on the wiki?

Yes.

- Are you able to reproduce the issue? If so, what steps did you follow?

Every time.

Edit any button I have > Add effect > Cooldown > check "Triggered" button > set to 60s > save

Press any button, "Triggered" button does not go on cool down.

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

https://drive.google.com/file/d/0B8Yo0Os_yTMsZ0JIM2tCbnZrUWM/view?usp=sharing

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

Done!

**Comment by Firebottle** [comment]
Have you tried a single button? Make one button cool down the other button and see if it works.

**Comment by Kylix-Tyfurious** [comment]
I'm actually having a lot of wonky issues right now with cool downs. I just realized tonight while trouble shooting that several of my buttons are not cooling down other buttons at random. I've even went in and removed the cooldown effect completely, saved it, then re-added the cooldown effect with buttons checked again. Some checked buttons are not cooling down even though they're being told to.

For example, if I tell it I want my "KO" button to cooldown "Freeze Controls", "Wow", and "Trumpet", only "Wow" and "Trumpet" will cool down... But I'll put the exact same settings on "Wow" and it will cool down everything?? It makes no sense.

**Comment by Kylix-Tyfurious** [comment]
Well, I think... _think_ I got everything working for my board properly at the moment, but there's definitely something going on with the way effects are being saved. I had to uncheck all, save and then recheck buttons and save again like 50 times to get it to do what it was being told. (It was also disconnected each time I made or saved any changes.) 

Hope that helps. If there's any other info I can provide that may be useful, let me know and I'll try to duplicate any steps I took.

**Comment by Firebottle** [comment]
What effects do you mean specifically? Is it only the cooldown effect that isn't saving correctly or are there others?

**Comment by Kylix-Tyfurious** [comment]
There may be others, but the only effects I use with any of my buttons are "Game Control" and "Cooldown" so that's all I can speak to.

I'm not sure if the "Error Pressing Button" issue is related to Game Control or something else, but it's still happening to me as well.

**Comment by Firebottle** [comment]
Yes, the error pressing button issue would be related to game controls. That would mean that you're passing over a value to the emulator that it's unable to recognize. Do you happen to know which button is causing this issue or is it all of them?

**Comment by Firebottle** [comment]
@Kylix-Tyfurious can you tell me if you're using robotjs or kbmrobot? Also, do you have an example of a key combination that is broken?

**Comment by Firebottle** [comment]
Could you try 4.0.2? We made some fixes for interactive controls.

**Comment by Firebottle** [comment]
I'm going to go ahead and close this as it's been a long time since they responded and we made some changes to game controls in 4.0.2. So, I'm going to assume this is fixed and a new bug can be created if it isnt.
