### ISSUE TITLE
Improve Fireworks effect.

### ISSUE THREAD

**Issue by fyrebug72** [Firebottle/Firebot#293]
#### Describe your issue or feature request:
Before I switched to the newest version of Firebot, the fireworks celebration worked fine although a bit slow. After I switched, it goes super slow and can only see one shot that goes up half way up from the bottom. I have the

 overlay set to OBS compatibility.

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?
Beta 5

- Have you tried the troubleshooting steps located on the wiki?
Yes

- Are you able to reproduce the issue? If so, what steps did you follow?
Yes. Problem persists throughout length of the session.

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

**Comment by Firebottle** [comment]
Fireworks are very cpu intensive. The speed will depend on your computer. Do you have a fairly decent machine?

**Comment by fyrebug72** [comment]
Yes. Brand new Ryzen 1600x. Smokin hot PC

**Comment by Firebottle** [comment]
Okay, we can look into it. We probably need to take another look at the Fireworks and see if we can simplify them a bit. Sometimes OBS and Xsplit have a rough time handling them at the moment.

**Comment by fyrebug72** [comment]
KK ty!

**Comment by Firebottle** [comment]
Revisited this and changed up the fireworks a bit. Hopefully they're a bit less resource intensive and a bit more visible. Will be available in the next release and I'll do some more testing then.

**Comment by fyrebug72** [comment]
TYVM

**Comment by Firebottle** [comment]
Released 4.1.0
