### ISSUE TITLE
ebiggz tasks

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#294]
- [x] - Need modal popup when new version of app is downloading. Ex: 3.0.0 to 4.0.0.
- [x] - Slider for auto update settings.
- [x] - Rework checkboxes to make them **_SEXY_** AFFFffffff

- [x] - ~~Deliver pizza on button press.~~ Scope creep
- [x] - ~~Guaranteed moon shoes after testing.~~ Scope creep
- [x] - ~~make sentient~~ Scope creep
- [x] - ~~make firebot into an MMO~~ Scope creep

**Comment by ebiggz** [comment]
EZ
