### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by BackdraftMixer** [Firebottle/Firebot#295]
#### Describe your issue or feature request:

Currently creating a soundboard for Mixer. I add any kind of cooldown to the sound, I can see the cooldown as the streamer profile for it's correct time BUT the audience and anyone not signed into my account sees the time at 4 hours or 6 hours or 8 hours

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running?

v3.4.1

- Have you tried the troubleshooting steps located on the wiki?

Yes

- Are you able to reproduce the issue? If so, what steps did you follow?

Performing normal operations
-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you
**1)** Please navigate to **/firebot/user-settings/controls** and attach the .json file of the board you are having issues with.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry). This allows us to more easily test your board. Thanks!

You're added!

**Comment by Firebottle** [comment]
Hello,

We believe this is an issue with Mixer. Could you report it at mixer.com/contact?
