### ISSUE TITLE
Import expected time?

### ISSUE THREAD

**Issue by wcphart** [Firebottle/Firebot#296]
Just downloaded 4 since 3.4.1 notified me about it. Clicked Import Boards and Settings. Its been 10 minutes. What is the expected time for the spinner to go away?

**Comment by Firebottle** [comment]
5 seconds. Did you use the button on the welcome popup to start the process?

**Comment by wcphart** [comment]
It appeared to have done the import, but the spinner did not clear. Maybe an issue w Mixer atm? Even trying to turn the board on never finished. Just rebooted and will retry, and if that doesnt work I will reauth the bot and myself in the app.

**Comment by wcphart** [comment]
That did not do it. Just spins after Clicking the red connect icon in lower left.

**Comment by Firebottle** [comment]
Can you go to your settings area and hit the button that opens up your root firebot folder. There should be a log folder in there with a file dated today. Can you attach that?

**Comment by wcphart** [comment]
No log folder there... uh oh. Just overlay and user-settings.

**Comment by wcphart** [comment]
Might add, I could not get the board to connect before updating either... Thats why I think its not the app but maybe mixer.

**Comment by ThePerry-2015** [comment]
Open the user-settings folder, should be a folder named logs in there.

**Comment by wcphart** [comment]
There is not. @Firebottle Its a slow night, want to see it while Im streaming? lol

**Comment by Firebottle** [comment]
Okay, if this was an issue from before 4.0 you need to attach your controls file to this issue so we can look at it.

**Comment by wcphart** [comment]
I deleted the last scene I created, and things have cleared up. No idea why that killed it. Sorry for the bother.
