### ISSUE TITLE
User groups not showing up

### ISSUE THREAD

**Issue by fyrebug72** [Firebottle/Firebot#297]
#### Describe your issue or feature request: I have created 2 new user groups, Mods and subs. When i add an effect to a scene change button, only the default, mods and none groups show up. I have closed and restarted sweveral times to see if that would fix the proble but it did not. thanks for you help

-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running? Might be an idea to update to the latest version to see if the issues has been resolved there before posting an issue if you are on an old version(4.0.0 is the latest).

- Have you tried the troubleshooting steps located on the wiki?
Yes

- Are you able to reproduce the issue? If so, what steps did you follow?Yes

-----------------------------------------------------------------------
#### If you are having problems related to your interactive board, there are two ways that you can help us help you, please do BOTH of these steps as it makes it a LOT easier to help you to investigate the issue.
**1)** Please navigate to **Settings -> Open Root Folder** Then open user-settings -> controls and attach the .json file of the board you are having issues with, as well as the **latest log file in the user-settings -> logs folder** put these files in a ZIP-file before attaching them.

**2)** Go to Mixer's Interactive Studio, click "Edit" on the board you are having issues with, click on the share icon beside the board name up top in the right corner of the page, choose "Only allow specific", and then add in our names (Firebottle, ebiggz, kateract, and ThePerry).
This allows us to easily test your board. Thanks!

**Comment by InstrumentalMixer** [comment]
I have the same issue

**Comment by ebiggz** [comment]
Groups will not show up for these buttons unless you set the groups to have one of the scenes as their default. 

You can assign default scenes for groups by clicking the little gear next to the board name on the interactive tab. 

When groups don’t have a scene set as their default, the group is considered “inactive” because if a viewer were to be switched to that group without a default, there would be no scene to show them. We are working on making this more clear for the user.

**Comment by fyrebug72** [comment]
TYTYTYTY
