### ISSUE TITLE
Video freezing after finishing.

### ISSUE THREAD

**Issue by ThisGuyTom** [Firebottle/Firebot#298]
Video freezes after effect is complete.
-----------------------------------------------------------------------
#### If you're reporting an issue please fill out the steps below:

- What version of Firebot are you running? Might be an idea to update to the latest version to see if the issues has been resolved there before posting an issue if you are on an old version(4.0.0 is the latest).
4.0

- Have you tried the troubleshooting steps located on the wiki?
I have no idea how to troubleshoot it.

- Are you able to reproduce the issue? If so, what steps did you follow?
The overlay file in both Xsplit and OBS from the Appdata/Roaming folder of Firebot have the same issue only for video. The gifs work completely fine as an alternative but can go offsync.

**Comment by Firebottle** [comment]
Could you provide some more information? Are you trying to youtube video functionality or are you going with a local video? 

What do you mean by "freezing? Does the video play and then literally freeze part way through? Does it play to the end and then just remain in the overlay?

Please be as descriptive as possible.

**Comment by ThisGuyTom** [comment]
Local videos play entirely through and then remain up in the overlay after finishing at the last frame completely frozen

**Comment by Firebottle** [comment]
Thanks! We'll take a look at it and try to get it fixed in the next release. Until then, you might try throwing it on youtube and going through that instead.

**Comment by Firebottle** [comment]
So... by chance did you leave the "How long should it show?" field blank? You need to put the number of seconds that you want the video to show in this field. If you leave it blank the video will show forever. 

![image](https://user-images.githubusercontent.com/17416635/28879280-5ca6bcdc-7767-11e7-8141-8bef182d3a18.png)

**Comment by Firebottle** [comment]
released 4.0.1
