### ISSUE TITLE
X to close popup windows doesn't work

### ISSUE THREAD

**Issue by UnknownTBeast** [Firebottle/Firebot#305]
#### Describe your issue or feature request (details are helpful!):

The "X" (to close window) does not work on the Add New Board popup window, or on the Add Group popup window

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.0.1

- What are the steps to reproduce the issue?
1)Interactive tab>Add Board>Click X to close
2)Viewer Groups>New Group>Click X to close
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

No boards were created, just a bug with the popup windows.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Released 4.0.2
