### ISSUE TITLE
Cant Connect.

### ISSUE THREAD

**Issue by faburocks** [Firebottle/Firebot#307]
#### Describe your issue or feature request (details are helpful!):
After the today auto update the bot is not connecting to Mixer. It shows as: Interactive Status: connecting... and nothing happens. I try to use an old version and it gives me an error and wont connect ether. 

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.0.1 (today new update)

- What are the steps to reproduce the issue?
1) open Firebot
2) press connect button 
3) needs to close the app because it gets stock on connecting and nothing happens 
[FireBot.zip](https://github.com/Firebottle/Firebot/files/1196011/FireBot.zip)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by SJForrest** [comment]
Same here. Can't connect not from 4.0.1, not from 3.4.1.

**Comment by faburocks** [comment]
Issue solve! I just got connected.
Thank you so much.
That was fats.
