### ISSUE TITLE
Board disconnects

### ISSUE THREAD

**Issue by barndawg14** [Firebottle/Firebot#31]
Whenever a button is pressed on my board that is successful and not tied to a spark cost(in dev lab) Firebot disconnects and I get error message: "Error setting up robot events in setupRobotEvents."  However, when I leave error message open, Firebot stays connected and board works fine.

**Comment by Firebottle** [comment]
Which version are you on? If you havent already, could you try one of the newer beta versions?

**Comment by barndawg14** [comment]
I am on v.1.0.0. Yeah, I can update that and send those to you.

**Comment by barndawg14** [comment]
[Pokemon.zip](https://github.com/Firebottle/Firebot/files/737186/Pokemon.zip)


Here are the user settings for the board I am having issues with. I upgraded to v.1.1.0-Beta 3 and instead of just giving an error message Firebot becomes "not responding" and I have to go into windows task manager to close the program.

**Comment by ThePerry-2015** [comment]
@barndawg14 : The cooldownButtons is filled with 13 in your file, what's the point of that value?
The cooldownButtons field is to assign which buttons that should be affected by the cooldown. The cooldown field is to assign the cooldown value, 0 and upwards are accepted in that field. Cooldown in seconds btw.

**Comment by barndawg14** [comment]
Because it has to have a value but I don't want any cool down on any of my buttons. So I assigned a random number so I could save the button.

**Comment by ThePerry-2015** [comment]
Well, as I said Cooldown Buttons should have the same ID as the button itself, not any random number. And the Cooldown lenght for the button should be 0 if you don't want any cooldown on it. So if you change those values around it should work just fine.

I've attached your file with the changes in it, try this and see how that works.
[Pokemon.json.txt](https://github.com/Firebottle/Firebot/files/737385/Pokemon.json.txt)

**Comment by Firebottle** [comment]
And thanks for reporting @barndawg14 obviously I should try to make the fields a little more obvious or account for having nothing in those fields. I'll put that on my list.

**Comment by Firebottle** [comment]
@barndawg14 can you try the newest beta again? I went in and set it up so you shouldn't need to put anything in cooldown or cooldown button fields. Hopefully that works better for you.

**Comment by barndawg14** [comment]
Yeah, I will try that out here within the next hour. :P Just finishing up some homework.

**Comment by barndawg14** [comment]
Okay I downloaded the newest beta and it works great! No more errors or crashing. Thank you so much Firebottle.

**Comment by Firebottle** [comment]
No problem! Glad it's working for you.
