### ISSUE TITLE
Login doesn't work. Version 4.0.1

### ISSUE THREAD

**Issue by SJForrest** [Firebottle/Firebot#310]
Hello I have a problem with log in. When I'm trying to login as bot or as streamer a white screen is appear.
[screen](http://prntscr.com/g3seeb)

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.0.1

- What are the steps to reproduce the issue?
1) Start the firebot
2) Open login manager
3) Try to login

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Hello, please follow step two in the troubleshooting steps of your message. Attach the log file if there is one. If not, let us know.

**Comment by SJForrest** [comment]
[2017-08-03.zip](https://github.com/Firebottle/Firebot/files/1197302/2017-08-03.zip)
This is my log file. The problem is still actual.

**Comment by SJForrest** [comment]
[video](https://youtu.be/A0DqF-byn5I)
A video with error.

**Comment by Firebottle** [comment]
Not sure what would cause that, but the error log did provide a cause. We'll look into it.

ERROR uncaughtException: Can't Load Database {"date":"Thu Aug 03 2017 08:13:15 GMT+0300 (RTZ 2 (зима))"

**Comment by SJForrest** [comment]
I thinks, that's because of зима it on cyrillic.

**Comment by Firebottle** [comment]
@SJForrest could you try running the app as an administrator just to test?

**Comment by SJForrest** [comment]
[2017-08-03.zip](https://github.com/Firebottle/Firebot/files/1198516/2017-08-03.zip)
Same problem. Just white window after login. :(

**Comment by Firebottle** [comment]
Hello! Could you try giving 4.0.2 a go? I should have fixed the issue where the white screen wipes the app. It might help us troubleshoot more.

**Comment by SJForrest** [comment]
[2017-08-04.zip](https://github.com/Firebottle/Firebot/files/1199448/2017-08-04.zip)
I tried 4.0.2 still the same, only white screen. No messages with errors. I tried with admin rights.

**Comment by Firebottle** [comment]
Okay, can you give 4.1.0 a shot? @SJForrest

**Comment by SJForrest** [comment]
Hello, after I reinstall Windows 10 everything working fine.
