### ISSUE TITLE
Feature Request - Run File

### ISSUE THREAD

**Issue by CrucialConnection** [Firebottle/Firebot#314]
I was wondering if a feature could be added possibly in the future to allow Firebot to run a file/application when I button is pressed.

**Comment by EarWaxCandy** [comment]
I got this to work using custom scripts. if you create a custom script with the following code it should work:

`function run(buttonId, username, modules) {
   
var spawn = require('child_process').spawn;

spawn('application.exe',['optional arguments']);
}

exports.run = run;`
