### ISSUE TITLE
Run AutoHotKey scripts - Feature Request

### ISSUE THREAD

**Issue by EarWaxCandy** [Firebottle/Firebot#324]
#### Describe your issue or feature request (details are helpful!):
Would be nice if I could just run an AHK script. currently Game Controls are being posted to the current window, if I could just say "run this ahk" then the controlsend commands in the AHK would be sent to the appropriate window instead of the window that is currently active.

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by EarWaxCandy** [comment]
was able to use this to run the autohotkey scripts through the custom script option

function run(buttonId, username, modules) {
   
var spawn = require('child_process').spawn;

spawn('C:\\Program Files\\AutoHotkey\\AutoHotkey.exe',['C:\\MyHotKeyScript.ahk']);
}

// Export 'run' function so it is visible to Node
exports.run = run;

**Comment by awrebels** [comment]
@EarWaxCandy which "effect" in firebot did you add your script - html?

**Comment by ThePerry-2015** [comment]
This is the Custom Script "effect"; https://github.com/Firebottle/Firebot/wiki/Writing-Custom-Scripts

**Comment by awrebels** [comment]
Did the most recent update fundamentally change the custom script function? I'm basically doing this exact thing to trigger an ahk program but it isn't working any longer after the update. Thoughts?

**Comment by ebiggz** [comment]
Can you elaborate on what isn't working? Are you getting an error?

**Comment by awrebels** [comment]
I don't get an error in firebot but if i try to run the js file directly i do get an error that exports is not defined. 

i'm using the same script as above to trigger an ahk program.Seems like the js is not being run.

**Comment by awrebels** [comment]
The script above was working for me previously - is there something else that needs to be running in order for it to work. I have node.js installed. It is likely i am forgetting a step that i previously completed

**Comment by ebiggz** [comment]
Looking into this, there appears to be a bug with custom scripts if the script doesn't provide any default parameters. We will get this fixed in the next update. 

For now though, this should hopefully work around the problem. Plus if there is still an error, it should display the error message in a popup. Before running the script make sure to click **Edit** on the button the script is attached to and click save. This will save the new unused parameter.

```javascript
function run(buttonId, username, modules) {
    return new Promise((resolve, reject) => {

        var response = {
            success: true
        }

        var spawn = require('child_process').spawn;

        spawn('C:\Program Files\AutoHotkey\AutoHotkey.exe', ['C:\MyHotKeyScript.ahk'])
            .on('error', function(err) {
                response.success = false;
                response.message = JSON.stringify(err);
            });

        resolve(response);
    });
}

function getDefaultParameters() {
    return new Promise((resolve, reject) => {
        resolve({
            "unused": {
                "type": "string",
                "description": "unused param",
                "default": "no need to put anything here"
            }
        });
    });
}

exports.run = run;
exports.getDefaultParameters = getDefaultParameters;
```

**Comment by ebiggz** [comment]
@awrebels Just to let you know v4.2.1 was released today and that bug should be fixed. You can now use the original script.

Also, the original idea to add "spawn" to the modules object was added in v4.2.1 so I will close this item.

**Comment by awrebels** [comment]
Awesome - your code worked great but I will update and test with the original function. Thanks and great work!

**Comment by ebiggz** [comment]
No worries! Glad it's working for you.

**Comment by reaperofpower** [comment]
I tried both scripts and no luck is there an update one I might find?
