### ISSUE TITLE
Changing "Port Number" in Firebot Doesn't Modify port.js file.

### ISSUE THREAD

**Issue by imjeeves** [Firebottle/Firebot#325]
When trying to change the Overlay Web Server port in Firebot, the port remains unchanged in "port.js."  The port for the application changes, but the Overlay continues to try to connect to the original port.

-----------------------------------------------------------------------

- What version of Firebot are you running?
4.0.2 (Fresh Install)

- What are the steps to reproduce the issue?
1) Close OBS
2) In Firebot, go to Settings -> Advanced
3) Changed Web Server port to "8081"
4) Closed Firebot
5) Reopened Firebot
6) Opened OBS with remote-debugging-port set
7) Connect to remote debugging port
8) click on Firebot overlay
9) Get messages that indicates it's still trying to connect to port 8080.  (Which means the application port changed but the code is still pointing somewhere else).
10) Open firebot-data/user-settings/overlay-settings/port.js
11) Websocket.Port still set to 8080.
12) Manually change Websocket.Port to 8081.
13) refresh the Debugging page
14) Debugger connects.

**Comment by ThePerry-2015** [comment]
Another Path-related issue, will be pushed with the next bug fix. Until then this will have to be changed manually within the port.js file as you found in step 10 in your list.

Thanks for the report. :)

**Comment by ebiggz** [comment]
Conveniently this has already been fixed and will be added to the next release.

**Comment by Firebottle** [comment]
Released 4.1.0
