### ISSUE TITLE
Can Not Add New Board

### ISSUE THREAD

**Issue by fyrebug72** [Firebottle/Firebot#328]
#### Describe your issue or feature request (details are helpful!):
Trying to add new Board. Created new board in studio. Tried twice

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.0.2

- What are the steps to reproduce the issue?
1)Create new Board in studio
2)Added new board to FIrebot
3)Get the swirly "working" symbol
[Fyrebug Zip.zip](https://github.com/Firebottle/Firebot/files/1207821/Fyrebug.Zip.zip)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by ThePerry-2015** [comment]
Left over file in controls folder, with a dotted name. Made it all go crazy while adding new stuff.
