### ISSUE TITLE
User Group Specific Buttons

### ISSUE THREAD

**Issue by mrmoviemaker88** [Firebottle/Firebot#330]
need help i try to find a way when i do a button cald mods set it to change scene i like if mod 1 press only mod 1 go to the mod buttons how do i do it ? 
sorry if i post in wrong place
for now if mod 1 press all mods go to mod buttons and if some mod press soundbord in mod buttons all mods go to the soundbord

**Comment by Firebottle** [comment]
You'll need to use the "change group" button. That button will change the person from one group to another and then they'll see the new scene. Everyone else will continue to see what they had before.

**Comment by awrebels** [comment]
@Firebottle how can the moderator change back though? I would kinda like the same thing: a board for mods only and then the default that they could go back and forth between at the click of a button

**Comment by Firebottle** [comment]
You make a copy of the default. Make a new user group called mod2 and
assign it to the duplicate default scene. The make buttons on each to
switch between the moderator group and mod2 group.

**Comment by awrebels** [comment]
Right that's what I was thinking was a workaround - however that technically is a different scene. Is there a way in firebot to copy buttons or copy scenes from one to the other? Or more over reference the same button in a different scene without manually recreating them? 

This is likely broaching a different topic but is it possible to put a viewer group filter or checker on a button? For instance the default board has a button only that while visible for everyone only functions for mods which could be used for this purpose.

**Comment by Firebottle** [comment]
It's been brought up enough that maybe we should go ahead and add it and just let the streamer deal with the questions if they wish. I'm trying to decide how often it'd be used due to the limitations.

**Comment by awrebels** [comment]
It'd be interesting, although it may not be possible, but if the buttons could be visible depending on the group the user belongs to. For instance the mods would see an extra little button to switch to their mod board but no other users would see said button. ¯\_(ツ)_/¯

**Comment by Firebottle** [comment]
Yeah, I wish that were possible. It probably will be later on if enough people suggest it to Mixer. Right now though everyone can see all the buttons on the scene. It's just up to the app to choose to do something with the button click or not.

**Comment by mrmoviemaker88** [comment]
if i do change group then ppl thet is noot mod can go to mods button :( 
> 
You'll need to use the "change group" button. That button will change the person from one group to another and then they'll see the new scene. Everyone else will continue to see what they had before. 
>

**Comment by Firebottle** [comment]
Correct, that will happen with the way you're trying to do it. I think we've decided that next release, 4.2.0, we're going to try to build in the thing you want.

A workaround is posted up this chain a bit. If you follow those four steps you can get things working. Otherwise you'll need to wait for the release.

**Comment by mrmoviemaker88** [comment]
Thanks did miss it :)

**Comment by ebiggz** [comment]
Released in v4.6
