### ISSUE TITLE
Video audio playback

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#331]
#### Describe your issue or feature request (details are helpful!):
Noticed a weird issue that audio (play sounds effect) will actually play through firebot however videos (show videos) still use the default device. Perhaps this is a limitation of audio router but it does seem to affect any videos. 

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Yep, sound effects play through the Firebot app. Videos play through the overlay.html file.

**Comment by awrebels** [comment]
And that should play out of the selected audio monitoring device within obs?

**Comment by Firebottle** [comment]
I believe so

**Comment by Firebottle** [comment]
I made a comment about this in the main feature request thread that would take care of the issue. Going to go ahead and close this one for now.
