### ISSUE TITLE
💻 Feature requests 🐈

### ISSUE THREAD

**Issue by sorryaboutyourcats** [Firebottle/Firebot#332]
Thanks for making another kick ass Mixer tool 'Firebottle and friends'.

I'd like to suggest a few ideas that might make things interesting if implemented.
Sorry in advanced if they've already been suggested though!

- Queue system for viewers to take turns - can change viewer control every X minutes.
   They would click 'Join Player X' and gain controls to a certain group when it's their turn.

- Event log written to a file, to be used as an OBS overlay.
   Ability to filter what gets written or not, like 'Only display viewers who hit the ATTACK button'.

- To avoid using my ghetto groups.json method, viewer groups should be written to separate files, 
   This way you can see which viewer is in which team (viewer group) via OBS overlay.

- An option for a button press to write the 'name of the viewer who hit it' to a file.
   Then we can initiate an onscreen alert like 'Billy2010323 hit the WTF button!'.

- Mods should be able to add and remove users from viewer groups.
   They should also be able to add and remove viewers to the queue.

If greater detail is needed or you're just wondering what the funk I'm talking about, let me know!

😺👍

**Comment by Firebottle** [comment]
1. Not suggested yet. Thanks!
2. Suggested, this would be per button. You'd add an effect to the button that writes a specific phrase to a text file.
3. Not suggested yet. Thanks!
4. Similar to suggestion 2.
5.

**Comment by Firebottle** [comment]
Oops. Hit the wrong button.

Thanks for the suggestions! We do want to implement some button to text file stuff for people to use in overlays.

**Comment by Firebottle** [comment]
I'm going to go ahead and close this and then re-opening anything we havent done as separate issues for visibility.
