### ISSUE TITLE
Cooldowns Dont Apply (Clock Sync Issue)

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#335]
There are instances where cooldowns will seem to not apply for certain people. This is because Firebot sends cooldown information based on the computer clock of the computer running Firebot. 

This causes situations where your clock is a minute behind everyone else and you're sending 30 second cooldowns. In this case the cooldown has already expired for everyone else and does not show.

To correct this, go to http://time.is/ and see if your clock is synced up. If it isn't, fix it. This goes for viewers seeing strange cooldowns as well.

**Comment by Firebottle** [comment]
We need to put in a check to see if the local time on the computer matches the external time of something like time.js. If it does not then we need to tell the user to set their clock.

**Comment by SinaCutie** [comment]
My time is synchronized and I can still trigger a button 2-3 times before the cooldown comes into effect.
