### ISSUE TITLE
Cant make 0 size buttons

### ISSUE THREAD

**Issue by OniShixx** [Firebottle/Firebot#339]
At first my issue was, I wanted to change the size of some of the buttons to act as more of a Header for a category of buttons.  After much headache I was able to essentially make buttons with 0 height( I'm unable to Make 0 height buttons again, I've tried every browser.)  I wish I could just edit the sizes in the JSON.

However, I accepted that I wasn't going to be able to make anymore 0 height buttons and decided to be happy with what I had.   Which I then noticed my present issue.  Only one of my buttons is clickable, even though they all have or had an effect attached.
-----------------------------------------------------------------------

Firebot version -
4.1.0

Steps taken-
1) I created a board, added it to Firebot
2) Added the play sound effect to 4-5 of the buttons on the board
3) Only one button works, the rest are gray and un-clickable.  I didn't notice any differences between the button that works and the ones that don't
4) Just to be sure I shortened the Button ID's of the other buttons and lowered the Spark cost to match.
5) Tried different Effects and File types.  Buttons remained gray/un-clickable.
6) I did try all of the troubleshooting steps.
7) Making a new board and starting fresh did seem to fix the issue.  But I can't seem to recreate the Header buttons(0 height/width)

[Omni1.zip](https://github.com/Firebottle/Firebot/files/1232915/Omni1.zip)

**Comment by Firebottle** [comment]
Hello, Firebot only supports what can be done via the Mixer Studio which follows the recommendations of Mixer. We don't support 0 height and width buttons.
