### ISSUE TITLE
Ctrl + Backspace conflict

### ISSUE THREAD

**Issue by FierySama** [Firebottle/Firebot#34]
Hey, FireBottle! I just wanted to say that I use Ctrl + Backspace every time I type. It actually deleted entire words at once and is a very helpful shortcut, especially when streaming and you need to type fast. Is there any way we can rebind this key to something barely used like Alt + Backspace? or Ctrl + Tilde, Alt + Tilde?? The program is looking super sweet already, and I can't wait to see more progress!

**Comment by Firebottle** [comment]
Sure. I'd like to set it up so it can be changed as well.

**Comment by Firebottle** [comment]
Fiery, the shortcut has been changed to ctrl+alt+f12. Hopefully that helps.

**Comment by FierySama** [comment]
Thanks FIreBottle! I appreciate the quick fix :)
