### ISSUE TITLE
gif display?

### ISSUE THREAD

**Issue by Tikkle** [Firebottle/Firebot#340]
#### Describe your issue or feature request (details are helpful!):

Im trying to make my buttons display a .gif file, but its only allowing .mp4 or an image

**Comment by ThePerry-2015** [comment]
A GIF is an image, so just add it as an image effect adjust the time you want it to show and it should be all good.

**Comment by Tikkle** [comment]
Do i use the Firebot overlay to get it to show on XSplit?

**Comment by Tikkle** [comment]
nvm, i figured it out, thanks for the help @ThePerry-2015
