### ISSUE TITLE
Feature Request: Connection options

### ISSUE THREAD

**Issue by ThePerry-2015** [Firebottle/Firebot#343]
Got a question the other day if it was possible to have an option for auto-connect on startup of the application.

**Comment by EarWaxCandy** [comment]
Along with this could there be an option to reconnect after a disconnect, or does that exist already and i'm just not seeing it. I have a board that runs on a 24 hour stream, and it disconnects regularly. would be nice if it could try to reconnect every x number of seconds.

**Comment by Firebottle** [comment]
FYI @ebiggz in the chat commands branch I've made modifications to the way the app connects so that interactive and chat are uncoupled from each other. If you tackle this issue you might do it in the chat command branch.

**Comment by ebiggz** [comment]
I don't even remember assigning myself to this. But I am happy to do it. I'll make sure to base the work off the command branch.

**Comment by Firebottle** [comment]
I think a better option for this is probably connections based on if the stream is active or not. It's very easy to hit the mixer api to get the status of a stream. So we could tie connects and disconnects directly to that.
