### ISSUE TITLE
will not log me in

### ISSUE THREAD

**Issue by jackkelland** [Firebottle/Firebot#344]
when I do the normal log in that the bot has when I log in with the pop up window nothing happens, it will not say that I have logged in 

fireboat v4,1.0

- What are the steps to reproduce the issue?
1) open fire bot
2) click log in from broadcaster or bot 
3) log in

**Comment by ThePerry-2015** [comment]
Via the Get started popup on first launch or via the Manage Logins up top right?
Direct Mixer login or via Microsoft, Twitter or Discord account?

I've just tested with my Mixer and my linked Microsoft account on my end and it seems to work just fine for both my Streamer and bot account.

**Comment by jackkelland** [comment]
there was no manage log ins on the top right but the top left and I tried that but did not work and trying the Microsoft one will not show up at all. (same with discord)

**Comment by Firebottle** [comment]
Please send a screenshot of what you're seeing when you try to log in.

**Comment by jackkelland** [comment]
![error](https://user-images.githubusercontent.com/31321957/29685122-638bd62a-890c-11e7-865c-a3fb783a3a05.png)
when I try to log in using Microsoft

**Comment by jackkelland** [comment]
![error2](https://user-images.githubusercontent.com/31321957/29685157-7ddbf10e-890c-11e7-9489-6fa94748e86a.png)
when I sign in from mixer using the pop up box it just sends me back here with nothing else

**Comment by ThePerry-2015** [comment]
You are on Version 3.4.1. Please update to 4.1.0 http://firebot.pro

**Comment by jackkelland** [comment]
o oops sorry
