### ISSUE TITLE
Feature Request: Hotkeys

### ISSUE THREAD

**Issue by RemixedLJ** [Firebottle/Firebot#345]
Hi there, I can't already see it so I can only assume it's not there, but, i'd like to be able to assign hotkeys to each of my buttons through FireBot, I use a Stream Deck and want to be able to activate the buttons using that which I could if I could assign hotkeys..

Is this already possible? Or does anyone have any suggestions?

Max

**Comment by ThePerry-2015** [comment]
There is hotkeys, check out the Game Control effect.

**Comment by RemixedLJ** [comment]
No I mean so I can press a hotkey to activate the button, not the other way around.

**Comment by ThePerry-2015** [comment]
Oh, the other way around, yeah, that's not in Firebot so I'll mark it as a feature request.

**Comment by ebiggz** [comment]
Beginning work on this in the `hotkeys` branch.

Goals:
- [ ] new "Hotkey" tab that will let the user define hotkey combinations and then either trigger effects from a button, a command, or create a custom list of effects. 
- [ ] add two new effect types: "Connect To Service" (with checkboxes for Interactive and Chat), and reversely "Disconnect From Service" with same options. This will let us recreate the current hardcoded hotkeys for connecting Interactive and Chat. It will also allow the user to customize the default hotkeys for or even set up mod commands/buttons for this behavior.

**Comment by Firebottle** [comment]
Did you finish this up or is there more work needed?

**Comment by ebiggz** [comment]
Whoops, this was finished. Released in v4.9
