### ISSUE TITLE
Soundboard cooldown problems

### ISSUE THREAD

**Issue by snipe86k** [Firebottle/Firebot#346]
#### Describe your issue or feature request (details are helpful!):
I am writing for possible insight on an issue I am having with the soundboard. I have been using soundwave interactive and for some time it has been working well. But the last 6 or 7 streams every button has been overridden with a 1h cooldown instead of a few minutes as I have them set in the software. I have tried to delete the whole editor profile on mixer and redo it. I have also now switched to firebot, and again deleted the profile on mixer starting again fresh and every time I have this 1h preset cooldown thing persists through any attempt I try to resolve it. with this switch to firebot I have also blocked out and uninstalled soundwave interactive. Please let me know if you guys have any thoughts.

The message above I sent to you months ago and I was told that it wasn't firebot. Mixer says they have no control of cooldowns. I have been using it with this issue now for months. Today I uninstalled all firebot and associated folders I installed the newer 4.1.0 . I created another new board on mixer to ensure all was completely fresh. In the testing process, I would start the bot and go to my channel clicking all buttons on the page before moving to the next. and repeating this process. also trying to switch as many pages as possible. About the time I get through all pages it freezes up and shows no cooldowns. I then refresh the page and nearly every button is on a one-hour cooldown. Something is wrong here and I have no idea what.

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.1.0

- What are the steps to reproduce the issue?
1)Turn the bot on
2)Go to the stream and click multiple buttons
3) eventually it wont show cooldowns until a refresh and then everything is on a 1 hour cooldown.

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
[Firebot soundboard.zip](https://github.com/Firebottle/Firebot/files/1254783/Firebot.soundboard.zip)

2) In **user-settings > logs**, find the latest log file.
[2017-08-27.zip](https://github.com/Firebottle/Firebot/files/1254782/2017-08-27.zip)

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by snipe86k** [comment]
Also If I restart the bot it then seems to work fine until too many buttons are pressed again and it locks up again.

**Comment by snipe86k** [comment]
I was just messing with it more thinking that maybe if I attached some of the buttons with an additional cooldown maybe that would solve the issue.

Steps:
1. discconnect bot
2. reconnect bot
(Steps 3-7 are within a few seconds of one another)
3. On stream click to transfer from sub only page to default.
4. Click aaalrighty 
5. click Nasty
6. click Nooo!
7. Click Blame
(Button Nasty on 1h instead of 60 sec cooldown.)

I attempted to make this occur for a second time in a row and it would not happen again.

**Comment by snipe86k** [comment]
I have it to where it seems to work fine for me but when a viewer tests it. it gives a 2 hour cooldown.

**Comment by Firebottle** [comment]
Hello,

Mixer cooldowns are based on your computers time. For example, if I am a minute behind on my computer and I send a 30 second cooldown, most people will not see it. This is because that time is technically already over.

Go to time.is and make sure your clock is synced up to about 1-2 seconds of real time. If your viewers are seeing the same thing, try this with them as well.

Firebot is sending cooldowns correctly. However, this time thing could cause people to see different cooldown amounts.
