### ISSUE TITLE
API Buttons -> Talk as bot or Streamer

### ISSUE THREAD

**Issue by ThePerry-2015** [Firebottle/Firebot#35]
The last beta(which btw has the wrong version # in package.json so it still says there is a new update) adds the option to post things to chat as the bot or the streamer based on settings, but at the current version it seems to chose bot/streamer on random instead of based on setting. I have setup one button with API Buttons -> Advice and set it up with Bot as chatter. When button is pushed it chats as bot or streamer, next time I connect it can be the other one. So it seems like somewhere in the code it mixes up pr connection. 

Sometime the log outputs
`Logged into chat as Bot`
`Logged into chat as Streamer`

And other times vice versa:
`Logged into chat as Streamer`
`Logged into chat as Bot`

Not sure if the order it connects has something to do with this, since it seems that even if it says bot last it still post as either one of them even if the button is set to Bot. Just thought I should mention it.

Added a log line into apiProcessor.js at line 32:
`if(apiType == "Advice"){`
`			randomAdvice(chatter);`
`			console.log("Talking as: "+chatter);`
`		}`

To see who the app itself thinks he is posting as, and as the board setting is set to Bot the variable chatter = bot according to the log
`Talking as: Bot`
But still it posts to chat as the Streamer so something isn't obeying the chatter setting later on in the code.

And I still have some issues with #30 now and then, specially if I add more than 2 cooldownButtons in the button settings. Just to mention that.

**Comment by Firebottle** [comment]
This should be fixed in the most recent commit.
