### ISSUE TITLE
Feature Request: Add ability to copy/paste/delete all effects in edit button modal

### ISSUE THREAD

**Issue by ebiggz** [Firebottle/Firebot#356]
I've seen some folks asking if its possible to copy the effects from one button to another. This would be a super easy addition that I'd like to do. 

Thinking of having a button, in the location shown below, that will have a drop down of actions: copy, paste, delete all.

![image](https://user-images.githubusercontent.com/3515161/30456741-afa2285e-9959-11e7-9b56-98b66bc15cdb.png)

**Comment by ebiggz** [comment]
This is dev complete and ready for 4.2.0

**Comment by Firebottle** [comment]
Released in the dank update 4.2.0
