### ISSUE TITLE
Feature Request: Notifications to Users

### ISSUE THREAD

**Issue by ebiggz** [Firebottle/Firebot#357]
It would be great to implement a way for us to be able to send notifications to Firebot users that they would see when opening the app.

This would be useful for when a new known issue pops up and we want to let everyone know we are aware.

**Comment by ebiggz** [comment]
I have begun work on this. I think for now we can have a json file in github we can refer to but we could always expand this at a later time.

**Comment by Firebottle** [comment]
Released 4.4.0
