### ISSUE TITLE
Sound lag in Firebot

### ISSUE THREAD

**Issue by Dianthus85** [Firebottle/Firebot#362]
#### Describe your issue or feature request (details are helpful!):
Soundboard lagging
I have tried re-doing the O-Auth, (deleting the authorisation on mixer beforehand)
Uninstalling and re-installing Firebot
Changed the control Emulation bot.
Re-adding the link for firebot into XSplit

Everytime I start up the board the sound lags and whenever a button is pressed it jitters the sound.

Not sure where to go from here. Not that it should matter but the sounds are on the same SSD as Firebot. Even on the test it lags by the way before I even load it up to mixer! I have also tried re-adding the sound/s to Firebot.

Is there a piece of software that is a known issue for Firebot to work with that I should disable?

Thanks in advance.
-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
v4.2.2

- What are the steps to reproduce the issue?
1) Unknown....
[2017-09-19.zip](https://github.com/Firebottle/Firebot/files/1315520/2017-09-19.zip)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
This will happen if your CPU is maxed out. Your CPU isn't giving enough resources to Firebot to process everything.

**Comment by Dianthus85** [comment]
CPU isnt maxed, its only using 50-60% while PUBG is running :)

**Comment by Firebottle** [comment]
50-60% with PUBG, streaming software, and firebot running? Have you tried going into windows and giving higher cpu priority to Firebot? Do you run any additional sound related software such as voice meter? Has it always behaved like this or did it start recently?

The only other time I've seen audio stuttering happen is when I upped my volume to 1000% in testing.

**Comment by Dianthus85** [comment]
Yeah it worked before 2 updates ago. Since then it hasnt worked at all. Nothing really only my STRIX

**Comment by Firebottle** [comment]
Well, we haven't changed how the audio is played in a very long time. The last two updates haven't adjusted the audio at all, but they have added new features which might use a bit more cpu.

I'll wait and let @ThePerry-2015 and @ebiggz chime in when they get a chance. I can't think of a reason for distortion other than CPU which you've mentioned is not the reason.

Try setting the cpu priority for Firebot higher in windows just to try it out.

**Comment by Dianthus85** [comment]
Ok even with XSPLIT not running, and no game it still lags so its really not the CPU :( 

It really seems like a compatibility issue.

**Comment by Firebottle** [comment]
Could be. For example, I could probably get it to distort pretty bad if I went in and made some voicemeeter adjustments. So it could be an issue with the sound setup and how audio is getting routed too. Though that wouldn't produce any type of lag.

**Comment by Firebottle** [comment]
@Dianthus85 please try 4.4.0 and see if you're still having the issue.

**Comment by Firebottle** [comment]
closing due to no response in over a week.
