### ISSUE TITLE
[Feature Request] - Internal web-server for streaming overlays

### ISSUE THREAD

**Issue by ThePerry-2015** [Firebottle/Firebot#369]
#### Describe your issue or feature request (details are helpful!):

Moving all overlay support over to an "internal web server" inside Firebot to get around issues with file paths and local/remote paths that we keep getting with different Broadcaster software, specially local file paths for OBS and copy & paste file paths in XSplit. This will also make it easier to setup Multi PC Stream setups since it wouldn't require the bot to be running on the stream or gaming machine depending on this and that setup it could be ran on one dedicated machine and just pointing the overlay via a local URL instead of file path.

A bit badly explained, but just to get my idea written down so I have it for future reference.

This might also open up for moving the sound effect over to the overlay instead of playing it inside Firebot like today.

**Comment by Firebottle** [comment]
Released 4.4.0
