### ISSUE TITLE
"waiting for the game to be ready.." Continuous connecting. 

### ISSUE THREAD

**Issue by TastyLemons** [Firebottle/Firebot#370]
#### Describe your issue or feature request (details are helpful!):

Receiving a continual 'connecting...' on firebot, and a 'waiting for the game to be ready..' on the interactive portion of my mixer. Updated the firebot today from a v3, and then made some updates to the board itself with some buttons and such. 

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
v4.2.2

- What are the steps to reproduce the issue?
1) Open bot, and attempt to connect to mixer. 

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

[Lemon Sound Board.zip](https://github.com/Firebottle/Firebot/files/1330846/Lemon.Sound.Board.zip)

No, logs currently in the new version folders. 

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
[Lemon Sound Board Edit.zip](https://github.com/Firebottle/Firebot/files/1330973/Lemon.Sound.Board.Edit.zip)

Try this one. Made a few changes.

**Comment by TastyLemons** [comment]
That seemed to do the trick! Much appreciated!
