### ISSUE TITLE
Filterable Effects Lists

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#371]
Right now we have all effects in a dropdown menu, but as that list gets longer it gets harder to use. We need to convert this dropdown menu to a filterable list. The filters would be based on the dependency for that effect, for example "Interactive" would show all effects that require interactive connection.

**Comment by ebiggz** [comment]
I've been making progress on this. Should have the change complete by EOD today.

**Comment by Firebottle** [comment]
Released 4.4.0
