### ISSUE TITLE
Switch out updater for Electron Updater

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#375]
Change out our current updater with a new one that is better supported and allows for different OS support. Also provides more features and progress bars.

https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater

Covered issues with change:
#306

**Comment by ebiggz** [comment]
Looking into this.

Referring to this example here:
https://github.com/iffy/electron-updater-example

**Comment by Firebottle** [comment]
Taking this out of the milestone. And just for the notes: the issue with implementing this is that it requires a new builder as well which works in conjunction with the updater.
