### ISSUE TITLE
Board Not Updating At All

### ISSUE THREAD

**Issue by DoctorSoup143** [Firebottle/Firebot#383]
#### Describe your issue or feature request (details are helpful!):
I simply can't do anything because the board wont't update. At this point i can't even add a board...

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.3.0

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
What board number are you trying to add?

**Comment by Firebottle** [comment]
No response for 5 days. Closing this issue. If you're still having problems please open a new issue.
