### ISSUE TITLE
Cooldowns are no being shown properly to all users

### ISSUE THREAD

**Issue by Mortanos** [Firebottle/Firebot#384]
#### Describe your issue or feature request (details are helpful!):
Cooldowns are not being applied consistently and accurately to all user!
User A might press a button and see a cooldown, but user B will not and  be able to click the button
Also had instances where one was able to spam press a button or multiple with no cooldown

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
v4.3.0

- What are the steps to reproduce the issue?
1)Press a button on my soundboard
2)Press it again
3)and then again
[reportfile.zip](https://github.com/Firebottle/Firebot/files/1360155/reportfile.zip)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Went through some troubleshooting to try to fix this and hit a dead end.

I appear to be seeing cooldowns just fine, but Mortanos is not. When running his board in our dev environment I see that all of the buttons are being sent to cooldown correctly. I also only see a single button press, but Mortanos is reporting that people can spam the buttons and they all activate.

So, I had him check his chrome console to see if he was getting a "user may not interact with disabled controls" error. He said he does not get that error at all, Instead he gets a "user doesnt have enough sparks" error.

**Comment by Firebottle** [comment]
Please try 4.4.0 and see if you're still having the issue.

**Comment by Mortanos** [comment]
I have done the update, and I'm still having the issue. I don't know of
it's a coincidence if that the cooldowns work for the on dash board but not
off dash. Not entirely sure what is happening, but when I also attempt to
ban the user from spamming the board, they can still spam :/

**Comment by Firebottle** [comment]
Just ban them from your entire channel. A full on ban will remove the interactive piece for the user.
