### ISSUE TITLE
Automatic Button Cost/Decrease

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#385]
We should add an option to buttons to automatically increase and decrease it's cost based on how often it is used. For example, if someone clicks a button the cost goes up by 50 sparks. But, every minute that same cost drops by 10.

**Comment by eaaliprantis** [comment]
Which for this to happen, you would have to add a minimum requirement so that it doesn't go down to 0 if someone was not using it

**Comment by ebiggz** [comment]
This is partially implemented with the "Update Button" effect and its expression parser. Only thing that doesnt happen is the cost decrease overtime.

**Comment by Firebottle** [comment]
Going to go ahead and close this one. It was a random idea I had, but I think with the update button effect people are happy.
