### ISSUE TITLE
Button queue?

### ISSUE THREAD

**Issue by PieRatKing** [Firebottle/Firebot#387]
#### Describe your issue or feature request (details are helpful!):

Not sure if this has been thought of, or brought up, but a command queue would be advantageous. I may have missed it, but I have two sets of cool down groups right now, the problem is when one button from one set gets pushed, and someone immediately pushes one from the other set it takes away from the experience of the first button, and even the second. Some of my interactive features I put a lot of time and effort into. But if there was a way to queue the commands as so they don't mesh over each other I feel it would keep the quality of the interactive board. Of course simplest way would be to do a global cooldown, but not all buttons are the same.

Thanks for your consideration,
PRK

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Thanks for the feature request!

There are definitely times when you'd want something like this, but also there are times when you'd need buttons to be spam-able. So we'd need to build a separate optional queue system to get this in place.

**Comment by PieRatKing** [comment]
Oh yes, I meant to add that as well, but thanks for your response, and consideration, keep up the great work on this amazing piece of utility.

**Comment by Firebottle** [comment]
Hello,

This can now be done using the "Update Button" effect combined with a delay.

- "Update Button" and make it disable all other buttons.
- "Delay Effect" and wait for the period of time it takes to complete the sounds/images.
- "Update Button" and make it enable all other buttons again.

**Comment by PieRatKing** [comment]
dude thanks a ton, you are awesome!!!
    On Tuesday, January 16, 2018, 8:50:00 AM CST, Firebottle <notifications@github.com> wrote:  
 
 
Hello,

This can now be done using the "Update Button" effect combined with a delay.
   
   - "Update Button" and make it disable all other buttons.
   - "Delay Effect" and wait for the period of time it takes to complete the sounds/images.
   - "Update Button" and make it enable all other buttons again.
