### ISSUE TITLE
Dark theme text not visible in some areas

### ISSUE THREAD

**Issue by cbrookins** [Firebottle/Firebot#388]
#### Describe your issue or feature request (details are helpful!):

Cannot see text in Enter/Exit Animation drop down menu when using Dark theme.

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.3.0

- What are the steps to reproduce the issue?
1) Enable the Dark theme
2) Add a Show Image or Show Video action
3) Observe the Enter/Exit Animation dropdown

**Comment by Firebottle** [comment]
Hello @cbrookins thanks for the report. We'll have this fixed in the next release.

**Comment by Firebottle** [comment]
Released 4.4.0
