### ISSUE TITLE
app fails to log in?

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#389]
#### Describe your issue or feature request (details are helpful!):

I seemed to lose auth for streamer and bot this morning when starting up. I am now trying to log in again streamer and bot and it just hangs on a spinning loading circle; which never completes. 

Is this a known issue or problem with my install perhaps?  

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1) open firebot
2) login accts are not auth
3) click manage logins
4) use streamer auth to login to streamer
5) loading spinning circle goes continuously 
-> also tried doing bot login first. does not working either.  

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by awrebels** [comment]
FIXED: I identified the issue by deleted user-content first and then deleted auth.json and reauthed. All good now.

**Comment by Firebottle** [comment]
Sorry about the trouble! I was just about to recommend that same thing. Will close this issue.
