### ISSUE TITLE
Filename issues with new boards

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#390]
Had a user that tried to create a new board with the name: -=[THE RETRO ARMY]=- | -=[INTSBMOD-400]=-

Firebot tries to use the board name as the file name for the controls. In this case it tried to create the file, errored out because it was not a valid windows filename, and didn't throw any error.

We need to throw errors if the board name is not a valid filename.

**Comment by NightmareJoker2** [comment]
Really? You don't have at least a `filename = filename.replace('/', '／').replace('|', '_').replace('\\', '＼').replace('?', '？').replace('"', '\'').replace(':', '：');` in there somewhere? :)

**Comment by Firebottle** [comment]
Heya! Thanks for your input! I think... Not sure if you're making a joke or being demeaning.

Anyway, using the name of the board for the file name seemed like a good idea at one point because it made it easier for users to find the json file for the board. It still comes in handy today when working support. We've already discussed moving to IDs. No idea if or when that will be added.

**Comment by NightmareJoker2** [comment]
Neither, just color me surprised. I'd expect a file I/O framework to already do this for you (if you're using one) or you to be aware of which characters aren't allowed for filenames (and/or the board names) or reserved names. They are well documented: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx (Linux and OSX compatible file systems only disallow a subset of these)

That being said, you should always use a value you can reliably know to be unique when storing things in the file system, and board names do not qualify that criteria at all... ;)

PS: always assume your users will do something to break things :P
