### ISSUE TITLE
Suggestion: Add "Random" to "What location should it show in"? for Videos/Images

### ISSUE THREAD

**Issue by TVCalico** [Firebottle/Firebot#393]
#### Describe your issue or feature request (details are helpful!):

I think it'd open up a lot of interesting interactions to add "Random" to the "What location should it show in?". You randomize the positions you have currently (IE: Middle, Left, Top Middle, ETC) so that users can have the image or video appear on random parts of the screen in lieu of a set location.

**Comment by ebiggz** [comment]
This has been released in v4.5
