### ISSUE TITLE
Cool down

### ISSUE THREAD

**Issue by pdubpolarbear11** [Firebottle/Firebot#394]
#### Describe your issue or feature request (details are helpful!):
I am having a cool down issue. If you press one button and then quickly press another one it will fire both of them even though I have every thing set to be on a cool down right after any button is pushed. When I look at the event log is says ____ tried to press the ____ but it was on cooldown. But it still fires off. 

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

v4.3.0
- What are the steps to reproduce the issue?
1) press one button
2) then press another one quickly before the cooldown shows up
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.
[logs.zip](https://github.com/Firebottle/Firebo
[logs.zip](https://github.com/Firebottle/Firebot/files/1381018/logs.zip)
t/files/1381017/logs.zip)

```
NOTE: A lot of issues can be solved by,
- Updating to the latest versio
[logs.zip](https://github.com/Firebottle/Firebot/files/1381019/logs.zip)
n
[Pdubpolarbear11.zip](https://github.com/Firebottle/Firebot/files/1381022/Pdubpolarbear11.zip)

- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
We can take a look and try to reproduce the issue. Looking at the code, the only time that event is shown in the log is if the button does not fire. 

But, it could be that someone is clicking it more than once. The first one fires, and then the others display the message. So we'll take a look and see if we can reproduce the problem with some auto clickers or something.

**Comment by Firebottle** [comment]
Please try 4.4.0 and see if you're still having the issue.
