### ISSUE TITLE
Feature Request: Reordering Effects

### ISSUE THREAD

**Issue by Machiezmo** [Firebottle/Firebot#395]
It'd be cool to be able to reorder effects.  I made some interactive buttons once that did hotkeys but decided I wanted a sfx alert and then a delay then the hotkey and I had to remove the hotkey effect to be able to add sfx then delay then hotkey.

**Comment by ebiggz** [comment]
This feature has been implemented in v4.5 Beta 3.

**Comment by ebiggz** [comment]
This has been officially release in v4.5
