### ISSUE TITLE
Notification Area for Dark Theme

### ISSUE THREAD

**Issue by Machiezmo** [Firebottle/Firebot#396]
#### Describe your issue or feature request (details are helpful!):
Notification area for dark theme is hard to read...well impossible.  If you click on it you can read just fine.

https://gyazo.com/ebb872b8bb14680ab536cc1944008986

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.4.0

- What are the steps to reproduce the issue?
1)Click the bell

**Comment by ebiggz** [comment]
This has been fixed in 4.4.3
