### ISSUE TITLE
Custom scripts no longer seem to fire

### ISSUE THREAD

**Issue by platypusmuerte** [Firebottle/Firebot#398]
Button with action "Custom Script" that points to a JS file matching the example at https://github.com/Firebottle/Firebot/wiki/Writing-Custom-Scripts#effects do not fire the chat message.

Please advise, and Happy Saturday!

The cooldown is triggered, and the click shows up in Moderation log, though no errors, also it seems the code wrapper here doesn't like me lol

`
function run(runRequest) {
  // Return a Promise object
  return new Promise((resolve, reject) => {
    var buttonId = runRequest.buttonId;
    var username = runRequest.username;
    

   
    var response = {
      success: true,
      errorMessage: "Failed to run the script!",
      effects: [ 
          {
              type: EffectType.CHAT,
              message: "Hello chat!",
              chatter: "Streamer"
          }
      ] 
    }

    
    resolve(response);
  });
}

exports.run = run;
`

**Comment by platypusmuerte** [comment]
Would like to add that setting success: false above, does trigger the notification in Firebot. So the script is getting called, its just not... doing things.

**Comment by Firebottle** [comment]
When we added in chat commands we added a "type" to the effectsPacket the backend passes around. Doesn't look like we caught this for custom scripts and it leaves out the type. This causes it to thing it's neither interactive or a chat command and doesn't run.

**Comment by Firebottle** [comment]
Fix is in the dev repo and ready for patch.

**Comment by Firebottle** [comment]
Should be fixed in 4.4.1
