### ISSUE TITLE
Cant Click

### ISSUE THREAD

**Issue by BytorMixer** [Firebottle/Firebot#402]
#### Describe your issue or feature request (details are helpful!):

Hello Firebottle, I am having a problem, Me and my viewers cant click the sounds, the scene switch (social) button works, but when they click on the discord button it doesnt work at all, and i have it set to bring up a chat message as well, so pretty much all interactive stuff except for the scene switcher doesnt work

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.4.1

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Hello, please attached your controls.json file to this ticket so we can take a look and test it out.

**Comment by BytorMixer** [comment]
ok, i got the buttons to work but the scene switch  doesnt work now, here is the controls i will retry everything after this update and it doesnt support .json files, ill retry with a different comment

**Comment by BytorMixer** [comment]
it still wont let me send the controls file over, is it my (boardname).json or is it something else

**Comment by BytorMixer** [comment]
I got the sounds to work but not the scene switcher

**Comment by BytorMixer** [comment]
it seems like the problem is every now and then, sometimes they all work sometimes just the sounds work, and sometimes nothing works

**Comment by Firebottle** [comment]
Attaching json for bytor.
[Interactive_Stock.zip](https://github.com/Firebottle/Firebot/files/1387499/Interactive_Stock.zip)

**Comment by Firebottle** [comment]
@BytorMixer are you still having an issue with this?
