### ISSUE TITLE
Overlay issues

### ISSUE THREAD

**Issue by stryd3r50** [Firebottle/Firebot#403]
#### Describe your issue or feature request (details are helpful!):

I replaced the old overlay address with the new one and now none of my gifs and videos both dont play

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by ebiggz** [comment]
Hi @stryd3r50 !
There are two reasons they may be causing this:
1) You have the overlay open in multiple places (ie in OBS/Xsplit) and in a browser (ie Chrome/Firefox)
2) Your broadcasting software was opened before Firebot and it is set to cache webpage sources. 

If 1, simply close the overlay in your browser and try again. We will have an update soon that will resolve this problem. 

If 2, make sure the browser/webpage source for the overlay in your broadcasting software is set to clear it's cache on scene change (you can do this in obs, not sure about xsplit). OBS also has a clear cache button if you open up the browser source settings. Alternatively just make sure firebot is open before the broadcasting software is started.

**Comment by ebiggz** [comment]
Hi @stryd3r50 
Please try 4.4.2 and see if your problem is resolved.

**Comment by Firebottle** [comment]
going to close this due to no response in over a week.
