### ISSUE TITLE
Local videos only play once.

### ISSUE THREAD

**Issue by Uriei** [Firebottle/Firebot#404]
#### Describe your issue or feature request (details are helpful!):
When I set buttons to play a local video, they only play once, and only the first one used, after that first local video, it doesn't play another, ever, until, I think, a whole computer restart, restarting Firebot, OBS, whatever, doesn't seem to fix it.

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.4.1

- What are the steps to reproduce the issue?
1) Add a Play Local Video effect
2) Run it.
3) Try to run it again.

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
[Uriei Soundboard.zip](https://github.com/Firebottle/Firebot/files/1387311/Uriei.Soundboard.zip)
The button in question is `"controlId": "Test"`
2) In **user-settings > logs**, find the latest log file.
**No logs.**
-----------------------------------------------------------------------
Also with OBS debug mode I get this everytime I click on the button.
![image](https://user-images.githubusercontent.com/6078221/31613133-70449d58-b282-11e7-9b9b-2a13e98053cf.png)

**Comment by Uriei** [comment]
4.4.2 seems to have solved this issue, I'll keep trying this ;)

**Comment by ebiggz** [comment]
Hey @Uriei 

Thanks for the awesome and thorough bug report, one of the best I've seen here!

4.4.2 should indeed resolve your issue. Previously in 4.4.0 and .1, there was an issue if you had the overlay open in multiple places like your broadcasting software (ie in OBS/Xsplit) and in a browser (ie Chrome/Firefox). The cause for that issue may have caused a similar symptom in other cases too. Either way that root problem was resolved. 

Let us know if you run into any other issues.

**Comment by Uriei** [comment]
No problem, I always try to make things clear so it can be solved quicker ;) GJ
