### ISSUE TITLE
Canal de voz (discordia)

### ISSUE THREAD

**Issue by RicardoArturo** [Firebottle/Firebot#407]
Create a (Play) button to place in Mixer and listen (X) Discord channel.

When you broadcast your screen and you are playing with other friends that occupy your Mixer channel, they are heard twice.

I can divide the output of adudio and my colleagues who play in my channel are heard in my headphones while I only transmit what goes on the screen.

But the problem with that is that viewers can not listen to those who are playing with me through Mixer.

The button would be so that the person who transmits only transmits the audio of the game and the spectators use the vox of (Play) to be able to listen to the other people who are playing with me and Discord.

I hope you understand and see it useful and above all can be done :)

**Comment by Firebottle** [comment]
If you haven't already, I recommend downloading Voicemeeter Banana. This will give you better control over your audio sources and where those get routed.

**Comment by RicardoArturo** [comment]
it does not help me, Those who play with me using discord occupy watch and hear what I transmit in MIXER.

The viewers alike.
The difference is that the others play using buttons that I have implemented but they listen to themselves and if I cancel that audio the viewers no longer listen to those who are playing.

**Comment by eaaliprantis** [comment]
As what Firebottle suggested, use Voicemeeter Banana.  It can help with
your audio issues that you are having.

**Comment by ThePerry-2015** [comment]
I'm not quite sure what you are trying to achieve..
But I think you want to make it possible for the ones in your Discord to listen to the sounds played from Firebot over discord? So they don't need to listen to your stream as well just to hear interactive sounds?

**Comment by RicardoArturo** [comment]
I want the viewers to listen to both the players and all the content of the game.

and players play using only my Mixer channel using discord to cast them

It is a role playing game

**Comment by RicardoArturo** [comment]
I already saw how to solve it, in discord there is a bot that allows me to transmit audios via Discord, this so that the players can cancel the audio of my Mixer Channel and thus not be heard twice
