### ISSUE TITLE
 we skipped over due to dependencies.

### ISSUE THREAD

**Issue by pdubpolarbear11** [Firebottle/Firebot#409]
#### Describe your issue or feature request (details are helpful!):

I am trying to set up commands for just the chat and I keep getting this for any of my buttons that are just chat. System: (Song request) has an effect we skipped over due to dependencies. Song request is the button I am referencing 

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.4.2

- What are the steps to reproduce the issue?
1)set up button with just chat
2)push button with just chat

3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
If you have an interactive button that is trying to use the chat effect, you need to be connected to chat.

**Comment by Firebottle** [comment]
Going to close this due to no response in over a week.

**Comment by pdubpolarbear11** [comment]
Thank you
