### ISSUE TITLE
Volume control for the Connection notification sound

### ISSUE THREAD

**Issue by Uriei** [Firebottle/Firebot#411]
Someone asked me for this and I think it's a good idea, a volume control for that really loud sound when Firebot connects and disconnects, because for now it's just a really deafening sound or no sound at all, now, if the feature request #410 gets done, this could be less than an issue, but would still be nice.

**Comment by Firebottle** [comment]
FYI, in the latest releases we knocked the volume down by more than half as a temporary solution.
