### ISSUE TITLE
Keystroke for chat interactive on/off? 

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#412]
#### Describe your issue or feature request (details are helpful!):
Is there a keystroke to turn that on as well or perhaps an option to turn both on with single keystroke?

Also i noticed a weird problem where my custom groups don't show up for users unless I enable chat interactive and turn on and off regular interactive. 

It seems to happen only at the beginning of the stream and doesn't persist if i turn off&on the interactive buttons 

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Yes, chat needs to be on for firebot's auto grouping to work.

I believe the keystroke to turn on the events might have broken, but it should be ctrl + alt + f11 for chat and ctrl + alt + f12 for interactive.

**Comment by Firebottle** [comment]
@awrebels please let me know if those hotkeys worked when you get a chance.

**Comment by awrebels** [comment]
Yes they did thank you!
