### ISSUE TITLE
User specific cooldowns? 

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#413]
#### Describe your issue or feature request (details are helpful!):

I have a few buttons that would be great to have user specific cooldowns however still be active for those that have yet to click them. Is this possible?

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
To do this a scene would need to be created for each user. Right now Mixer does not support cooldown for a single person.

**Comment by awrebels** [comment]
Understandable. Do you think a custom script could check if the user recently clicked the button and not proceed with other effects if so? 

Which actually brings up another question is it possible to check which user clicked the button within a custom script? Perhaps to pull user info (name, icon, user link)?

**Comment by Firebottle** [comment]
https://github.com/Firebottle/Firebot/wiki/Writing-Custom-Scripts
https://github.com/Firebottle/Firebot/wiki/API-Documentation

Yes, the custom scripts send info on who pressed the button. Yes, you could do what you wanted with custom scripts. 

You could attach a single custom script to a button and no other effects. If the custom script determines that the user can press the button then you could fire and effects you wanted through the API.

**Comment by Checkmarks** [comment]
@Firebottle I understand this feature has been moved to done on Dec 1, 2017.  I would like to utilize this feature and was wondering if it could be pushed out on the next update or if there is a custom script you could share?

If this is already implemented, could you please point me in the correct direction?

Thank you!

**Comment by DragynsLair** [comment]
Mixer still does not support User Specific Cool-Downs.  There are some custom scripts floating around that could simulate this functionality, but be aware that they are extremely confusing to the end user.  It's best to join The Crowbar discord for custom scripting discussions.  When you pop in make sure to explain your use case so that we better understand what you're trying to accomplish.

Thanks!

**Comment by Checkmarks** [comment]
@DragynsLair would you be able to point me in a direction of a custom script that could simulate it?  My biggest issue with custom scripts is that it gets complicated when firing off effects that have multiple parameters such is the update button effect.

In my opinion, I think Firebot would benefit greatly with an IF/THEN effect where if a condition is true or a condition is false it fires off a list of effects through the GUI.  Do you think we could create this custom script?  I don't think an IF/THEN effect would be too complicated to implement, I'm just not sure how to implement effects that are already supported in Firebot into parameters.

**Comment by DragynsLair** [comment]
I think the IF/THEN is coming, but unsure when.  But you can do the behavior in a custom script.

For example, add this to the beginning of the custom script:
`function getDefaultParameters() {
    return new Promise((resolve, reject) => {
        resolve({
            "IfValid": {
                "type": "effectlist",
                "description": "Effects on Valid User",
                "secondaryDescription": "Effects that run if Text Data is a Valid User",
                "showBottomHr": true
            },
            "IfNotValid": {
                "type": "effectlist",
                "description": "Effects on Invalid User",
                "secondaryDescription": "Effects that run if Text Data is an Invalid User"
            }
        });
    });
}
exports.getDefaultParameters = getDefaultParameters;
`
Then something like this in the promise:
`        if (!isValid) {
            global.userName = "none";
            var response = {
                success: true,
                effects: runRequest.parameters.IfNotValid
            }
        } else {
            global.userName = textData;
            var response = {
                success: true,
                effects: runRequest.parameters.IfValid
            }
        }
`

You'll be able to build the two effect lists using the GUI.
