### ISSUE TITLE
dead link on Writing Custom Scripts

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#415]
#### Describe your issue or feature request (details are helpful!):

Just a small thing: 
On this page https://github.com/Firebottle/Firebot/wiki/Writing-Custom-Scripts the EffectType.js referenced link is dead. 

Should be changed to https://github.com/Firebottle/Firebot/blob/master/lib/common/EffectType.js

**Comment by ebiggz** [comment]
Ahh good catch good sir. The page has been updated with correct link. 👍
