### ISSUE TITLE
Counter on most used button

### ISSUE THREAD

**Issue by dicksonia** [Firebottle/Firebot#416]
#### Describe your issue or feature request (details are helpful!):

is there a way to add a feature there is keeps track of What button is pushed the most, even if its simple like Button 21 was pushed 251 time this month ETC. am wanting something like this to keep track of what people like so we can change the board up, 

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
What you're describing would probably go on the "dashboard" which we have a feature request for already. But it would but cool to have an individual count per button that could be used with variable in the chat effect.
