### ISSUE TITLE
[Feature RQ] Manual editing of JSON button layout

### ISSUE THREAD

**Issue by Annorexorcist** [Firebottle/Firebot#418]
#### Describe your issue or feature request (details are helpful!):
I would like to be able to manually edit the board's JSON file to resize buttons smaller than you currently can on the online editor interface. Scorpbot's interactive system can set buttons to as small as 1x1, so I know Mixer itself supports small buttons.

**Comment by Firebottle** [comment]
Hello! Yes, Firebot follows Mixer's guidelines as they have them set in the interactive studio. I'll keep this feature request open, but we plan to continue following those guidelines for the foreseeable future.

**Comment by Firebottle** [comment]
I'm going to go ahead and close this request for now. The dev group has spoken about this several times and are in agreement to continue using the mixer dev lab regulations. It keeps the site looking nice and keeps interactive usable.

Should something change in the future we'll open up a different issue.
