### ISSUE TITLE
Feature request- Using mixer commands

### ISSUE THREAD

**Issue by EarWaxCandy** [Firebottle/Firebot#420]
#### Describe your issue or feature request (details are helpful!):
Is it possible to use mixer commands, for example /timeout /ban /giveaway. if not, could something be added to allow them. currently it just puts the text into chat

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
There is a working version of this in the chat improvements branch. It's likely it'll find its way into the next release.

**Comment by ebiggz** [comment]
Release in v4.8.0
