### ISSUE TITLE
Custom Script Repo

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#422]
We've been passing around the idea of a custom script repo for awhile, but I think it'd be great if we could work it directly into Firebot.

Basically Firebot would have a selection of pre-screened community created scripts for people to choose from. In Firebot the user would be able to see the name of the person that created the script, a description, and perhaps a link to the creators channel or website. The user could then select whichever one they wanted to have it applied to a button.

I was thinking we could host these scripts on Firebot.pro so that we could update and pull lists of scripts on the fly without a full on Firebot update.

This idea would allow more community members to help and contribute even if they dont want to dive into Firebot itself.

**Comment by ebiggz** [comment]
Firebottle has started work on this: 
https://github.com/Firebottle/FirebotScripts
