### ISSUE TITLE
Feature Request: Leave the firebot.exe file in the same location during upgrades.

### ISSUE THREAD

**Issue by cbrookins** [Firebottle/Firebot#424]
#### Describe your issue or feature request (details are helpful!):

Each time I do an upgrade I have to allow it through the Windows firewall.  Is is possible to quit moving the location of the executable? (Ex. AppData\Local\Firebot\app-4.4.4\firebot.exe and AppData\Local\Firebot\app-4.4.5\firebot.exe)

After a few upgrades you have an entry for every version of firebot you have ever run.  This is more of an annoyance than an issue.  May be more of an issue for people using a third party firewall.

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.4.5

- What are the steps to reproduce the issue?
1) Update to a new version
2) Use the Windows firewall

**Comment by Firebottle** [comment]
Are you talking about the button you need to hit when installing?

**Comment by cbrookins** [comment]
That is it exactly.  Is it just the one click at each upgrade.  It adds a new entry to the firewall for each new version of firebot, because the executable is at a different location on disk.  Running 4.4.0 adds an entry, upgrade to 4.4.1 adds an additional entry, 4.4.2 another entry.  Where it should be one firewall entry you now have three.  This will continue with each new version.

I unfortunately cleaned out all the old entries in the firewall or I would send you a screenshot of the 12 or so entries I had for firebot.

But like I said, it is more of an annoyance than a bug.  I do not think it would cause harm, just not clean.

**Comment by Firebottle** [comment]
Understood, we can look into it. Right now the installer creates a new folder each time because it can't overwrite the executable that is running to download the new update.

**Comment by Firebottle** [comment]
I have the curse of always hitting the close button instead of the comment button. Sorry, reopened.

**Comment by Firebottle** [comment]
Im going to go ahead and close this as a duplicate. Fixing this would require that we change updaters and installers which we have tickets open for already.
