### ISSUE TITLE
Updated Board Not Syncing

### ISSUE THREAD

**Issue by v3r0n1cax** [Firebottle/Firebot#429]
#### Describe your issue or feature request (details are helpful!):
 I updated the board on mixer and it's not updating on firebot. Also I have issues were sometimes the buttons work and other times they don't

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Hello, looks like you missed some information when submitting the issue. What version of Firebot are you running?

Are you sure you saved your changes in the dev lab before going to Firebot? Have you tried restarting Firebot? Are there any error logs from today?

**Comment by Firebottle** [comment]
Closing as it's been 5 days without response.
