### ISSUE TITLE
Overlay folder missing

### ISSUE THREAD

**Issue by GarryMK4** [Firebottle/Firebot#431]
#### Describe your issue or feature request (details are helpful!):
I've been trying to set up my interactive buttons for Mixer and I need a specific folder that has an HTML file in it, but the folder does not exist where it should. I've uninstalled and reinstalled Firebot 3 times and it never adds the overlay folder that I need.

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
v4.4.5

- What are the steps to reproduce the issue?
1) install firebot
2) go to settings and open root folder
3) Overlay folder not present

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

[GarryMK4.zip](https://github.com/Firebottle/Firebot/files/1504352/GarryMK4.zip)
[2017-11-26.zip](https://github.com/Firebottle/Firebot/files/1504353/2017-11-26.zip)

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Hello! You no longer need an HTML file for the overlay. Simply go to the settings are of firebot and there will be a button to copy the overlay path. It'll be something like "localhost".

**Comment by GarryMK4** [comment]
Let me take a moment to see how that will apply. When I try to use this overlay my buttons don't appear on my stream when I'm connected. I'll see if this fixes the issue and get back to you.

**Comment by Firebottle** [comment]
The overlay is completely unrelated to your buttons not showing. If the interactive button is connecting for you buttons will show. You might not see them if you didn't add buttons to desktop, tablet, AND mobile in the Mixer lab.

**Comment by GarryMK4** [comment]
Ah. I did not know that. I guess I will have to go back and trial and error till it is fixed. Thank you for the help

**Comment by Firebottle** [comment]
No worries. If it's connected and you dont see buttons try maximizing the window. If you see them then, that means you need to put buttons on the tablet and mobile views.
