### ISSUE TITLE
HTML Effects not working 

### ISSUE THREAD

**Issue by EarWaxCandy** [Firebottle/Firebot#436]
#### Describe your issue or feature request (details are helpful!):

cannot get html effects to work since recent update on Nov. 30

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by ebiggz** [comment]
Hmm. Using the latest build, I threw a test img tag in an html effect and it worked fine.
Could you explain a little further what exactly isnt working?
Are you not seeing anything whatsoever or are there things showing up but not as expected?

Some other things that might help us nail down the issue:
- Open up the overlay in your browser, open the dev tools (press f12 in chrome), and see if you can see any errors in the console when you click an html button.
- Provide some example html that isn't working for you for us to try.

**Comment by EarWaxCandy** [comment]
hmm.... well now that i've opened it back up it seems to be working again. the html i was using was just an iframe. nothing spectacular. i had opened the overly url in a browser earlier before reporting this issue. go ahead and close this i guess. sorry.

**Comment by ebiggz** [comment]
Super weird. No worries! Let us know if it crops up again.
