### ISSUE TITLE
Keyboard Controls Don't work

### ISSUE THREAD

**Issue by JimmyMac3** [Firebottle/Firebot#439]
I've set up the buttons in the Dev Lab and setup the buttons as game control buttons in firebot to emulate keyboard controls so a viewer can press the arrow key interactive buttons to control an on stream game - It works fine when I click on the interactive buttons with the mouse but when I use the Keyboard controls nothing - Doesn't even show an event in the event log. When I use the keyboard arrow keys (I've tried it with WASD too) the interactive buttons on the channel light up just as if they are being pressed by mouse click so not sure why that isn't being picked up by firebot

-----------------------------------------------------------------------
- What version of Firebot are you running? 4.5.0 beta4

[KBControlsIssue.zip](https://github.com/Firebottle/Firebot/files/1523424/KBControlsIssue.zip)

**Comment by ebiggz** [comment]
Thanks for the report. Keyboard events were indeed broken and have been fixed by Perry. The fix will be in the next update.
