### ISSUE TITLE
Log for button presses when closing bot

### ISSUE THREAD

**Issue by GamertagIsAnt** [Firebottle/Firebot#440]
#### Describe your issue or feature request (details are helpful!):

This is not really an issue more like a Quality of Life Feature Request.

It would be super awesome to have a log file saved for the events being pressed once you shut the bot down or if/when it crashes so that way if you need to review the list of people who pressed buttons you can. Currently every time you close the bot it starts fresh upon restart.

I will be honest sometimes I'm like yup that was an epic stream then close all the bots but forget I had that one user who was spamming a button or for instance others may have no cool-downs on their sub board so it would be nice for that too. 

Thank you all for the wonderful work, the bot is amazing Keep it up!

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
4.5.0-beta3

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Hello!

You can now add a "text to file" effect to buttons and commands. If you use the "append" options with this affect it will do what you want.

**Comment by GamertagIsAnt** [comment]
Thanks Firebot Team, You all are awesome!
