### ISSUE TITLE
Boards Will not load

### ISSUE THREAD

**Issue by JimmyMac3** [Firebottle/Firebot#441]
Can't use any boards other than the very first original sound board I ever created - Second board I created in beta 4 shows up in beta 5 but when I hit the interactive button it shows my old sound board

As a test I went to the dev lab and created completely new board from scratch and when I go live it still just brings up my original sound board.

Also firebot doesn't keep changes to the boards - I add an effect and save it but if I hit resync or restart firebot the effects are gone.

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running? 4.5.0 Beta5

- What are the steps to reproduce the issue?
1) Make a second board
2) go live with second board
3) First board shows up

[controls.zip](https://github.com/Firebottle/Firebot/files/1524967/controls.zip)

**Comment by ebiggz** [comment]
Hey Jimmy, thanks for the report. We have made a ton of updates for the next beta that should resolve all of these issues. :)
