### ISSUE TITLE
Tagged users not passed to custom scripts via command args

### ISSUE THREAD

**Issue by platypusmuerte** [Firebottle/Firebot#442]
#### Describe your issue or feature request (details are helpful!):
The commands are not passing tagged users as arguments, instead it becomes an empty string.

Also, the commands object in runRequest is different than the wiki

Wiki says it should be:
`command: {
        trigger: string,
        args: array
  }`

Instead I get: 

{"cmd":{"value":"mycommand"},"args":["test",""]} 

when I type "mycommand test @PlatypusMuerte"

- What version of Firebot are you running?
4.5.0-beta4

- What are the steps to reproduce the issue?
1) Create a command, and a custom script that just returns the runRequest
2) call the command with at least 1 of the args as a tagged user (using @)

**Comment by ebiggz** [comment]
This has been fixed and will be in the next beta. :)

**Comment by platypusmuerte** [comment]
EBiggz, you rock!
