### ISSUE TITLE
Manually Pressing Button error.

### ISSUE THREAD

**Issue by ColdFoamy** [Firebottle/Firebot#443]
## What version of Firebot are you running?
v4.5.0-beta6

## Please describe the issue or feature requests in as much detail as possible.
Tried manually clicking a button. The button only contains an .mp3 Play Sound effect.
![image](https://user-images.githubusercontent.com/34302925/33655974-89397182-da6c-11e7-8b16-02efb4ff246e.png)

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
Thanks for the heads up.  Definitely a bug. There is a work around however, if you click "Edit" on any button, and then click Save, all buttons should be able to be manually clicked.

**Comment by ColdFoamy** [comment]
Yep! Just figured that out. All sorted now :D
