### ISSUE TITLE
Tenths of seconds in UI

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#447]
## What version of Firebot are you running?

4.5.0

## Please describe the issue or feature requests in as much detail as possible.

In the UI you are unable to show a video for something like 1.6 seconds. It rounds to the nearest whole number. Likely something in the code is just setup to ignore tenths.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
Fixed this issue.

In the overlay, we were doing `parseInt` on duration which cut off everything but the whole number. Updated function to `parseFloat` to resolve.

**Comment by ebiggz** [comment]
Release in v4.8.0
