### ISSUE TITLE
permissions per button 

### ISSUE THREAD

**Issue by Evldoa** [Firebottle/Firebot#448]
I would like to see a permission tab added to the individual buttons example so that i could have buttons on my default board that only my mod group can use 

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
hello, this has been entered #330 I'll keep that one open and close this as a duplicate. Feel free to comment in the other thread! Thanks so much for opening an issue and helping build firebot!
