### ISSUE TITLE
Button: Image Overlay

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#45]
This would be a new button. When it is clicked it would send a websocket message over to an HTML file the streamer has loaded up in their streaming software. When the message was received an image or gif would be shown for X seconds.

- Image selector w/ validation
- Time to show
- Screen positioning. (X/Y Coords or do we go with "Top Center", "Top Left" etc... dropdown?)

**Comment by ThePerry-2015** [comment]
X/Y will give most possible customization for the user, but it will require the user to input their output resolution in app settings. If done with X/Y should it have just input fields or both input fields and sliders?

For own reference: [jQuery Slider API](http://api.jqueryui.com/slider/)

**Comment by Firebottle** [comment]
I'm thinking I'm going to combine this with the sound button and just turn it into a "media" button. I'd say probably 99% of the time people will want to use a sound along with an image. For the media button, both the image and sound will be optional.

**Comment by Firebottle** [comment]
This change is now in the newest commit. I've combined this one with the sound attachment request. You can now attach sounds OR images to any button you create.
