### ISSUE TITLE
Buttons wiped of effects (all sounds gone.. again)

### ISSUE THREAD

**Issue by Lagby** [Firebottle/Firebot#451]
## What version of Firebot are you running?
v4.6.0

## Please describe the issue or feature requests in as much detail as possible.
Waterbottle broke my board and all the sounds disappeared.  I was adding write-file to a new button.. testing file entry... and waterbottled spammed and broke all the things.

Messed around with event list attached to the button.   

Check vod.. 06:10:00 mark.. around there.. I restored backup from earlier in the day and restored successfully.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Took a look at the board json file (also tossed it into discord) and it looks like for whatever reason it pulled a partial board from Mixer. When it does this Firebot thinks that you deleted the buttons from Mixer and they're no longer needed. So, it deletes all of the settings for the buttons that are gone.

No idea what caused the partial board to be pulled. Will do some research.

**Comment by Firebottle** [comment]
We haven't had any other reports of this happening since December. Closing this one. If you run into the issue again just let us know.
