### ISSUE TITLE
Unable to login as another user due to credential caching

### ISSUE THREAD

**Issue by DeekyJay** [Firebottle/Firebot#453]
## What version of Firebot are you running?
v.4.6.0

## Please describe the issue or feature requests in as much detail as possible.
When logging out and attempting to login, credentials are cached in the browser, so it automatically logs you in as the previous logged in user.

![2017-12-14_15-08-01](https://user-images.githubusercontent.com/6782859/34018878-e6246968-e0e0-11e7-92e1-0b5a33e2588a.gif)

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Hello! If you log out, restart firebot, and then log back in does that fix the issue? That might work temporarily until we can get something else in place.

**Comment by ebiggz** [comment]
Released in v4.9.0
