### ISSUE TITLE
Chat Reconnect Auth Loop

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#454]
## What version of Firebot are you running?

4.5.0

## Please describe the issue or feature requests in as much detail as possible.

There was an issue where if authentication failed the chat reconnect function would still try to fire resulting in 5 authentication failed responses. The error messages that the function threw would cover up the real reason for the problem.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Fixed. If you run into an auth issue it will stop all connection attempts and log that account out of the app. We log the person out due to their auth tokens being out of sync. In these cases a re-log will fix the problem.

**Comment by ebiggz** [comment]
Released in 4.7.0
