### ISSUE TITLE
Suggestion: Show/hide Sources on OBS/Xsplit

### ISSUE THREAD

**Issue by KensonPlays** [Firebottle/Firebot#459]
## What version of Firebot are you running?
v4.7.1

## Please describe the issue or feature requests in as much detail as possible.
I think it would be cool to be able to control a source or two in OBS/Xsplit.

I have a "Cat Cam" and sometimes the cat isn't sleeping on my bed, I could then hide those sources without alt-tabbing to hide them until my cat's back.

StreamDeck can't do multiple sources at once, so this would be a good alternative (since I use my iPad as a third monitor anyhow).

**Comment by Firebottle** [comment]
Can you bind hotkeys to do what you want? If so, you can use game controls in firebot.

**Comment by Firebottle** [comment]
Closing this due to no response.
