### ISSUE TITLE
Constellation (alerts for events like follows and subs)

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#462]
**Before Launch**:
- [x] Implement constellation
- [x] Follow, Subs, Host events. Should be able to apply our effects system to these.
- [x] Implement optional stats into ui somewhere. (current viewers, total viewers, etc...)
- [x] Build new panel in moderation area to use as a constellation event log.

**Bonus ideas**:
- Raid warning: If current viewer count increases by xx% (user configurable) then fire an event. 
- Spark Exempt: If a user follows, subs, or hosts give them spark exempt status for X amount of time.
- Viewer Goal: If a channel hits X number of viewers, fire whatever effects are configured.
- Sub Goal: If a channel hits X number of subs, fire whatever effects are configured.

Several of these "other ideas" might require a button to reset the "current session". That way they can reset the number of followers and such.

**Comment by ebiggz** [comment]
This is awesome. For # 4, we could probably tabulate the current Event Log to save space. "Interactive" for current stuff, "Events" or "Channel" for constellation, etc

**Comment by Firebottle** [comment]
That would be great. I was just looking into that a bit ago and was thinking two logs, one for "interactive events" and one for "stream events", but if we can somehow combine these and save space that would be awesome.

**Comment by ebiggz** [comment]
Marking this as dev complete I think the first iteration of this work is ready for release

**Comment by ebiggz** [comment]
Release in v4.8.0
