### ISSUE TITLE
Play full video when no duration is specified

### ISSUE THREAD

**Issue by ZeroCola89** [Firebottle/Firebot#464]
## What version of Firebot are you running?
v.4.7.1
## Please describe the issue or feature requests in as much detail as possible.
Bug Report:
I've added several videofiles (as Random Effect -> as Show Video), but the videos end to early. For example. A video takes over 20 seconds, but it end after 5 seconds. I do not set a time, when the video should end.

**Comment by ebiggz** [comment]
Hi ZeroCola, thanks for the bug report.

This is actually intended behavior. If no duration is specified, the duration is set to 5 seconds by default. So I am going to tag this as a feature request and update the title to reflect that. 

I am not a fan of this behavior either as it's not intuitive, especially when we don't state anywhere that we default to 5 seconds. So I'd definitely like to get this updated.

The workaround currently is just to manually set the duration in the effect options.
