### ISSUE TITLE
Channel Editor Mod Scene Access

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#467]
Streamers can give certain people channel editor access. This is passed through the API as being the primary role for that user. The auto grouper doesnt know how to handle this role and throws them in the default scene. 

We just need to either separate this role from the mod role so people can select it, or we need to just group it in along with mods.

**Comment by Firebottle** [comment]
For now I quickly just combined the editor role with the mod role. We can separate it out if there is a need later.

**Comment by ebiggz** [comment]
Release in v4.8.0
