### ISSUE TITLE
Version 4.7.1 Multiple Issues Arising

### ISSUE THREAD

**Issue by mysterio30** [Firebottle/Firebot#468]
Been Running into an issue where everytime i close firebot, i open it up again and it resets firebot back to a fresh install. i have looked into backingup the files and it still reverts yet it still remembers my streamer/bot login.

2nd issue im running into. i setup my board, i have it all setup. locked in and i edit 1 of my buttons. ID is :Nushing. Add in the sound effect and when i try to test play the sound i get an error message stating "there was an error trying to manually activate the button TypeError: cannot read property controls of undefined" these issues have only arisen since the new update for firebot.  

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
Hi @mysterio30 

It sounds like you have somehow got some corrupted files. 

If you can, it would be awesome if you could send your save files in a zip. Heres how:

- Open Firebot (and skip through the setup wizard), and then go to the **Settings** section, click on **Open Root Folder** in the "General" tab. 
- That should open up a file explorer window
- In that window, you should see a folder called **user-settings**. Zip that one up.

Now that you have the zip, you can attach it to this ticket (by dragging the zip into the text field here) or by DMing it to us in Discord. Send it to me or Firebottle. 

We can also chat about this in our discord server if you prefer: https://discord.gg/DegW792

**Comment by mysterio30** [comment]
I have thrown you my settings via a DM on discord. Discord may be indeed easier!

**Comment by ebiggz** [comment]
I see you have, thanks. I'll follow up there!

**Comment by ebiggz** [comment]
Mysterio's user-settings folder indeed had a corrupted settings.json file, and one of his board saves was also corrupted. He's starting fresh and will make a backup once hes setup again. 

For other devs:
A recurring theme in the couple of corrupted file incidents we've had, is there is an extra and nameless, ".json" file in the controls folder. I wonder if that is whats triggering these sorts of corruptions.
