### ISSUE TITLE
In App Chat Window

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#469]
Throwing this in here for reference when the next release goes out. Chat window is working in the chat improvements branch.

- Shows viewers currently connected.
- Can chat as either bot or streamer account.
- Can now use mixer native commands such as /giveaway.
- Can turn the entire thing on/off in settings. Off would likely improve performance elsewhere, especially in big chat rooms.
- Added option to buttons, commands, and constellation events, to show an alert in the chat window. (Note any messages from "System" are shown only in app and not in actual chat.)
- Added ability to see which moderation actions were taken by which moderators where possible. (Ex: Message deleted by Firebottle)

**Comment by ebiggz** [comment]
Release in v4.8.0
