### ISSUE TITLE
Chat Feed, Phase 2

### ISSUE THREAD

**Issue by ebiggz** [Firebottle/Firebot#474]
Now that the first iteration of the chat feed is in, here is the current backlog of features we want to get in next or eventually

- [x] Support /r chat command that replies to last whisper.
- [x] Inline buttons to delete, timeout, purge, and ban users.
- [x] Handle whispers sent to bot account.
- [x] Clickable URL's in chat
- [x] Press up to cycle through previously sent messages/commands
- [x] Ping when tagged/highlight messages with tags

**Comment by MagX47** [comment]
Another suggestion, show users entering and exiting chat if possible?

**Comment by Firebottle** [comment]
@MagX47 We can definitely look into it! That'll probably be one of the later features we add since we have the viewer list on the side. However it wouldn't be too hard to implement.

**Comment by ebiggz** [comment]
I am going to call the current completed features dev complete and create a "Phase 3" for the remaining items.
