### ISSUE TITLE
Can't exit from webpage which opens in Firebot

### ISSUE THREAD

**Issue by UnknownTBeast** [Firebottle/Firebot#477]
## What version of Firebot are you running?
4.8.0

## Please describe the issue or feature requests in as much detail as possible.
On UPDATES page, there is a link "Please note: we still have more features we'd like to add for this. See them here." If you click the link it opens the page in Firebot. But there is no way to close out of the page and even with my "go back" button on mouse, it doesn't go back to the Firebot GUI. Only way to close it is to restart Firebot.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
Thanks for the heads up Unknown! I updated the github release page to not have a link in it anymore.
