### ISSUE TITLE
unable to download. says unsafe.

### ISSUE THREAD

**Issue by kittykatkatey** [Firebottle/Firebot#484]
## What version of Firebot are you running?

trying to download v4.8.0

## Please describe the issue or feature requests in as much detail as possible.
 unable to download for windows. giving a unsafe message and wont let me continue.

   

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
looks like this was resolved in discord.
