### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#487]
Creating for patch note purposes.

I'm currently working to resolve issues with chat, interactive, and constellation issues. I want to make sure they work well, don't double up chat messages, and other weird issues we've been seeing recently.

- [x] Better error handling for chat, interactive, and constellation.
- [x] Clean up auto reconnect script for chat, and convert it for use on interactive and constellation as well.
- [x] Clear reconnect attempts if users manually interact with connection buttons.
- [x] Check status.mixer.com for reported issues and warn user of possible connection problems.

**Comment by ebiggz** [comment]
Released in v4.9.0
