### ISSUE TITLE
Images/Gifs not displaying but sounds are working fine.

### ISSUE THREAD

**Issue by Thuurston** [Firebottle/Firebot#488]
## What version of Firebot are you running?
v4.8.0

## Please describe the issue or feature requests in as much detail as possible.

Sounds on the board are working perfectly but the images do not show up in OBS.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ThePerry-2015** [comment]
In which order do you start OBS and Firebot?
With the current Overlay system we are using you have to start Firebot first then OBS.
If you start OBS first then Firebot, open the Firebot Overlay inside OBS and refresh overlay cache to see if that helps.

Another thing, are you using images stored in your Onedrive folder by any chance?

**Comment by ebiggz** [comment]
Hey @Thuurston 
It sounds like you have a caching issue.
The overlay is hosted once Firebot starts running, so you may notice images and videos not showing up if you start your broadcasting software before Firebot. To prevent this, make sure to select **Refresh browser when scene becomes active** for the overlay Browsersource or just make sure Firebot is started first.

**Comment by Thuurston** [comment]
Starting Firebot first, then OBS worked.

Thanks! Sorry, I'm new to this haha

**Comment by ThePerry-2015** [comment]
No problem, glad we could help. 👍

**Comment by ebiggz** [comment]
In an upcoming release we will have an easy way to see if the overlay is properly connected or not as we know its not always obvious. Thanks for reaching out!
