### ISSUE TITLE
Html Url Effect - almost like a browser source

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#489]
#### If you're reporting an issue, *please* fill out & do the following questions. If you leave them blank the issue may be closed due to lack of information.

Is it possible to update the html effect to allow for url input? I'm thinking to clean up overlays we have buttons that trigger certain static ones. For instance streamjar goals or that stream boss overlay. 

Perhaps there is another method that already exists that I'm not thinking about. 

Thanks for the help in advance 

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
You might be able to throw an iframe into the HTML effect. I haven't tried it myself and I'm not sure it'd work with everything, but it could be a temporary solution.
