### ISSUE TITLE
Scenes tabs still exist after deleting scenes.

### ISSUE THREAD

**Issue by UnknownTBeast** [Firebottle/Firebot#494]
## What version of Firebot are you running?
4.8.0

## Please describe the issue or feature requests in as much detail as possible.
Added some additional scenes to my workout board (179320) the other day, then realized I couldn't do what I wanted to with them. So I deleted them from the Mixer interactive site, and saved it. I then resynced the board. But the old scene tabs were still there, but no button in those tabs. I tried changing to another board then back to the workout board, tabs still there. 

It's not hurting anything, I just don't want to re-add the board again and do all the button settings again.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Fixed as part of #501
