### ISSUE TITLE
Option to put user back in the last group they were in on reconnect

### ISSUE THREAD

**Issue by EarWaxCandy** [Firebottle/Firebot#499]
## What version of Firebot are you running?

Release v4.9.0

## Please describe the issue or feature requests in as much detail as possible.

I'm not sure that this is supposed to be this way. A user presses a button, the button does a change group command. They don't show up in the viewer groups, however the board does change scenes. 
if the user refreshes the stream, they end up back into the default group on the main scene. shouldn't changing group actually assign them to that group permanently?

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Yes, that is intended behavior. We rely on Mixer to keep track of which groups people are in instead of keeping track of all of that in the bot itself. When a user refreshes Mixer they are treated as a new user for all intents and purposes. So they're thrown back into their original group.

Are you running into times when this is a big issue? Could you give us more detail on the situation?

**Comment by EarWaxCandy** [comment]
I'm planning to make a sort of "choose your own adventure game" using
multiple scenes etc. At the end, I'm giving away game codes, gift cards,
etc.  if for some reason the board were to disconnect, crash, or whatever,
people would lose their progress I can't risk that. I know that you can
manually assign a user to a viewer group. Not sure if they stay that way
permanently? If so, is it possible to put someone in a group via script or
is it something that can be added as an option.

**Comment by ebiggz** [comment]
It's certainly possible to add a toggle on the Change Group effect to make the user "permanently change groups", aka update the group data file.  @Firebottle Would there be any adverse implications to adding something like that? If not, we can mark this as a feature request. The choose your own adventure idea sounds really cool.

**Comment by Firebottle** [comment]
Only problem is that the groups json file wasn't really built for that or meant to hold that many people. With what we have right now those names never get cleared, so after a few streams that json file is going to be massive. 

I think we could probably do this once we get the new DB in place that will track points and stuff. We could just add another column there for "last group" or something.
