### ISSUE TITLE
Add chat related events to the live events area.

### ISSUE THREAD

**Issue by mito551** [Firebottle/Firebot#503]
## Please describe the issue or feature requests in as much detail as possible.

I love the events feature and would love to see the event "Poll started" and "Poll ended" to play sounds whenever I make a poll and whenever the results are in.
Also, a donation event will also be nice, but that's only when mixer implements those.

**Comment by Firebottle** [comment]
To build on top of this, I'd like to incorporate all the events we can.

- Purge message event
- Clear chat event
- Timeout event
- Delete message event

etc...

**Comment by snowlerblader** [comment]
I believe this is the right place to add this request - I really like the viewer entrance sound effect option that scorpbot has. I use it for followers, but also to warn me when hypezone pops in. 

Thanks!

**Comment by ebiggz** [comment]
@kateract is going to take this on.

**Comment by DereckR** [comment]
@Firebottle I have also added a couple of commands that when firebot detects hypezone it hides notifications and follow notifications until finished to make sure no distractions. Might want to add this to it .

**Comment by Firebottle** [comment]
@DereckR That might not be in the first release, but it is a very good idea! You might create a new feature request for that one.

**Comment by snowlerblader** [comment]
Hi Devs, I successfully got firebot to play a sound when a user joins chat. Thanks! Is this the right place to continue to ask for feature adds on top of that, or should I open a new issue? I'd like to be able to assign sounds to specific users or groups of users.
