### ISSUE TITLE
Feature Request: Chat Commands can be set to check all text

### ISSUE THREAD

**Issue by JimmyMac3** [Firebottle/Firebot#507]
Add an option to set a command to check the whole line of text not just the beginning of it to see if the trigger word is in it. 

Example
Trigger - hacks
Whole Line Option Enabled

Any of these in chat would trigger the effect:
#hacks
I Call hacks
hacks
did you see that :o hacks for sure!

And while your at it could you give us an option to make the trigger not case sensitive please

**Comment by Firebottle** [comment]
Heya! this will be part of #497
