### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by dicksonia** [Firebottle/Firebot#509]
## Please describe the issue or feature requests in as much detail as possible.
  Streamer pixelprincess80 for a few months now has been having issues with fire bot crashing and stop working on mixer well streaming. we dont know why its been crashing. we have to keep restarting it multiple  times a stream . we have reinstalled a few times now and keep it up to date but still does it. the app its self does not close off it just does not stay connected to mixer interactive 2.0 any help please ? 

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Hello!

We're going to need some more info. Is the program actually crashing or is it just disconnecting from mixer? Can she send over her logs from a day shes having issues?

To get log files go to settings -> open root folder -> /user-settings -> /logs and look for the file with a date. Attach it to your comment here.

**Comment by dicksonia** [comment]
Sorry for the late reply i was with out net for a few days . its just the
Bot disconnecting from mixer . . the bot is not fully closing down . she
will be sending me the logs today after her stream and ill pass them on
ASAP . again sorry for the delay in response .

**Comment by dicksonia** [comment]
this is the log Pixel has sent me from todays stream and crash . if you
need more let me know and ill send them  all  . hehehe . Thanks guys
