### ISSUE TITLE
Feature Request: Text Effect

### ISSUE THREAD

**Issue by mito551** [Firebottle/Firebot#512]
## Please describe the issue or feature requests in as much detail as possible.

Would be nice to show text on screen with a user's name or any other variables we can use in chat. 
If possible, we should also be able to use all the video/image effects. 
I primarily have the follower/host/sub notifications to be honest, but you can imagine a miriad of ways text can be used. 

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
Hi Mito,

Thanks for the awesome feature requests. I agree a "Show Text" effect is needed sorely for the Events stuff. I actually have already completed work on this so it should be in the next release. 

We'll use this ticket for tracking the feature and notifying when it's available.

**Comment by mito551** [comment]
That sounds great, thanks for the update!

P. S. I'm mitori on discord ;)
