### ISSUE TITLE
Feature Request: Add AutoIt for interactivity

### ISSUE THREAD

**Issue by Dementei** [Firebottle/Firebot#514]
## Please describe the issue or feature requests in as much detail as possible.
Based off of this older fork of BeamChatPlays https://github.com/CarpeNecopinum/BeamChatPlays-autoit it is said that using AutoIt, instead of current emulators such as RobotJS and KMBRobot, actually improves game compatibility for interactivity usage. I haven't tried it personally, but it'd be great to test it at least. I am trying to put together a maximum game compatibility stream for viewers to fully control one of my games without the issues that arise using current emulators. With this new emulator it should work with full range keyboard, combos, mouse control and clicks, joystick, same as the others if possible, thanks. Thanks!

**Comment by Firebottle** [comment]
Dementei, you said you haven't used autoit before? Do you know if it actually improves compatibility with your games? If not, would you be willing to give it a shot?

**Comment by Dementei** [comment]
With the older fork I posted, I don't think it works with Mixer since the updates so I haven't been able to try.  It uses OAuth and a different JSON script layout, it's a little bit beyond me to figure it out.

**Comment by Firebottle** [comment]
Okay, we'll look into it. I'd never heard of autoit before you brought it up and there is no guarantee that it'd improve game compatibility over what we have now. But, if it's easy to implement we'll definitely do it.
