### ISSUE TITLE
Button: Custom Scripts / Custom Web API calls

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#52]
Add in a new button that, when clicked, will load up a JS file and run a function. This would allow people to run custom scripts. This would be a very dangerous option for most people, so we'd need to have people specifically enable it in the settings area with some type of warning.

**Comment by ebiggz** [comment]
I am currently working on this feature. Just commenting here to make sure we don't have multiple folks working on this in tandem. I am nearing completion and will have a pull request in soon. 👍

**Comment by Firebottle** [comment]
@ebiggz holy crap this is super cool. Testing it all now and will hopefully get it into the next build.

**Comment by ebiggz** [comment]
@Firebottle Awesome, that example is great.

**Comment by Firebottle** [comment]
Released 3.3.0
