### ISSUE TITLE
Spark Exemption Groups

### ISSUE THREAD

**Issue by CrazedLlamaz** [Firebottle/Firebot#534]
## What version of Firebot are you running?
v4.9.0

## Please describe the issue or feature requests in as much detail as possible.
Spark Exemption for Groups does not appear to be working.

I make my subscribers spark exempt by manually typing in their usernames. After becoming partnered I decided to try to use the groups option that by default has a subscribers option. When the option is checked, subscribers are still being charged sparks. I can still fix this by manually entering names.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Add subscribers as a group to your default scene on your board. It works, but the implementation is goofy. The group has to be assigned a scene on the board or else it doesnt function.
