### ISSUE TITLE
Channel Currency, Giveaway Tool, Viewer Hours Watched, Chat Games and import from scorpbot

### ISSUE THREAD

**Issue by OutlawDade** [Firebottle/Firebot#536]
Need that Loyalty Point system and a giveaway tool chat games like heist, roulette etc and track hours watched by viewers and a way to import that stuff from scorpbot and then i can solely use firebot.

**Comment by Firebottle** [comment]
Yep, all of this is already on the list. It'll be a slow rollout and won't happen all at once.

**Comment by Firebottle** [comment]
duplicate of #520 closing
