### ISSUE TITLE
Firebot Won't connect

### ISSUE THREAD

**Issue by TheLifeOfJinWoo** [Firebottle/Firebot#537]
## What version of Firebot are you running?

v4.10.1

## Please describe the issue or feature requests in as much detail as possible.

Hi, so I recently updated my windows 10 version. Now FireBot will no longer connect to mixer interactive services, I've tried adding it to firewall and even disabling windows security and my virus softwares, what do I do???

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
did you try relogging into the app? What troubleshooting steps have you taken and what were the results?

**Comment by TheLifeOfJinWoo** [comment]
Yes! I've tried just about everything and nothing changes, it continues to have the same effect of nothing connecting!

**Comment by Firebottle** [comment]
What specifically have you tried? List out all of the things you've done so far. Are you running bit defender? If so, turn it off.
