### ISSUE TITLE
Black outed buttons

### ISSUE THREAD

**Issue by caspergaming** [Firebottle/Firebot#54]
So when I use cooldown groups with my individual cooldowns go black after the countdown and can't be used again unless I refresh the bot, I have tried changing the settings and can't figure it out.  [https://gyazo.com/7548d32a949f537eca0a57270bf14b45](url)

Edit now everything is getting this no matter what group they are in

**Comment by Firebottle** [comment]
Contacted on discord. Issue is likely due to carrying a v1 controls file over to v2. Controls files are being modified as part of v2 and the v1 versions will have issues.

**Comment by Firebottle** [comment]
Casper, please let me know if the issue was fixed after recreating that board. Thanks!

**Comment by Firebottle** [comment]
Have not heard back on discord or here. Going to go ahead and close this one.
