### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SpontaneousJ** [Firebottle/Firebot#541]
Add the ability to use the obs-websocket to make a connection to obs from firebot.  So that instead of using keyboard shortcuts for turning on/off sources in OBS, the connection through the bot will do the work.  This can also be used to change scenes.

**Comment by SpontaneousJ** [comment]
Here is the link to the plugin - https://github.com/Palakis/obs-websocket

**Comment by Firebottle** [comment]
Thanks for the feature request! We've actually already got this one entered.
