### ISSUE TITLE
"You need to to log into the app as a streamer. (chat-connect)"

### ISSUE THREAD

**Issue by Chronostrider** [Firebottle/Firebot#57]
The 2.0.0 Release version isn't allowing me to launch my interactive board, giving me the above error. I've already logged into the app properly, and I even logged out of my bot's account in case that was causing an issue (which wasn't the case).

**Comment by Firebottle** [comment]
Just to be sure, have you logged out of both the streamer and bot account and then logged back in?

**Comment by Chronostrider** [comment]
Logged out of both, then back in, still didn't work. What DID fix it, I think, was removing Firebot's OAuth entry in my Beam account settings, then logging back into the app. It's possible that the old settings on the Beam side weren't properly being overwritten with the new app's login?

**Comment by Firebottle** [comment]
Hmm.. that could be the case. I'll look into it and see what I can do. Thanks so much for helping out! I imagine several people will probably run into the same issue.

**Comment by mckmuze** [comment]
I'm having this issue as well. No luck getting it to work yet.

**Comment by ambo33** [comment]
same issue here!

**Comment by Firebottle** [comment]
@mckmuze @ambo33 Are you moving from version 1 to version 2? If so, go to your beam account settings and remove access for Firebot. Then re-log into the app.

Otherwise, tell me how you're trying to log into the app (twitter, discord, etc...) and what version you're using.

**Comment by ambo33** [comment]
I THINK I signed up the day they moved from 1 to 2.  I have already done the remove and re-log.  Still doesn't work.

I'm logging into the app via my beam account.  No 3rd party login.  Straight to Beam via username.

**Comment by Firebottle** [comment]
@ambo33 

1. Go to beam -> account -> oauth apps.
2. Find Firebot and hit the remove application button.
3. Go to the firebot folder and delete user-settings/auth.json.
4. Open up firebot and log in again.
5. If that still doesn't work, delete the entire Firebot folder and download the newest version. Then do step 1 and 2 again.

**Comment by ambo33** [comment]
Now I'm getting "You need to to log into the app as a streamer. (chat-connect)" when trying to Launch Interactive

**Comment by Firebottle** [comment]
@ambo33 Did you go through all of the steps? If so, log out of the app and try the alternate login method.

**Comment by Marcan3308** [comment]
Hi, guys. I'm having the same problem. Just downloaded Firebot tonight.

**Comment by wyrdpleigh** [comment]
@Firebottle I went through the steps several times and still cannot get Firebot to function.

**Comment by Firebottle** [comment]
I'm looking into the issue, but it definitely seemed to spike after the xbox app launch. Have you guys gotten it working since posting? @Marcan3308 @wyrdpleigh ?

**Comment by ambo33** [comment]
@Firebottle I literally deleted firebot and re-downloaded and still can't connect.  Same error.

**Comment by Kelestraza** [comment]
I think I am also having the same issue as reported.
1. Did a fresh install tonight
2. Made sure I had the OAuth apps removed from my stream & bot account
3. Logged in in the FireBot App as streamer and bot account
4. Started interactive on beam and then tried to launch interactive in FireBot.
![image](https://cloud.githubusercontent.com/assets/2879045/25262217/813fa368-2624-11e7-8921-93a9ceb8f595.png)

**Comment by ThePerry-2015** [comment]
For those getting the "You need to log into the app as a streamer." message, are you getting this on the first run when you authenticate the streamer account? Have you tried closing firebot and reopened it after logging in? I've seen this issue a couple of times if I don't restart firebot after I've authenticated the accounts for some reason. If I log in then restart firebot it seems to work fine.

**Comment by Kelestraza** [comment]
@ThePerry-2015 Restarting a few times did actually resolve the chat-connect issue.

Thanks.
