### ISSUE TITLE
Feature Request: Offline Mode

### ISSUE THREAD

**Issue by KensonPlays** [Firebottle/Firebot#572]
## What version of Firebot are you running?
4.10.5

## Please describe the issue or feature requests in as much detail as possible.
I think it would be pretty cool to be able to define buttons that are usable when your not live/streaming.

Say, I could have some of my 'information' buttons pressable, but disable the soundboard/game control/etc when not live.

**Comment by kateract** [comment]
It's a little clunky, but you can set up another interactive board for your information buttons and switch over to that board when you go offline.  It's not as easy as using the same board, but it gets the job done.
Also, if your info board is your default board, you can disable buttons that take people to scenes with sounds.
I also think that some of this will be more feasible considering some of the features that are going to be implemented in the next version, so if there's a way we can find a way to tide you over until it comes out, that's probably for the best.

**Comment by Firebottle** [comment]
I think creating a second board is going to be the way to go in general. Adding in functionality for online/offline buttons for one board is something that would most likely over-complicate the system for most people.
