### ISSUE TITLE
Prevent overlap feature request.

### ISSUE THREAD

**Issue by JesterJFool** [Firebottle/Firebot#573]
As a streamer and viewer, I'm brand new to Firebot, but I have friends that have been using it for a while. I just set up my soundboard, and set each individual sound to trigger a cooldown on every other button for the length of the audio. The problem is, if another sound finishes cooling down while the new sound is still playing, users can trigger the freshly cooled down sound, and overlap the sounds. It would be awesome if there were a section in the Edit Button setting entitled "Prevent Overlap" or something similar, which would take the same argument as Cooldown, but would just automatically disable other buttons during the Prevent Overlap period, even if they finish cooldown while the button's effect is playing.

**Comment by DragynsLair** [comment]
You can do that with Cooldown Groups.  See tutorial here: https://www.youtube.com/watch?v=NcUIt3TE4uY&t

**Comment by JesterJFool** [comment]
That's a nice video, but it doesn't solve my problem. Let me see if I can explain it better... I have sounds that range in length from 1 second to 27 seconds. Each button his a personal cooldown of 30 or more seconds. Further, I added a cooldown effect on each of the buttons to set the cooldown of each other button to the length of the file being played. So if I click a button that plays a 12 second sound clip, that sound goes on cooldown for 30 seconds, and while it's playing, everything else goes on cooldown. The problem is, if, when that button is pressed, there is another button with 5 seconds of cooldown remaining, the cooldown of that button finishes while the first button has 7 seconds of play time left, and it can be clicked again, overlapping the two sounds. I would like my viewers to be able to click the buttons one right after another, if that's what they want to do. I really don't want to have to just cool everything down for 30 seconds any time any button is pressed.
What I'd like to see is a box where, when I put in a number (the length of time of the sound), it only overwrites the remaining cooldown on other buttons if the current cooldown on those buttons is currently less than the specified overlap time. So, in the aforementioned scenario, the button that had 5 seconds remaining when I pressed the 12 second long clip button would be overwritten to 12 seconds remaining. Thinking about it further, I think having the option in the cooldown effect to overwrite lower cooldowns would probably be a better solution.

**Comment by DragynsLair** [comment]
All you need to do is put them all in a cooldown group and set the cooldown group's cooldown for 30 seconds and you're done.  I think you're severely overcomplicating this.  

However, if you really want to do that... Option 3 in the video tells you how to do that.
Cooldown Button A for 5 seconds and all the others for 5 seconds using the Cooldown Effect.
Cooldown Button B for 10 seconds and all the others for 10 seconds using the Cooldown Effect.

What you're asking for already exists.  You just need to learn how to use it.

**Comment by JesterJFool** [comment]
I really don't think you're understanding what I'm wanting. I'll make a video later to explain. I'm super tired right now. But believe me when I say that grouping is not the solution I am seeking.

**Comment by kateract** [comment]
@JesterJFool Are you still having trouble with this?  @DragynsLair was not talking about using grouping. 
 There is a specific button **effect** for Cooldowns, alongside effects like Play Sound and Show Image, that will let you cooldown other buttons as an effect of your target button.  Let us know if that fulfills your need, and if you need more help you can always check with us in the [discord](https://discord.gg/DegW792).  Thanks!

**Comment by Firebottle** [comment]
Closing as we've got no response from @JesterJFool in a over a week.
