### ISSUE TITLE
Animation Video Bug Sound OBS

### ISSUE THREAD

**Issue by The-Scro-MX** [Firebottle/Firebot#574]
Hello, here is a little, when we launch an interaction with a video. at the end of my video I get a bug from Obs.

My Microphone and its game become Saturated.

I have not changed any of my settings since I've been using Firebot and OBS, and it's just been starting.

Could someone explain to me where the problem might come from?

I thank you in advance

**Comment by kateract** [comment]
Just a few questions to help us help you:
Are you using a YouTube video, or a local video?  
What do you mean by "My Microphone and its game become Saturated."? 
What version of Firebot are you using?

**Comment by Firebottle** [comment]
Closing as we've gotten no response from @The-Scro-MX in over a week.
