### ISSUE TITLE
cant get my interactives to work on mixer

### ISSUE THREAD

**Issue by inkedinfidel** [Firebottle/Firebot#575]
I have set up all the interactives. They show up on mixer and sometimes I can activate them but most of the time they will not activate on clicking them.

**Comment by kateract** [comment]
@inkedinfidel We're going to need more information about what is going on to be able to help you.  Please submit a new issue and fill out all of the questions by clicking [here](https://github.com/Firebottle/Firebot/issues/new) or contact us on the discord's firebot help channel [here](https://discord.gg/DegW792).  Thank you!
