### ISSUE TITLE
Group CoolDown

### ISSUE THREAD

**Issue by Treavous** [Firebottle/Firebot#577]
## What version of Firebot are you running?

V4.10.5
Using the latest version of OBS

## Please describe the issue or feature requests in as much detail as possible.
I added a group cooldown with both my buttons selected with a cooldown of 15 seconds. When button 1 is clicked, neither button goes to cooldown. If Button 2 is clicked, the cooldown on both is activated.  If I set a Cooldown on each button individually, the cooldown will activate on the button I click only. 

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by kateract** [comment]
@Treavous, you might try giving this video a watch that explains the different cooldown methods available in Firebot and how they work: 
https://www.youtube.com/watch?time_continue=1&v=NcUIt3TE4uY 
If that doesn't help you with the issue you are having, let us know!

**Comment by kateract** [comment]
I'm going to close this since we haven't heard from you again.  If you still need assistance, please check out our discord.
