### ISSUE TITLE
WS and Carina built in Firebot "Feature Request"

### ISSUE THREAD

**Issue by Rawdee** [Firebottle/Firebot#584]
WS and Carina needs to be installed on my PC for some scripts to work, would it be possible to implement that into Firebot instead, so that scripts that require that could work ? 

I think that would open up for many new features in Firebot as well.

**Comment by Firebottle** [comment]
Rawdee, we've discussed then and decided to close this ticket for now.

Our live events system already does what you need. If you haven't looked into that already, you can create a "follow" event that will only trigger for a username once per session. If you find a bug in that, please let us know so we can take a look.
