### ISSUE TITLE
CANNOT LOGIN with NEW update

### ISSUE THREAD

**Issue by JennaRossity** [Firebottle/Firebot#585]
## What version of Firebot are you running?
v4.10.5

## Please describe the issue or feature requests in as much detail as possible.
i can connect to my interactive board, i just cant login my bot and myself. it stays on the orange loading icon forever. ive tried downloading older version. ive tried reinstalling this version. nothing works. ever since i did this update i lost my board. 

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Go into firebot -> settings -> open root folder -> user-settings. Then delete the file called auth.json and try to relaunch the app and log in.

**Comment by JennaRossity** [comment]
Ok this worked. But now
My interactive board isn’t uploading.
It says I have the wrong code when I do not.
I also have to delete that JSON file everytime
I log on. It Doesn’t keep my info when I click it to remember me.
Thanks.

Sent from my iPhone

On Mar 21, 2018, at 5:08 PM, Firebottle <notifications@github.com<mailto:notifications@github.com>> wrote:


Go into firebot -> settings -> open root folder -> user-settings. Then delete the file called auth.json and try to relaunch the app and log in.

**Comment by ebiggz** [comment]
This has been resolved. Closing
