### ISSUE TITLE
Firebot Url not working on Obs

### ISSUE THREAD

**Issue by GentalGiant** [Firebottle/Firebot#586]
## What version of Firebot are you running?

The version of firebot I am using is 4.10.5

## Please describe the issue or feature requests in as much detail as possible.
 I was setting up a button to use a gif in that button I put a Play sound effect and a show image effect then I went into the location where I put fire bot on my computer got the url and opened up Obs added a new scene which was a browse source and put the url in when I went back to fire bot connected fire bot and pressed  the button the sound effect played but the image didn't show and tried the button like three more times but it didn't work so I decided to make a different button that uses a url that I could put in Obs so I used the effect celebration and used the celebrate fireworks and put the url in obs and connected fire bot but the same problem occurred and the fire works didn't show in Obs either so I was wondering if I was doing something wrong honestly I just want t put some gifs on my interactive board through fire bot please help
Thank you P.S hope yall don't mind run on paragraphs
 Hopefully help people who are also struggling to get gifs onto fire bot

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
The paragraph is a bit hard to read, but did you use the button inside of Firebot to get the overlay URL? If not, that's be the first step.

**Comment by kateract** [comment]
I'm going to close this issue since we haven't heard from you again.  If you still need assistance, please contact us through the discord Firebot Help channel.
