### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by jbrandle** [Firebottle/Firebot#587]
## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by jbrandle** [comment]
[SquirrelSetup.log](https://github.com/Firebottle/Firebot/files/1831817/SquirrelSetup.log)

Please help

**Comment by ebiggz** [comment]
Hi @jbrandle
The error in your setup log is indicating that Firebot is getting denied access to install. This most commonly happens with the antivirus software called Bitdefender.

Here’s how to exclude applications in Bitdefender:
https://www.bitdefender.com/support/policy-based-exclusions-1232.html

If you don’t use BitDefender, I would check your antivirus software and see if it’s flagging firebot.

**Comment by Firebottle** [comment]
Closing this one as we helped him in discord I believe.
