### ISSUE TITLE
Buttons not working. 

### ISSUE THREAD

**Issue by InfernumBeam** [Firebottle/Firebot#59]
Okay. So this is a strange one and it could be me mucking things up. But I can get general WASD to work. and a few other keys. However, I cant seem to get some things working. I  have no idea what I'm doing wrong, because the settings for the keys that are working are basically the same for the ones that aren't. Trying to get interactive Minecraft working. 

Setting up keys such as Q, Space, and F as well as 1-9 that aren't working. 
Keys that are working.... WASD, C, Shift. 

Setting for C and Shift are the exact same as Q, Space, f and the number keys....

**Comment by Firebottle** [comment]
Heya, could you go into your user settings folder and attach the controls file for the board you're working with?

**Comment by InfernumBeam** [comment]
{"tactile":{"0":{"id":0,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"Drop Things","typeSettings":{"press":"q","opposite":""}},"1":{"id":1,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"W","typeSettings":{"press":"w","opposite":"s"}},"2":{"id":2,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"A","typeSettings":{"press":"a","opposite":"d"}},"3":{"id":3,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"S","typeSettings":{"press":"s","opposite":"w"}},"4":{"id":4,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"D","typeSettings":{"press":"d","opposite":"a"}},"5":{"id":5,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"Jump","typeSettings":{"press":"space","opposite":"shift"}},"6":{"id":6,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"Sneak","typeSettings":{"press":"shift","opposite":"space"}},"7":{"id":7,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"Run","typeSettings":{"press":"control","opposite":""}},"8":{"id":8,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"Inventory","typeSettings":{"press":"e","opposite":""}},"9":{"id":9,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"Optfine","typeSettings":{"press":"c","opposite":""}},"10":{"id":10,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"Swap Hands","typeSettings":{"press":"f","opposite":""}},"11":{"id":11,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"1","typeSettings":{"press":"1","opposite":""}},"12":{"id":12,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"2","typeSettings":{"press":"2","opposite":""}},"13":{"id":13,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"3","typeSettings":{"press":"3","opposite":""}},"14":{"id":14,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"4","typeSettings":{"press":"4","opposite":""}},"15":{"id":15,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"5","typeSettings":{"press":"5","opposite":""}},"16":{"id":16,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"6","typeSettings":{"press":"6","opposite":""}},"17":{"id":17,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"7","typeSettings":{"press":"7","opposite":""}},"18":{"id":18,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"8","typeSettings":{"press":"8","opposite":""}},"19":{"id":19,"type":"Game Controls","cooldownGroup":"solo","cooldown":0,"notes":"9","typeSettings":{"press":"9","opposite":""}}}}




Couldn't attach the file cause they were Jsons.... So heres a wall of text for you :P :)

**Comment by Firebottle** [comment]
Heya. I loaded up your json and created a dev board. Went through all of the buttons and they're working fine for me in notepad. Can you check your dev lab and make sure you have press frequency or holding clicked for all of them?

**Comment by InfernumBeam** [comment]
Alright.  So it was my end of thing.  I didn't have the frequency checked on the ones that aren't being held.  Gotcha.  Thanks firebottle:)

**Comment by Firebottle** [comment]
No problem! Glad its working for you now!
