### ISSUE TITLE
General -> Events not Showing Created Events

### ISSUE THREAD

**Issue by Oxagon** [Firebottle/Firebot#591]
## What version of Firebot are you running?
v4.10.5

## Please describe the issue or feature requests in as much detail as possible.
Trying to modify created Events and the page is now blank. Event is still working in the Overlay but am unable to see in page to modify or delete.
![firebot issue](https://user-images.githubusercontent.com/37779928/37878668-90f97efc-303a-11e8-894f-9062eed4531d.png)

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
This has been resolved. Closing.
