### ISSUE TITLE
Ban Events Triggering Twice

### ISSUE THREAD

**Issue by mrpaden** [Firebottle/Firebot#592]
## What version of Firebot are you running?
4.10.5

## Please describe the issue or feature requests in as much detail as possible.
Board ID (227364) - Set up an event to trigger whenever someone gets banned. It's to play a sound effect and put a message in chat as the streamer. Whenever a ban happens, both events trigger twice resulting in double chat messages and an echoing sound effect.

**Comment by ebiggz** [comment]
Thanks for the report. This has been fixed in v4.11.0!
