### ISSUE TITLE
Interactive board won't connect. Keeps saying I must import one, even if I do it a million times

### ISSUE THREAD

**Issue by BG123445** [Firebottle/Firebot#593]
## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by BG123445** [comment]
Using V4.10.5
Keep importing a board from mixer, but every time I try to connect it gives error saying I must import a board

**Comment by ebiggz** [comment]
Hey @BG123445 sorry you are having issues. Can you create a firebot backup and attach it here so we can take a look?

Open Firebot > Settings > Backups > Backup Now
then Manage Backups > Open Backups Folder > attach the latest .zip file here.

Alternatively you can talk to us in our Discord if you prefer, and DM one of us your backup zip https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Closing this as it's been over 16 days without reply.
