### ISSUE TITLE
All cooldowns are set to 4 hours.

### ISSUE THREAD

**Issue by Annorexorcist** [Firebottle/Firebot#594]
## What version of Firebot are you running?
v4.10.5

## Please describe the issue or feature requests in as much detail as possible.
I just connected the board to Mixer and was testing my buttons. Firebot seems to cool the buttons down to 4 hours plus whatever cooldown is set in Firebot.

**Comment by DragynsLair** [comment]
This is a pretty common issue.  The most common cause is your PC Clock.  Make sure both the Time and Time Zone on your PC is set correctly.

**Comment by ebiggz** [comment]
Glad its working!
