### ISSUE TITLE
Overlay will not connect

### ISSUE THREAD

**Issue by Lordofthekeg** [Firebottle/Firebot#597]
.

What version of Firebot are you running?
v4.10.5

Please describe the issue or feature requests in as much detail as possible.

I'm using SLOBS 0.8.16.  I've added the browser source to the local file index.html in the Firebot folders.  It will not connect to it.  My Firebot console says, "Running, but nothing connected".  I've ran as Admin, refreshed the cache in SLOBS, but can't manage to get it to connect.  Firewall has an exception added for firebox.exe.  I'm out of ideas as to what to try next.  Any help would be appreciated.

Thank you
Lordofthekeg

**Comment by ebiggz** [comment]
Hi Lordofthekeg, 

In version v4.10.5, you shouldn't be adding a local html file as a browsersource for the overlay. 

If you go to Firebot > Settings > Overlay tab > Get Overlay Path, you should see this:
`http://localhost:7473/overlay`

Try updating your browsersource with that and verifying its connection in the Firebot sidebar.

**Comment by Lordofthekeg** [comment]
That worked.  I apologize.  I'm pretty new to using the bot and was working on some old documentation.  I appreciate the help!  Thank you!
