### ISSUE TITLE
Audio not working on viewers side

### ISSUE THREAD

**Issue by AbyssClutch** [Firebottle/Firebot#598]
## Please describe the issue or feature requests in as much detail as possible.
Hi, i am trying to include interactive buttons for audio on my stream, and it will show the buttons for the viewers, but the audio will not play on their side. It will only pop up on my side. Any recommendations on how to fix my problem?

**Comment by ebiggz** [comment]
This is how the app works. The app doesnt magically play sounds on every viewers device. The app simply plays the sound on your computer and then you need to make sure your broadcasting software (ie OBS/Xsplit) picks up the sound so your viewers hear it too.

**Comment by kateract** [comment]
Added an FAQ Question on the Wiki to cover this topic.
