### ISSUE TITLE
Unable to login using Microsoft, Twitter, Discord login

### ISSUE THREAD

**Issue by ScalySquash50** [Firebottle/Firebot#60]
It appears that something has gone wrong since the latest update with beam. If I try to login to the bot using my beam account, it will not accept any of the other authentication methods, which, since my account was made through Microsoft means I cannot login at all. When you click on any of the other authentication buttons it opens another window, which remains completely blank. If you close that window the original login screen remains buffering until you close it. 

Just wondering if this issue has been identified, and if there are any fixes for it yet. Thanks!

**Comment by Firebottle** [comment]
Heya, thanks for the report. This is the first time I've heard of the issue, but I'll look into it. I believe I know what might be causing it.

**Comment by Firebottle** [comment]
I did end up finding the issue. Looks like a few other apps using electron run into the same problem. I'm working on a fix now. I'll need to create a new login path that will require a bit more manual work (copy/pasting an auth key). It sucks people will have to do that manually, but at least they'll be able to log in until a better solution pops up.

I'm working on the fix now and hopefully I can have this ready in the next day or two.

**Comment by ScalySquash50** [comment]
Can't speak for other people but I'm happy to take a few extra steps so long as it works! Thanks so much for looking into this really appreciate it!

**Comment by Firebottle** [comment]
No problem! I've just released v2.1.0 which should address the problem. Download it below and look for the alternative login link on the login page.

I'll leave this issue open so you can give some feedback on if it works for you.

https://github.com/Firebottle/Firebot/releases/tag/v2.1.0

**Comment by ScalySquash50** [comment]
That worked! To be honest the link to click isn't super clear just below the login button. Took me a couple of read-throughs looking at the patch directions before I figured it out. But once that happened it was super easy. Thanks so much!
