### ISSUE TITLE
Movable Images

### ISSUE THREAD

**Issue by KensonPlays** [Firebottle/Firebot#605]
## What version of Firebot are you running?
4.11.1

## Please describe the issue or feature requests in as much detail as possible.
Having the ability to move a image from one spot to another would be awesome.

For example: Moving from bottom left to bottom right, or top left to bottom right, or whatever you want.

**Comment by Firebottle** [comment]
This already exists. Check out the enter and exit animations on the image effects.  There may be some directions that don't work, but for the most part this is implemented.
