### ISSUE TITLE
Assigning Groups

### ISSUE THREAD

**Issue by TokenParents** [Firebottle/Firebot#607]
## What version of Firebot are you running?
4.11.1

## Please describe the issue or feature requests in as much detail as possible
I'm trying to have people assign themselves to a group permanently. When I choose the effect (Change Group) it works only temporarily. Viewers aren't added permanently to the new group under the groups section. So the next time or after a refresh they aren't being auto sorted into their previously chosen group. 

## Contact Us!
Did you know that we have a help channel in discord as well?

**Comment by Firebottle** [comment]
Yes, this is expected behavior. We do not keep track of what groups people were in last time they visited the channel and neither does mixer. This might be something that eventually finds its way into version 5 later down the road when we have a viewer database built in.
