### ISSUE TITLE
Windows Mixer Icon

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#70]
In the windows sound mixer, the firebot icon is gigantic and makes it so you can't adjust the audio for the app.

**Comment by ThePerry-2015** [comment]
Might be related to this one: https://github.com/electron/electron/issues/4838
Seems like the icon has to use a .ico file so it doesn't use 1024x1024 images instead on Windows.

**Comment by Firebottle** [comment]
Should be fixed in v2.2.1. Thanks for the info Perry! It helped!
