### ISSUE TITLE
Random Disconnections

### ISSUE THREAD

**Issue by GamertagIsAnt** [Firebottle/Firebot#79]
I'm not getting any error reports, the bot is just dying(being told by chat) but when i go back the the program itself it says it's running & sometimes freezes up and just crashes. I also noticed the disconnection thing on Sorryaboutyourcats' stream as well but did not ask him if it was freezing/locking up.

**Comment by Firebottle** [comment]
How many buttons do you have on your board?

**Comment by GamertagIsAnt** [comment]
lol ok yeah I have all of them, soo 64 in total. xD btw It was flawless the whole day of the 2.2.2 release but started acting up the next. :) i may need to save that mega soundboard  for later then :)

**Comment by Firebottle** [comment]
You can still use it for 64 buttons, but I recommend changing the report interval in the dev lab to about 100ms to 150ms. If you still have crashes after that just raise it a bit more. It wont really cause any issues especially if you're using soundboard buttons.
