### ISSUE TITLE
Queue for sounds?

### ISSUE THREAD

**Issue by GamertagIsAnt** [Firebottle/Firebot#80]
I noticed if you push a sound button while a sound is already playing the button does nothing becoming a waste of sparks, it would be nice to allow them to play one after another

**Comment by Firebottle** [comment]
This sounds like a bug possible. It should play each sound as soon as the button is clicked, even if another sound is currently playing.

**Comment by Firebottle** [comment]
@GamertagIsAnt I went in to test this today to try to reproduce the bug. If I push two sound buttons as quickly as I can after each other they both play a sound immediately. 

Could you test this again on your side? Maybe it was a one time fluke? Maybe check to make sure your file paths are correct?

**Comment by GamertagIsAnt** [comment]
Yeah i think it might of been a fluke when the bot was disconnecting due to an incorrect report Interval. havent been able to get it to happen again

**Comment by Firebottle** [comment]
Gotcha. Yeah I'm working on trying to optimize things so that it can handle any size board at any report interval. Just takes a bit of time. Glad this is working though!

Closing issue.
