### ISSUE TITLE
An option to choose the sound output device

### ISSUE THREAD

**Issue by JimmyMac3** [Firebottle/Firebot#81]
Let the user choose where the sound plays. Not just use the windows default. For example - This would allow the use of virtual audio cable and/or VoiceMeeter to give more control over the sound volume and mixing.

**Comment by Firebottle** [comment]
If you haven't already, look into CheVolume for this one.

**Comment by wcphart** [comment]
Why was this removed from future releases? Is it in the latest beta? It is a feature I currently use in another bot, that I really don't want to give up.

**Comment by Firebottle** [comment]
I removed the future releases milestone and just replaced it with a label. However, this feature is low on my to-do list right now. For now I'm just concentrating on trying to make core features stable.

**Comment by wcphart** [comment]
Right on, stable is def more important! Just came here looking for the exact example above. I use Voicemeeter to mix audio into XBox party chat from the soundboard so they can interact too.

Really happy with it so far. Looking forward to whats to come! Thanks for the clarification.

**Comment by wcphart** [comment]
One last thought on this @Firebottle , could it be possible via a config file or something maybe? To avoid worrying about adding UI elements and all that?

**Comment by Firebottle** [comment]
Probably would be easier! I'll look into it.

**Comment by wcphart** [comment]
Hi @Firebottle any chance to think about this one, even if its some manual config stuff for a bit? Hearing more and more streamers wish it had it. I'm happy to be a guinea pig/test subject LOL

**Comment by Firebottle** [comment]
We end up looking at all of the feature requests on the list sooner or later. Can't give an estimate on this one yet as we're working to get 4.0 out right now. I'll make sure to update this area when we have news.

**Comment by awrebels** [comment]
Seems like chevolume is not working anymore or rather inconsistently for windows 10. This would be a great feature. Slightly off topic is there any other program you @Firebottle would recommend in replacement of chevolume?

**Comment by ThePerry-2015** [comment]
I'm using CheVolume on last Insider Preview of Windows 10 Pro , not seen any new issues that wasn't there already in Win7.. It's not rock stable, but then again it has never been.
There is another option out there, Audio-Router (https://github.com/audiorouterdev/audio-router). It's not as well designed as CheVolume, but it's Open Source so you could rewrite it into your own design.

**Comment by wcphart** [comment]
IMO Audio-Router is not reliable. It seems to group things together in virtual groups, where changing 1 affects many others.

Others have stated that using that when you also use Voicemeeter Banana causes sounds to just stop all together, as well as affecting stream volume just by changing something elses volume.

**Comment by Firebottle** [comment]
Just leaving a note here that @awrebels brought up. 

This is going to be very hard to implement because not all sounds play through Firebot. Only the "sound effect" button type plays through Firebot. Everything else goes through the overlay.html file.

We can possible move the sound effects to the overlay.html file as well to get all sounds in the same place. But I'm not aware of a way to set the output device of sounds playing through an html file.

**Comment by ebiggz** [comment]
@awrebels, @wcphart If you didnt already know, the ability to select the audio output device for Sound Effects is now available in v4.5. :)

**Comment by ebiggz** [comment]
This is officially released in the non beta version of v4.5. Closing now.
