### ISSUE TITLE
Disappearing Buttons

### ISSUE THREAD

**Issue by InfernumBeam** [Firebottle/Firebot#84]
So, I have recently had all of my buttons in the app disappear and will not allow me to start the app up. However if I go into the User_settings file and open up the JSON files for the boards, everything is still in tact....... Unsure of what happened, or if a re-install of the bot might be in order. Figured I'd come here and see first.

**Comment by Firebottle** [comment]
This sounds like one of your files has bad JSON data in it. 

1. Go to the user-settings folder.
2. Delete Auth.json and relaunch the app. Login and see if that fixes it.
3. If not, delete settings.json and relaunch the app. This will delete your saved settings.
4. If that doesnt fix it, then reinstall the app.
5. If that still doesnt fix it, then you have a bad controls file. You'll need to delete your board.json file and rebuild the board again. Change the file extension from .json to .txt and attach it here as well.

**Comment by InfernumBeam** [comment]
Settings.json got it to work again!! <3 Thanks Firebottle!

**Comment by Firebottle** [comment]
Awesome! I'll mess around with the settings and see if I can get it to break or load up bad json. Not sure what would have caused it.
