### ISSUE TITLE
Global cooldown

### ISSUE THREAD

**Issue by FluffyMatt** [Firebottle/Firebot#85]
I recently switched over to Firebot to give it a test as it had some unique features. 

One thing I think is missing is that a button press initiates a global cooldown for all buttons, this would stop multiple sounds being fired at once. 

It would also be good to be able to exclude certain buttons from the global cooldown if possible. 

Loving it so far and the extra stuff you can do is awesome keep up the good work.

**Comment by Firebottle** [comment]
This ability is in Firebot v3. Each button can cool down any other button.

https://github.com/Firebottle/Firebot/releases/tag/v3.0.0-beta.1

**Comment by FluffyMatt** [comment]
Could this be extended to include group so a button fires off the cooldown of a group? instead of individual buttons or a way of adding a global cooldown to all button on a single button.

**Comment by Firebottle** [comment]
Yes, you can add as many buttons as you want with the new feature. Any button can cool down any other number of buttons.
