### ISSUE TITLE
Can't get mac release to open

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#90]
perhaps it is me but it doesn't seem to be opening
<img width="393" alt="screen shot 2017-05-09 at 4 16 28 pm" src="https://cloud.githubusercontent.com/assets/28576527/25870828/88e9e0ac-34d3-11e7-8e8d-ada3aae219b3.png">

OSX 10.11.6

**Comment by Firebottle** [comment]
Yep, sorry about that. I tried a mac build with the latest release, but it doesn't look like it's going to work for now. Some of the features such as game controls are only available on windows machines.

In the future I might think about releasing a mac friendly version with the windows only features stripped out.
