### ISSUE TITLE
Error JSON not formatted correctly?

### ISSUE THREAD

**Issue by DeeJaySpiderman** [Firebottle/Firebot#91]
Unsure why its giving me this error atm I'm just clicking copy to clickboard on dev and bringing it right over to firebot and I'm getting that error.

**Comment by Firebottle** [comment]
Firebot does not currently support interactive 2.0 which has different json than 1.0. Make sure you're in the 1.0 lab.

**Comment by DeeJaySpiderman** [comment]
How do we switch it back?

**Comment by Firebottle** [comment]
Go to studio home where you select games and the option is in the top right.
