### ISSUE TITLE
Error - Button # has both holding and frequency checked...

### ISSUE THREAD

**Issue by reecerbeam** [Firebottle/Firebot#92]
Hello,

After I loaded the JSON code and set up my board, I'm getting an error when I try to go interactive. It gives me an error that button # has both holding and press frequency checked in the dev lab. I've checked all buttons and they only have frequency checked. It seems to pick a random button every time I try to go interactive or chat.  I've included a screenshot for your reference.  I also included the code from my controls folder for the board.

I went through any old errors trying to find something but nothing.  Thanks for your assistance.

![firebot error](https://cloud.githubusercontent.com/assets/28618157/25935682/e3c7ad8a-35e9-11e7-9a4d-78997bfb8e81.png)

{"tactile":{"0":{"id":0,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Great Odin's Raven","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Burgandy_great odins raven.wav","soundVolume":0.5,"imagePath":"E:\\Games\\OBS Stuff\\Stream Media\\Giph\\Great-Odins-Raven-Ron-Burgundy-Cant-Believe-His-Eyes-In-Anchorman.gif","imagePosition":"top-middle","imageDuration":4000},"typeSettings":{}},"1":{"id":1,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Epic Fail","media":{"soundPath":"E:\\Games\\OBS Stuff\\ScorpBot\\SFX\\priceisrightfail_1.mp3","soundVolume":0.5,"imagePath":"E:\\Games\\OBS Stuff\\Stream Media\\Giph\\Epic Fail.gif","imagePosition":"top-middle","imageDuration":4000},"typeSettings":{}},"2":{"id":2,"type":"Nothing","cooldown":120000,"cooldownGroup":"solo","notes":"Spray and Pray","typeSettings":{},"media":{"soundPath":"","soundVolume":"","imagePath":"","imagePosition":"top-middle","imageDuration":""}},"3":{"id":3,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Instructions","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\instructions.wav","soundVolume":0.5,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"4":{"id":4,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Don't Mess with Cap","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\Captain America.wav","soundVolume":1,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"5":{"id":5,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Yoda","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\yoda-that-is-why-you-fail.mp3","soundVolume":0.5,"imagePath":"E:\\Games\\OBS Stuff\\Stream Media\\Giph\\Yoda Fail.gif","imagePosition":"top-middle","imageDuration":4000},"typeSettings":{}},"6":{"id":6,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Emergency","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\Emergency.wav","soundVolume":0.5,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"7":{"id":7,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Feeling Lucky...","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\Very accurate.wav","soundVolume":0.5,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"8":{"id":8,"type":"Media","cooldownGroup":"solo","cooldown":300000,"notes":"Globo Gym","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\Globo Gym.wav","soundVolume":0.5,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"9":{"id":9,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Die!","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\diebond.wav","soundVolume":0.5,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"10":{"id":10,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"The Fuzz","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\Hot Fuzz_noise.wav","soundVolume":1,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"11":{"id":11,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Jog On","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\Fuzz Jog On.wav","soundVolume":0.5,"imagePath":"E:\\Games\\OBS Stuff\\Stream Media\\Giph\\Fuzz Jog On.gif","imagePosition":"top-middle","imageDuration":3000},"typeSettings":{}},"12":{"id":12,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Bullets","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\bullets (1).wav","soundVolume":0.5,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"13":{"id":13,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Boom Boom","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\Boom Boom.wav","soundVolume":0.5,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"14":{"id":14,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Stark Being Stark","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\Stark being Stark.wav","soundVolume":0.5,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"15":{"id":15,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Impressed","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\impressed.wav","soundVolume":1,"imagePath":"","imagePosition":"top-middle","imageDuration":0},"typeSettings":{}},"16":{"id":16,"type":"Media","cooldownGroup":"solo","cooldown":120000,"notes":"Phixate's Off Time","media":{"soundPath":"E:\\Games\\OBS Stuff\\Stream Media\\Sounds\\Soundboard\\iron_man_theydontcallusearthmighties.mp3","soundVolume":0.5,"imagePath":"E:\\Games\\OBS Stuff\\Stream Media\\Giph\\Ironing Man.gif","imagePosition":"top-middle","imageDuration":5000},"typeSettings":{}}}}

**Comment by reecerbeam** [comment]
Also, this morning, I tried creating an entirely new board and pasting the JSON code in.  I haven't added any interaction with the buttons but I get this error.  I guess I'm having no luck here.  I'm logged in as myself (streamer) and bot.

![firebot error 1](https://cloud.githubusercontent.com/assets/28618157/25961559/5226756c-3640-11e7-8ddd-a52b60386c86.png)

**Comment by Firebottle** [comment]
Firebot does not currently support interactive 2.0. Make sure you're in the interactive 1.0 dev lab.

**Comment by reecerbeam** [comment]
I created it in the legacy dev tab, not the new interactive studio.  Is there something else I should be checking?

**Comment by Firebottle** [comment]
Try creating a board with a single button. If that works then we know its a specific type of button causing the problem.

**Comment by reecerbeam** [comment]
Thanks for the suggestion. I'm currently out of town but I'll try that when I get back.

**Comment by reecerbeam** [comment]
Created whole new board with one button and get the error below.

![firebot error 2](https://cloud.githubusercontent.com/assets/28618157/26029179/91816f72-37f4-11e7-88dd-da4ec2e92949.png)

**Comment by ThePerry-2015** [comment]
This is because you have to have the same amount of buttons in both boards. If you have 15 buttons in Dev Lab you need 15 buttons in Firebot and vice-versa. And since you only have Button 0 in firebot it will show a "random" number between 1 and 14(if that's the last button in Dev Lab) or higher if you have more buttons.

**Comment by reecerbeam** [comment]
Hello,

That was a new board I made in DevLab as I was instructed to in the thread.
Both only have one button. I didn't create any buttons in FireBot. I simply
just imported the board with the JSON code and that was the error.

**Comment by ThePerry-2015** [comment]
Aha, I supposed you had multiple buttons in the new dev lab board as it said you were missing buttons. Then I'm not quite sure, mine seems to work just fine with a both brand new boards and my old boards.

**Comment by reecerbeam** [comment]
With another streamer's help, this has been solved.
