### ISSUE TITLE
Button Improvements

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#94]
I plan on making it so that you can change button text and spark cost through Firebot instead of need to revisit the studio for that.

To Do:
- Ability to change sparks in app.
- Ability to disable a button in the app.
- Ability to change button text in the app.

To do this we'd need a process that runs right after connecting but before readying the board. This process would go through each button and send updates to mixer with the new values.

After that we'd need a separate process that updates on a per button basis as soon as someone hits save in the app.

**Comment by FluffyMatt** [comment]
Could you also have the ability to place the buttons too? I found using the Studio rather awkward and found it difficult to handle lots of buttons and placing them on the grid was quite painful.

**Comment by Firebottle** [comment]
Sorry, I don't have plans to remake the interactive studio. But, it will get better with time as they fix bugs.

**Comment by Firebottle** [comment]
Added the ability to change active status, button text, and spark cost through Firebot. Upon connecting to interactive Firebot will loop through everything and make those changes again. So you no longer need to visit the dev lab for these items.

**Comment by Firebottle** [comment]
Released 4.4.0
