### ISSUE TITLE
Overlay folder missing in V3.0.0

### ISSUE THREAD

**Issue by FluffyMatt** [Firebottle/Firebot#95]
Looking into the new release and it appears the overlay folder which housed the ability to see images in OBS and use the Celebration fireworks appears to be missing. 

Is there a new way of doing this in OBS?

**Comment by Firebottle** [comment]
Oh wow, I just forgot to include it. Give me a second to get a new upload in place.

**Comment by Firebottle** [comment]
Okay, just uploaded a new zip with the missing folder. Also uploaded the overlay folder separately in case you just want to download that. Sorry!

You add it to OBS the exact same way that you did in Firebot v2.

**Comment by FluffyMatt** [comment]
Great! Thanks very much :)
