### ISSUE TITLE
Play sound volume setting

### ISSUE THREAD

**Issue by FluffyMatt** [Firebottle/Firebot#96]
The play sound volume setting can be set higher than 10 for example 102 this causes the sound to be distorted. Could this be limited to prevent accidentally messing it up?

**Comment by Firebottle** [comment]
Sure, it'll be lower priority since the text for it does say 1-10. Plus, there might be people that want a sound to be over 100% volume.

**Comment by FluffyMatt** [comment]
Ahh make perfect sense. I wasn't sure if you wanted people to only do 1-10, I'll close this off as it is works fine.

**Comment by Firebottle** [comment]
@FluffyMatt thank you soooo much for entering this stuff. I really do appreciate the help and ideas.

**Comment by FluffyMatt** [comment]
No worries @Firebottle as a DEV myself I know feedback is really handy.
