### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by Brandonmig** [Firebottle/Firebot#98]
when adding a picture to show,  im picking png and gifs and they are not showing up on the preview browser.    HELP!!! lol

**Comment by Firebottle** [comment]
Make sure to load up the overlay into OBS or XSplit. It's located in the Firebot folder. /firebot/overlay/firebot.html.

If you're missing the overlay folder, go back to the releases page and download it. I accidently forgot to include it in the initial Firebot upload.
